### ISSUE TITLE
Trouble with Setup [ Windows 7 with Service Pack 1 ]

### ISSUE THREAD

**Issue by obernikhin** [Bionus/imgbrd-grabber#620] opened 2016-09-22 15:47 UTC
### What steps will reproduce the problem?
Select "Russian" in installer.

After pressing "Install" button in Installer ( After you select directory, shortcut and etc. )

### What is the expected behavior? What do you get instead?
Error log in attachment

 I get an error:
 "Runtime Error (at 29:206)
Внутренняя ошибка: ExtractTemporaryFile: The file "" was not found."

### What version of the program are you using? On what operating system?
From Grabber 4.5.3 to Grabber 4.7.0
OS:
Windows 7 with Service Pack 1  x64

### Please provide any additional information below
previous versions works fine.

**Comment by obernikhin** [comment] 2016-09-22 15:48
Error log

[errorlog.txt](https://github.com/Bionus/imgbrd-grabber/files/487712/errorlog.txt)

**Comment by collanity** [comment] 2016-09-22 20:56
Устанавливай на английском языке. Проблемы с русским языком.

**Comment by Flat** [comment] 2016-09-22 23:43
Duplicate of #611

**Comment by Bionus** [comment] 2016-09-23 12:47
Yes,

As said in issue #611, you should install it with the English language.
I thought I already updated the installer, but seems like I did not. I'll change the installer tonight and remove the broken locales from it.

**Closed by Bionus** 2016-09-23 12:47 UTC
