### ISSUE TITLE
Unknown source when downloading images from gelbooru user favorites

### ISSUE THREAD

**Issue by redthrowred** [Bionus/imgbrd-grabber#2253] opened 2021-02-02 08:07 UTC
**Bug description**
Source is not found for images from gelbooru user favorites.

**Steps to reproduce**

1. Select "gelbooru" in "sources."
2. Search for a user's favorites (e.g. fav:727453). 
3. Click on any image. 
4. The new window says "Image not Found," and in the details tab, the source is simply "Unknown."

**Expected behavior**

The source should exist; additionally, the image's resolution is very low when downloaded, since it just uses the thumbnail (as I understand it).

**Context**

This problem only occurs when searching favorites pages--I didn't find a problem searching keywords.

**Screenshots**

![Capture1](https://user-images.githubusercontent.com/78407852/106570463-e8cd2d80-6503-11eb-8f64-8b1ed157160c.PNG)
![Capture2](https://user-images.githubusercontent.com/78407852/106570476-ebc81e00-6503-11eb-98ef-a1201d135671.PNG)

**System information**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/5909581/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/5909549/settings.txt)

- OS: Windows 10
- Grabber version: 7.3.2

Add any other context about the bug report here.

**Comment by yami-no-tusbas** [comment] 2021-02-02 10:00
Seems to be ok in nightly, seems to be related to #2235. 
Yeah this is the html modification that gelbooru did some times ago, the fix should be up in version 7.3.3 as it is working now fine on nightly.

Duplicate of #2235

**Comment by Chumbucket420** [comment] 2021-02-02 13:16
I am having the same issue with gelbooru favorites even after switching to the latest nightly release, it only finds the image thumbnails. Works perfectly fine for any other tags.

**Comment by redthrowred** [comment] 2021-02-04 06:41
I also just tried a fresh install of the nightly version and couldn't seem to get it to work.

**Closed** 2022-03-26 22:23 UTC
Labels: bug, source, reproduced
