### ISSUE TITLE
%md5% is not working

### ISSUE THREAD

**Issue by help-me-please** [Bionus/imgbrd-grabber#1015] opened 2017-08-05 21:05 UTC
### What steps will reproduce the problem?
little_witch_academia source is gelbooru.com
Name is "%md5%.%ext%"
Clicked "Get this page"
Go to download tab then clicked download
Output: https://ibb.co/m0cwjv
![screenshot_20170806045551](https://user-images.githubusercontent.com/30758689/28998722-ae73021e-7a64-11e7-9916-95b8606f50c8.png)

Log tab: https://ibb.co/jwhCPv
![screenshot_20170806045743](https://user-images.githubusercontent.com/30758689/28998723-b6615192-7a64-11e7-8775-0463c8b89328.png)

Destination Folder: https://ibb.co/mj2CPv
![screenshot_20170806045838](https://user-images.githubusercontent.com/30758689/28998726-bd0252d0-7a64-11e7-9fb0-f018a0ae5815.png)

### What is the expected behavior? What do you get instead?
To have 20 pictures with different file names
Only downloads different extensions like 1 jpg and 1 png or  1 jpg, 1 png, and 1 gif and Filenames are none

### How often does this problem occur?
Always

### What version of the program are you using? On what operating system?
Grabber_5.4.2 on Windows 7

### Please provide any additional information below
I also tried from danbooru.donmai.us still same result

**Comment by BarryMode** [comment] 2017-08-07 18:47
%md5% works for me, however, %path% is outputting as %path% in the separate log file.

**Comment by Bionus** [comment] 2017-08-07 19:58
I can't reproduce the issue either.
Does this happen on every source or only Gelbooru?

If you open the page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=&tags=little_witch_academia right after a failed loading, do you see the "md5" field properly set in the XML file?

When I open it, I for example have:

```xml
<post height="1000" score="0" file_url="//gelbooru.com/images/9f/49/9f494fae3a0d64cf1b690953965b2daa.png" parent_id="" sample_url="//assets2.gelbooru.com/samples/9f/49/sample_9f494fae3a0d64cf1b690953965b2daa.jpg" sample_width="850" sample_height="412" preview_url="//assets.gelbooru.com/thumbnails/9f/49/thumbnail_9f494fae3a0d64cf1b690953965b2daa.jpg" rating="s" tags=" 1girl backlighting blonde_hair blue_eyes blurry blurry_background book chair depth_of_field diana_cavendish highres indoors light light_particles lipgloss lips little_witch_academia maredoro multicolored_hair open_collar reading shirt sitting smile solo two-tone_hair white_shirt window " id="3821198" width="2064" change="1502130576" md5="9f494fae3a0d64cf1b690953965b2daa" creator_id="6498" has_children="false" created_at="Mon Aug 07 13:29:23 -0500 2017" status="active" source="https://i.pximg.net/img-original/img/2017/08/08/00/00/01/64284450_p0.png" has_notes="false" has_comments="false" preview_width="150" preview_height="72"/>
```

Which has the proper `md5="9f494fae3a0d64cf1b690953965b2daa"` set.

_@BarryMode: fixed on `develop` by 541aeac1216aa7eaf588c80854b6c68c7fb939ea._

**Comment by MasterPetrik** [comment] 2017-09-26 06:06
also can't reproduce the issue either.

**Comment by MasterPetrik** [comment] 2017-09-26 06:07
@help-me-please is it still relevent in last grabber version?

**Closed** 2018-04-29 14:12 UTC
Labels: bug, cant-reproduce, source
