### ISSUE TITLE
No Result for Sankaku Complex

### ISSUE THREAD

**Issue by jackx2323** [Bionus/imgbrd-grabber#1000] opened 2017-07-18 03:26 UTC
### What steps will reproduce the problem?

Every search in Sankaku Complex gives me a "No result" answer. It´s the only site I'm having trouble with.

### What version of the program are you using? On what operating system?

Grabber 5.4.2
Windows 8.1 x64

**Comment by urzuse7en** [comment] 2017-07-18 11:50
Duplicate of #997 
Just wait for the new release now.

**Closed** 2017-07-20 17:15 UTC
Labels: duplicate
