### ISSUE TITLE
Crashes literally everywhere

### ISSUE THREAD

**Issue by theHubi** [Bionus/imgbrd-grabber#392] opened 2015-06-05 22:21 UTC
Aside from the fact that I liked the old design a lot more (less buttons) and some things are not translated from French to English.

The new Grabber is useless. Thank you for your efforts, Bionus, but why release an update that makes your program crash in every instance.

Click on something you deleted in the sources list (because saving sources from version to version seems to be impossible for some reason), Grabber crashes.
Add images to download, Grabber crashes.

What on earth did you do? A complete recode?

**Comment by Bionus** [comment] 2015-06-05 22:44
Hello

> I liked the old design a lot more (less buttons)

Which buttons are you talking about? The ones on the search tab near the "Sources" button, or the ones on the downloads tab?
Which ones would you remove, or how would you redesign them? I'm open to suggestions.

> The new Grabber is useless. Thank you for your efforts, Bionus, but why release an update that makes your program crash in every instance.
Think a second that you may be a special case. It doesn't crash "in every instance" on my fresh VM XP as well as my own computer.

> Click on something you deleted in the sources list (because saving sources from version to version seems to be impossible for some reason), Grabber crashes.
> Add images to download, Grabber crashes.

You mean when doing something such as:
1. Add a source
2. Search
3. Delete said source
4. Open a search result
If so, I agree I haven't tested this case (since I don't see why someone would do this) so it may indeed crash, I'll check it out.

**Comment by theHubi** [comment] 2015-06-06 09:16
The ones on the download tab. But that's just personal preference. Still I would say: The less button on a single spot the easier to figure out it is. 3.5 had... 4? I think it was 4 buttons in the download tab. The new one has 8.

I mean:
1. Install the new version (you get like 15 sources which I instantly clean up to about 5 or 6)
2. Remove a source (it doesn't get completely removed, the text just disappears.
3. Click on the line where the source was
4. Program crashes

It also crashes in every instance when I try to download just about anything. I tried with a couple 1000 images, 100 images and 10 images. Both on "Download All" and on "Download Selected"

I'm just wondering what you did to make your "perfectly working" program have so many crashes.
Did you do a complete recode from Version 3 to Version 4?
I'm a programmer (well.. webdev, but still) as well, so I guess there's either a problem with a loop or you forgot a bracket somewhere : P

**Comment by Bionus** [comment] 2015-06-06 13:37
Yes, there are more buttons because there are more features there (moving and deleting single downloads if I remember correctly). I could reorganize them though, make them into a single line, and change the "Move up"/down by some icons.

> I'm just wondering what you did to make your "perfectly working" program have so many crashes.
> Did you do a complete recode from Version 3 to Version 4?

I just changed the memory management which leaked from everywhere in previous versions, leading to crashes on big downloads and at totally random times.

**Comment by theHubi** [comment] 2015-06-06 14:21
Here's how I used Grabber in the past:
1. Add to download
2. if less than 5000 images -> Download, else download small groups <1000 images with "Download Selected"
3. Pressed Delete after download was done, no visual button needed.
Moving stuff up and down.. not really necessary if you ask me, as you can select what to download first and you're gonna download all of them eventually anyway.
Yeah.. the only time I experienced crashes with the 3.5 was when downloading more than 20.000 images at once. But as I found out afterwards, that's because Gelbooru does not let you download more than 20.000 images at once.

And memory usage... meh. I got 16 GBs and most of the time only 8 are used.

**Comment by Bionus** [comment] 2015-06-06 14:54
I see. I guess many users do like this, it's not the first time I read it.
But you're actually the first one who didn't experience crashes using the v3.5.

> Moving stuff up and down.. not really necessary if you ask me, as you can select what to download first and you're gonna download all of them eventually anyway.

The rationale for this one was that when you start all downloads at once, they are downloaded from top to bottom. So if you want to download the third line first, while it is true that you could just use "Download selected" then download the others, you don't necessarily want to go there for each download.

> And memory usage... meh. I got 16 GBs and most of the time only 8 are used.

With the changes I made Grabber should not go above 100 MB memory usage, even during big batch downloads. Before, it could go up to a few GB of RAM pretty fast, also leading to unexpected behavior. Most users only have 4 GB, so going above 500 MB / 1 GB is pretty much out of the question (especially when it's actually feasible not to).

**Comment by Bionus** [comment] 2015-06-06 15:12
> 1. Install the new version (you get like 15 sources which I instantly clean up to about 5 or 6)
> 2. Remove a source (it doesn't get completely removed, the text just disappears.
> 3. Click on the line where the source was
> 4. Program crashes

By the way this issue should also be fixed with the 4.1.3 version (see issue #390).

**Closed by Bionus** 2015-06-06 15:12 UTC
