### ISSUE TITLE
chan.sakaku still not loading tag types on time 

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#608] opened 2016-09-12 10:04 UTC
Same as issue https://github.com/Bionus/imgbrd-grabber/issues/597

Now it downloads most images with the proper filenames but some of them not.
If i download manually and wait for the tag types to load then click save it downloads them correctly but in batch download it does not.
It occurs with the same images sometimes and sometimes not (i have deleted and redownloaded the files to test)

**Comment by Bionus** [comment] 2016-09-13 20:34
So you mean issue #597 was actually not fixed, but it now happens less often?

I'm not sure I understand for batch downloads, you mean most filenames are wrong during batch downloads?

**Comment by elreymu** [comment] 2016-09-14 01:39
Yeah it happens less often, i think it has something to do with the simultaneous downloads feature, sometimes it downloads 2 images at once and doesn't wait for the tags in the second one in batch download

**Comment by VeryCrushed** [comment] 2016-10-22 06:47
Can confirm this as a issue, only on batch downloads though. You can view individual files fine, but as soon as you try to use the batch downloader it doesn't grab all the tag categories.

**Comment by VeryCrushed** [comment] 2016-11-13 23:56
@Bionus You seem to be working hard on this project today, any chance you could potentially get a fix in for this? Not being able to use batch downloads is a real pain

**Comment by Bionus** [comment] 2016-11-14 00:29
@VeryCrushed I can add the investigation and fix for this on my roadmap yes, but I can only use idol.sankaku from my country, chan.sankaku is blocked. Does this issue also happen on it?

**Comment by VeryCrushed** [comment] 2016-11-14 02:32
@Bionus It is possible to test with idol.sankaku

Its definitely an issue with batch downloading, as in browsing for images on a search tab and using ether the "Get This Page", "Get Selected", or "Get All" buttons. Selecting an image in the search tab and using the "Save" or "Save and Close" buttons work as intended.

If you use the "Save->Separate text file" options and set the string to %all:includenamespace,separator= ,unsafe% and try to use the batch downloader, all tags start with unknown: rather then the actual categories.

If you use commands to upload pictures with the batch uploader to another site, all tags will start with unknown. I have tested this both with MyImouto and Danbooru 2 inside a VM, and both result in tags without categories. However it works fine by individually downloading pictures.

Whats really interesting is this actually happens on all websites, except for one. Danbooru is the only one without this issue.  The commit you made originally (e2c6c5c72a844cb5e8eb1310e6179854d18f1254) to fix the issue only applied to the downloads done through the search area, not batch downloads as far as i can tell. Id attempt a fix myself, just dont know the code base very well enough to get it done. Looks like all the logic you applied to the files in /src/viewer needs to be applied to /src/batch

If you need anything else, feel free to ask. I check my email consistently and will get back ASAP.

**Comment by Bionus** [comment] 2016-11-15 23:48
I'll check this in more details for next update then

> The commit you made originally (e2c6c5c) to fix the issue only applied to the downloads done through the search area, not batch downloads as far as i can tell. Id attempt a fix myself, just dont know the code base very well enough to get it done. Looks like all the logic you applied to the files in /src/viewer needs to be applied to /src/batch

It's been added separately: [mainwindow.cpp](https://github.com/Bionus/imgbrd-grabber/blob/master/src/mainwindow.cpp#L1346). But since this was included in the latest release, which did not fix the issue, it will need more investigation.

**Comment by VeryCrushed** [comment] 2016-11-17 00:10
@Bionus So finally got a good setup with Qt and MSVC debugger so i was able to take a look at it myself, may just submit a pull request with a fix if that works.

mainwindow.cpp about line 1479 if (m_must_get_tags)

Id say at this point we should always get tags first making this pointless, adding if m_must_get_tags = true; right before this bit of code results in categories being loaded successfully.

**Comment by VeryCrushed** [comment] 2016-11-17 00:31
Actually, now looking more into it yeah we set m_must_get_tags to true if the filename requires it but not if saving a text file requires it or even if commands require it. Im gonna see about having needExactTags check commands as well as the text file

**Comment by Bionus** [comment] 2016-11-17 00:45
Indeed, thinking about it there's no check on the log file filename format for the `m_must_get_tags` variable. I guess replacing the `m_must_get_tags = false;` at the beginning by something like `m_must_get_tags = Filename(separateLogFormat).needExactTags();` would fix the problem. Since it seems you're already on it, I'll let you do a PR, unless you'd rather have me push some fix.

And this doesn't happen in the image window since the tags are always downloaded anyway.

*PS: I'm quite sorry you have to fiddle in `mainwindow.cpp`, that's the worst file of the project.* 😓

**Comment by VeryCrushed** [comment] 2016-11-17 03:21
Pull request is in, tested it and looks to be working properly. Only issues that may arise is if there are any other % variables that need tag info loaded. %all% seems to be setup fine right now using includenamespace but may need to be a bit more aggressive checking. Maybe need a parser like class that just checks strings for variables and has public facing variables to determine when a instance of a tag was replaced and what parameters it had.

Aside from that mainwindow.cpp really needs to shrink down, there is a lot of code that should be moved out and into ether a static utility class or moved into an existing one where the code fits in better. Lets just leave that for another day ;)

**Closed** 2016-11-20 23:08 UTC
Labels: bug
