### ISSUE TITLE
In ver 5.3.2 tabs erases after exit

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#930] opened 2017-05-24 01:23 UTC
### What steps will reproduce the problem?
1. Open some tabs
2. Close Grabber
3. Open Grabber again
4. in 90% cases tabs will not be restored, you will lose it.

### How often does this problem occur?
Almost in all cases.

### What version of the program are you using? On what operating system?
5.3.2. win 7
it starts from current version
It 100% wasn't happen in 5.3.0.alpha and earlier versions

### Please provide any additional information below
I lost all my tabs.... twise. there was 56+ tabs :(
Please do something with that.

**Comment by Bionus** [comment] 2017-05-24 22:26
> in 90% cases tabs will not be restored, you will lose it.

So you mean it does not always happen?

Because I just tried to open a few tabs, change pages, change sources, open new tabs, merged and not merged, etc. When I closed and re-opened they were still there.

Because I agree this is a major issue (losing tabs is a real pain) but if you had some way to reproduce that'd help a lot. For example, your `tabs.txt` file before opening the program + a few actions that will 100% cause the tabs to not save.

**Comment by MasterPetrik** [comment] 2017-05-24 23:10
It's very strange... I tried it yesterday many times and it was around 90% repeatability.
But today I tried many times but can't reproduse even a single time. So I now a bit confused.
I will see, will it happen again, but now, I guess you can freeze or close this issue.

**Comment by Bionus** [comment] 2017-05-25 00:56
> It's very strange... I tried it yesterday many times and it was around 90% repeatability.
> But today I tried many times but can't reproduse even a single time. So I now a bit confused.

That could be an indicator that it either depended from something that happened on some source, some network issue or simply different tabs/settings. But that sounds improbable given all of those are unrelated to the way tabs save.

>  I will see, will it happen again, but now, I guess you can freeze or close this issue and remove it from 5.3.3 plan..

I'll remove it from the 5.3.3 roadmap then.

> well, you know that if I can, then I try to investigate and reproduse all issues that I reporting)

Yeah, I know that. Your issues are actually part of the ones giving enough details to reproduce bugs easily (in cases where it's possible at least). :+1:

This remark was more of an introduction for the next sentence that maybe it's related to the initial state of the `tabs.txt` file (corruption, special tab order inside, etc.) so maybe always starting from the same one could help make it reproducible :smile:

**Comment by MasterPetrik** [comment] 2017-05-25 01:01
can you instead add https://github.com/Bionus/imgbrd-grabber/issues/851 to 5.3.3 plan?... just asking)

**Comment by MasterPetrik** [comment] 2017-06-17 21:25
I don't faced with this promlem simce then, so I will close the issue

**Closed** 2017-06-17 21:26 UTC
Labels: bug
