### ISSUE TITLE
Cannot download images or videos from rule34.xxx

### ISSUE THREAD

**Issue by hentaiwhite** [Bionus/imgbrd-grabber#2387] opened 2021-06-13 01:39 UTC
The log show this message

> [19:33:31.764][Info] Batch download started.
[19:33:31.776][Info] All images' urls have been received (254).
[19:33:31.781][Info] Loading image from https://api-cdn.rule34.xxx/images/4231/9eb11261ed136ee28276b774f7d40d63.jpeg 1
[19:33:31.781][Info] Loading image details from https://rule34.xxx/index.php?page=post&s=view&id=4812286
[19:33:31.969][Error] Loading error for 'https://rule34.xxx/index.php?page=post&s=view&id=4812286': Error transferring https://rule34.xxx/index.php?page=post&s=view&id=4812286 - server replied: Service Temporarily Unavailable

**Comment by TempMonkas** [comment] 2021-06-13 03:23
Same issue here.

**Comment by Bionus** [comment] 2021-06-13 08:42
Duplicate of #2384

**Closed by Bionus** 2021-06-13 08:42 UTC
