### ISSUE TITLE
Monitor option for default Delay and default Interval in minutes

### ISSUE THREAD

**Issue by VeggieJay** [Bionus/imgbrd-grabber#2934] opened 2023-03-18 02:00 UTC
**Is your feature request related to a problem? Please describe**

It looks like the default Monitor interval is 1440 min and delay is 0 min, but it would be really nice to have the option to set new defaults

**Describe the solution you'd like**

A setting in Options -> Monitoring where these values can be set 

**Describe alternatives you've considered**

Can't think of any clean alternatives

**Comment by Bionus** [comment] 2023-03-25 14:03
Closing as duplicate of #2882 👍

**Closed by Bionus** 2023-03-25 14:03 UTC
Labels: duplicate, suggestion
