### ISSUE TITLE
SANKAKU COMPLEX??

### ISSUE THREAD

**Issue by maxman2103** [Bionus/imgbrd-grabber#1067] opened 2017-09-11 13:59 UTC
### What steps will reproduce the problem?

batch download does not work...

### What is the expected behavior? What do you get instead?

when batch downloading

### How often does this problem occur? On which sources?

https://chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
5.5.0

### Please provide any additional information below
plz..fix this problem in the next version or tell me is there any way to download batch from chan.sankaku

**Comment by NavinF** [comment] 2017-09-11 21:23
Known problem. See the main thread: #997

**Comment by MasterPetrik** [comment] 2017-09-13 23:28
@Bionus recommend to close this issue due to duplicate of #997

**Comment by BarryMode** [comment] 2017-09-14 00:10
It works fine. The host is just refusing the program.

**Closed** 2017-09-14 00:11 UTC
