### ISSUE TITLE
grabber downloading a maximum of 20 images per page on chan.sankaku

### ISSUE THREAD

**Issue by elreymu** [Bionus/imgbrd-grabber#609] opened 2016-09-12 10:08 UTC
For example, when i set it to show 30 images per page and click "get this page"

It will download only 20 out of those 30.

If i set it to show 40 or anything else, it will download the first 20 only even if the batch displays its going to download 40.

However if i set it to display 15, then it will actually download 15 correctly.

**Comment by Bionus** [comment] 2016-09-13 20:42
How do you even manage to load pages with other images/page than 20 on Sankaku?

From what I remember, they voluntarily removed the support for the images/page setting, forcing it to 20. Which would explain what happens in your case. And when you ask for a limit under the actual number of images returned by the website, Grabber will drop the images (in that case, Grabber will drop the remaining 5 images for a search for 15 images if Sankaku returns 20).

**Comment by elreymu** [comment] 2016-09-14 01:51
I don't know why i can, but here's a screenshot that shows it can even load 60 images in one page
![sankakulimit](https://cloud.githubusercontent.com/assets/17685263/18497283/1daaab68-79ea-11e6-967d-5cecf90310ff.png)


So you say if i ask for 15 images it will return 20 always?
Here's what happens in my case.
![sankakulimit2](https://cloud.githubusercontent.com/assets/17685263/18497402/32b148b8-79eb-11e6-9598-a57a9bb424e2.png)
![sankakulimit3](https://cloud.githubusercontent.com/assets/17685263/18497403/376497fc-79eb-11e6-9bb2-8b44ca6c3eed.png)

It downloads 15 and nothing more as expected.

**Comment by Bionus** [comment] 2016-10-08 23:44
Indeed, I could reproduce just now, so I pushed a fix which should be included in the next update.
It was caused by some internal setting that forced the images/page to 20, even though logged in users can actually change it up to 200.

Thanks! :smile:

**Closed** 2016-10-09 15:49 UTC
Labels: bug, source
