### ISSUE TITLE
[BUG] Error loading the image (Gelbooru)

### ISSUE THREAD

**Issue by Babyforce** [Bionus/imgbrd-grabber#1437] opened 2018-09-29 21:57 UTC
**Bug description**

Sometimes, an image from Gelbooru won't load in the image viewer and will leave the message "Error loading the image"

**Steps to reproduce**

1. Select "Gelbooru" as source and click OK to start browsing
2. Click on some images (Sometimes, the error displays and the image stays pixelated)

**Expected behavior**

The image is supposed to fully load and no error is supposed to show up.

**Context**

This is the error I get in the log when it tries to load the image:
`[23:36:56.403][Info] Loading image from `https://simg4.gelbooru.com/images/dd/ae/ddae791db5ab346f6b7268f195c4c1f2.jpg`
[23:36:56.413][Info] Loading and saving image in `path\8621f75c-79ed-49aa-a38b-547029011b17.jpg`
[23:36:56.449][Error] Network error for the image: `https://simg4.gelbooru.com/images/dd/ae/ddae791db5ab346f6b7268f195c4c1f2.jpg`: 3 (Host simg4.gelbooru.com not found)
[23:36:56.450][Info] Image received from `https://simg4.gelbooru.com/images/dd/ae/ddae791db5ab346f6b7268f195c4c1f2.jpg`
[23:36:56.451][Info] Error loading the image.
`

**Screenshots**

![grabber_2018-09-29_23-52-10](https://user-images.githubusercontent.com/1695422/46250818-530cc980-c443-11e8-9a60-d61ccc8c057c.jpg)

**System information**

- OS: Windows 10, but also happens in Ubuntu 18.04
- Grabber version: 6.0.5

**Additional context**

After a few tests in a browser, I noticed that links in simg3.gelbooru.com were opening, but not simg4. I tried opening the link from the log by replacing the 4 with a 3 and it was working. I believe the grabber somehow changes this number at some points, but I cannot figure out why. I tried reinstalling the software and deleting the settings file but I got no luck.

**Comment by Bionus** [comment] 2018-09-30 07:04
Indeed!

It seems that `simg4` has been deprecated in favor of `simg3`, which broke the Gelbooru integration which was forcing it because of a bug in their API a few years ago.

You have three options to fix the issue:
* Wait for the 6.0.6 release by the end of the day
* Use the nightly version
* Edit `C:\Users\Nicolas\AppData\Local\%USERNAME%\Grabber\sites\Gelbooru (0.2)\model.js` and remove the line `img["file_url"] = img["file_url"].replace("/gelbooru.com/", "/simg4.gelbooru.com/");`

I'm marking this as a duplicate of issue #1410, which was closed so you might have missed it (so I reopened it). You can see the whole context there.

**Closed by Bionus** 2018-09-30 07:04 UTC
Labels: bug, duplicate, source
