### ISSUE TITLE
Not working on rule34.xxx

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#2385] opened 2021-06-11 21:06 UTC
This seems new, the past few days maybe. I tried searching "wutboi -dark-skinned_male" and it comes up just fine. But when trying to download them the downloads just never start. They just stay at 0%. The weird thing is if you do copy link a link would come up like [this](https://api-cdn-mp4.rule34.xxx/images/4223/4b9f188a952deefdfc7ae230c8c326ea.mp4) which loads just fine in Chrome. But Grabber itself isn't downloading the files. The downloads just won't initiate. Tried with 7.5.1 (x64) and an earlier version.

**Comment by Tiffys** [comment] 2021-06-11 21:15
I'll add for the time being as a workaround a user can use the copy links button after selecting the entire download queue then paste those into something like JDownloader 2 and it bypasses needing the API and downloads via the links directly.

**Comment by maxzmud** [comment] 2021-06-11 21:26
I'm also having this problem

**Comment by ayoits0913** [comment] 2021-06-12 03:56
yep they check for bots now. looking for a fix too

**Comment by Bionus** [comment] 2021-06-12 14:01
Closing as duplicate of #2384

**Closed by Bionus** 2021-06-12 14:01 UTC
Labels: bug, duplicate, source
