### ISSUE TITLE
Unable to "update" collection with new images in tag groups

### ISSUE THREAD

**Issue by MisterSnaivi** [Bionus/imgbrd-grabber#1059] opened 2017-09-07 20:46 UTC
### What steps will reproduce the problem?

Batch download with, I would imagine, over 30-50K images, most of which already exists in the HDD.

### What is the expected behavior? What do you get instead?

Check the tags listed for download, check what images of said tags already exist, download only new images. Instead, eventually crashes during the process.

### How often does this problem occur? On which sources?

Everytime. e621.net.

### What version of the program are you using? On what operating system?

5.5.0. Windows 10.

### Please provide any additional information below
I know this kind of problem has been reported several times already, but please help me out here.

I keep several (99 at the time of writing) groups of tags on my download list, with the intent of having Grabber check those tags, check my harddrive for images that already exists, and only download images newly uploaded to these tags. It does that, but crashes after a couple of pages.. I've tried to tweak my settings to prevent this, to no avail.
I would imagine this happens because the program is taking in too many images... But again, I only want it to check for new images, and I'm not sure if I can make the program do just that.

Crash dump, log file, settings file and igl file all available in the included zip file.

[Crash.zip](https://github.com/Bionus/imgbrd-grabber/files/1286068/Crash.zip)

**Comment by Bionus** [comment] 2017-09-08 12:51
Does it succeed in downloading images from the the first few pages before crashing?

The crash may be caused by the fact that a whole "pack" of images (1,000) already exists on the HDD. I'll take a look and see if I can reproduce.

**Comment by MisterSnaivi** [comment] 2017-09-08 17:53
Yes, it does check and download new images from the first few pages.

**Comment by brazenvoid** [comment] 2017-09-10 02:24
@MisterSnaivi I do have a workaround for you because I have done all of this for quite some time now. 

- You will have to keep the list of tag groups along with last count values in a spreadsheet and only download the difference of count values. 
- If the difference in count values is less than 1,000 then once you create the batch download, change the "Images Per Page" and "Image Limit" to that value. Otherwise only change the limit value to it.

This way the program does not encounter the already downloaded files and survives the onslaught of image found conditions. 

- It usually crashes after 5-20 pages of existing files. But that's only if the first page has new files. 
- If the first page has no new files then the image download simply finishes at the end of that page, forcing me to iterate over every page to find the file where the download last broke for whatever reason. That's a situation, I pray, I don't find myself in.

**Comment by Bionus** [comment] 2017-10-30 10:24
Should be fixed in `v5.5.2`. :+1:
Feel free to re-open if there still are problems.

**Closed by Bionus** 2017-10-30 10:24 UTC
Labels: crash
