### ISSUE TITLE
Crash after starting

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#679] opened 2016-11-24 03:17 UTC
### What steps will reproduce the problem?

Open it

### What is the expected behavior? What do you get instead?

............

### What version of the program are you using? On what operating system?
latest beta version or whatever on win 10

### Please provide any additional information below

[Crash.zip](https://github.com/Bionus/imgbrd-grabber/files/610409/Crash.zip)

**Comment by brodycas3** [comment] 2016-11-24 03:23
Went back to the stable v4.9.1 and the crashing stopped but that's still a problem if it crashes from no interaction with me.

**Comment by Bionus** [comment] 2016-11-27 20:58
Indeed, it was caused by the "merge results" feature with the new scroll layout. I pushed a fix, thanks!

**Closed** 2016-11-27 21:55 UTC
Labels: crash
