### ISSUE TITLE
E621 not working/displaying image results

### ISSUE THREAD

**Issue by SilverSilver10** [Bionus/imgbrd-grabber#1933] opened 2020-04-12 00:44 UTC
When I search for something, nothing comes up displayed under E621, I click the link to the search page and there are indeed images on that character present.
This started occurring some time back but I decided to wait to see if an update would fix it, no improvement.

**Comment by Bionus** [comment] 2020-04-12 17:25
Marking as duplicate of issue #1895.
Please post there if you have additional questions. FYI, e621 is already fixed in [nightly releases](https://github.com/Bionus/imgbrd-grabber/releases/nightly) 👍

**Closed by Bionus** 2020-04-12 17:25 UTC
