### ISSUE TITLE
Android crash when adding tag to favorites

### ISSUE THREAD

**Issue by Gilgamesh0028** [Bionus/imgbrd-grabber#3170] opened 2024-05-21 14:55 UTC
latest version, attempt to add a tag to favorites, and it crashes.

![Screenshot_20240521-085445](https://github.com/Bionus/imgbrd-grabber/assets/98428877/460ac5f0-a063-4d0e-8cdd-233dca161ae5)
can't get a log from the post crash,but this is what it shows when I launch the app.

**Comment by Bionus** [comment] 2024-05-24 21:48
Strange. It says you didn't grant write permissions, could that be the case? If you go to your Android settings to check the permissions granted to Grabber, if you grant storage permissions, would that solve the issue?

Although normally, Grabber doesn't need write permissions since it only writes to its own data directory or the save directory for which you give explicit writing rights in the settings.

**Comment by Gilgamesh0028** [comment] 2024-05-24 22:36
copying the discord convo:  >>https://discord.com/channels/780466420877361156/780466421464694786/1243691327305154610

screenshots are available when scrolling down.

**Comment by Bionus** [comment] 2024-05-25 12:50
Closing as duplicate of #3164 then for now since they seem to stem from the same issue.

**Closed by Bionus** 2024-05-25 12:50 UTC
Labels: crash, cant-reproduce, android
