### ISSUE TITLE
Can't login to Pixiv on Grabber

### ISSUE THREAD

**Issue by XxHaruoZxX** [Bionus/imgbrd-grabber#2270] opened 2021-02-18 16:24 UTC
I looked at other posts and tried their solutions, I couldn't find anything that would work for me.
I heard that changing your password is the cause, how do I overcome this?

This is what my log said. : 
[Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
[Info] [www.pixiv.net] Login finished: failure.

I'm completely uneducated on these btw. So I have absolutely no idea what I'm looking at.

**Comment by Bionus** [comment] 2021-02-18 19:05
Closing as duplicate of #2263.
I have yet to investigate that issue though 😓

**Closed by Bionus** 2021-02-18 19:05 UTC
