### ISSUE TITLE
Trouble downloading images from zerochan

### ISSUE THREAD

**Issue by kml2103** [Bionus/imgbrd-grabber#1235] opened 2018-04-03 18:21 UTC
### What steps will reproduce the problem?
selecting "get all"
downloading selected option

### What is the expected behavior? What do you get instead?
every image should be downloaded, but only one is while stating that the files are already existing.

### How often does this problem occur? On which sources?
every time I try to download from zerochan

### What version of the program are you using? On what operating system?
5.5.2 & win10

### Please provide any additional information below
![image](https://user-images.githubusercontent.com/38049457/38267674-2e0840d2-374a-11e8-878c-c81a9e01171e.png)

**Comment by Bionus** [comment] 2018-04-04 20:41
Duplicate of #1165.

I advice changing your filename to `%id%.%ext%` or use the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) version (at your own risk). More explanations are given in the other ticket. 😃

**Closed by Bionus** 2018-04-04 20:41 UTC
Labels: bug, duplicate, source
