### ISSUE TITLE
error

### ISSUE THREAD

**Issue by falsamr** [Bionus/imgbrd-grabber#555] opened 2016-07-02 08:08 UTC
error when i use proxy setting ! i don't know why ? but i try another program or try check my internet conection everything is fine

**Comment by Bionus** [comment] 2016-07-02 10:23
What do you mean there's an error? What happens exactly?
If it's a public proxy, could you put the type, host and port here so I can try it out? If it's not, I tried some random proxy online with no issues.

**Comment by falsamr** [comment] 2016-07-06 11:49
~When i grab some pict from the list (in my issue 47 pict from danbooru) the program suddenly not responding and ram usage increase until 2gb ! Then i go to task manager and use "end task" cuz ram usage of the program still increase !
~yes i use public proxy cuz my internet service provider blocking danbooru site
~after that i never downloaded pict more then 20

**Comment by BarryMode** [comment] 2017-08-24 14:17
@falsamr does this still happen in the current version or can this be closed?

**Comment by MasterPetrik** [comment] 2017-08-29 21:27
@BarryMode looks like I'm not the only one who search for issues that can be closed)

for @Bionus about that issue:

- autor is not actve on github over a year(probably will not respond)
- no technical info provided
- no similar issues or reports from another users(maybe it's a singe private problem) 
- maybe already solved in newer versions or autor solved it by other ways

recommend to close this issue. 
And if the issue is still relevant, then autor can ask to reopen it anytime anyway.

**Closed as completed** 2018-04-29 13:18 UTC
Labels: bug
