### ISSUE TITLE
Will not load results, affects all sources, must restart to load a page until it fails to load results again

### ISSUE THREAD

**Issue by pencilbook** [Bionus/imgbrd-grabber#1828] opened 2019-11-14 14:09 UTC
Bug description

There are 0 results unless I restart the program. After a while, it'll fail again and I have to restart again. Rinse and repeat.

Steps to reproduce

    Search for something
    Get results
    Search for something else
    No results
    Restart program
    Search again
    It shows up
    Search for something again
    No results
    repeat

logs: https://pastebin.com/7r1W7tfG

**Comment by pencilbook** [comment] 2019-11-15 18:20
new log https://pastebin.com/KzuE08Em

**Comment by pencilbook** [comment] 2019-11-21 18:29
Bump, needs to be fixed asap

**Comment by Bionus** [comment] 2019-12-05 12:04
Hello

From what I can see, this is a duplicate of your other issue, #1762?
I've been busy for the past few weeks, but it's at the top of my backlog, don't worry 👌

Let's keep the discussion there

**Closed by Bionus** 2019-12-05 12:04 UTC
Labels: bug, duplicate
