### ISSUE TITLE
"Copy to monitors" button

### ISSUE THREAD

**Issue by kifchan** [Bionus/imgbrd-grabber#3123] opened 2024-03-25 17:02 UTC
It would be good to copy the folder path as well

**Comment by ProtagNeptune** [comment] 2024-03-25 17:06
[It's not copying the Folder/Path from the Monitors tab to the Downloads tab when using the Copy to downloads option. #3118](https://github.com/Bionus/imgbrd-grabber/issues/3118)

**Comment by Bionus** [comment] 2024-04-01 10:58
Closing as duplicate of #3118 then

**Closed by Bionus** 2024-04-01 10:58 UTC
Labels: duplicate, suggestion
