### ISSUE TITLE
Nightly Build 2e7cc52d crashes when doing any search

### ISSUE THREAD

**Issue by Gradivus500** [Bionus/imgbrd-grabber#1844] opened 2019-12-10 01:52 UTC
**Steps to reproduce**

Install the latest nightly build
Type something into the search bar
Push "Enter"
Grabber will now crash

Windows 10
Grabber nightly 7.1.1 2e7cc52d

**Comment by Bionus** [comment] 2019-12-10 17:33
I'm afraid I can't reproduce the crash on the nightly fca21e0 (the one from ~1h ago).
Can you try it and tell me if the crash still happens?

And if so, could you share your log too?

**Comment by Gradivus500** [comment] 2019-12-11 06:24
I installed that version and got no crashing error. For good measure I went back and tried the old one as well. It still crashed, but after uninstalling and reinstalling that version it worked. I don't know what the problem was but its safe to say it probably had nothing to do with grabber.

Sorry for the trouble.

**Comment by Bionus** [comment] 2019-12-11 09:04
Well that's good to hear!
I'll close the issue then 👌

**Closed by Bionus** 2019-12-11 09:04 UTC
Labels: cant-reproduce, crash
