### ISSUE TITLE
No results when searching at Rule34 Paheal

### ISSUE THREAD

**Issue by SodaPopin** [Bionus/imgbrd-grabber#2159] opened 2020-10-28 23:09 UTC
It just occurred lately that any searches to Rule34 Paheal will result in nothing. I tried going to the site itself and even change the sources to rule34.xxx in grabber and everything seems to be fine. 
I changed nothing to my settings and even reinstalled the program with no avail.

**Comment by yami-no-tusbas** [comment] 2020-10-30 08:57
Well without the log there is nothing we can do for you good sir.

**Comment by Bionus** [comment] 2020-11-02 18:00
Closing as duplicate of issue #2155.
Also note that rule34.xxx and rule34.paheal are **not** the same websites.

**Closed by Bionus** 2020-11-02 18:00 UTC
Labels: bug, duplicate, source
