### ISSUE TITLE
Grabber don't try to change file extension

### ISSUE THREAD

**Issue by kifat** [Bionus/imgbrd-grabber#1021] opened 2017-08-10 20:47 UTC
**What steps will reproduce the problem?**

Maybe something new on sankaku - when grabber try to download .jpg file (when file is .png on site), he receive 403:forbidden and don't try to download file with .png extension

In browser - .png correctly open, .jpg - not

From log:
[23:38:06.999][Info] Loading image from https://cs.sankakucomplex.com/data/4f/3d/4f3d2aa31e0415398ffae0cd51c8d026.jpg 1
[23:38:07.000][Info] Loading and saving image in D:\Sankaku\oozora itsuki\4f3d2aa31e0415398ffae0cd51c8d026.jpg
[23:38:07.491][Error] Network error for the image: https://cs.sankakucomplex.com/data/4f/3d/4f3d2aa31e0415398ffae0cd51c8d026.jpg: 202 (Error transferring https://cs.sankakucomplex.com/data/4f/3d/4f3d2aa31e0415398ffae0cd51c8d026.jpg - server replied: Forbidden)

**What is the expected behavior? What do you get instead?**

Downloading all extensions instead ignoring not .jpg files

**How often does this problem occur?**

on sankaku only

**What version of the program are you using? On what operating system?**

Grabber_5.4.2 on Windows 7

**Comment by MasterPetrik** [comment] 2017-08-10 21:49
Looks like another duplicate of https://github.com/Bionus/imgbrd-grabber/issues/997
See the issue mentioned above for more info, Sankaku is blocking downloaders.

**Comment by Bionus** [comment] 2017-08-17 20:54
Closing this issue, discussion can be moved to #997.
Indeed, Sankaku is purposedly blocking downloaders.

**Closed by Bionus** 2017-08-17 20:54 UTC
