### ISSUE TITLE
Grabber stops downloading/fills up C: drive

### ISSUE THREAD

**Issue by Pollin2** [Bionus/imgbrd-grabber#1196] opened 2018-01-26 04:33 UTC
### What steps will reproduce the problem?
Attempt to download around 20,000 images in one batch

### What is the expected behavior? What do you get instead?
The expectation would be that downloading images proceeds smoothly. 

Instead, any time I try to download a single 20,000 image batch, Grabber either stops working periodically or eats up 30-40 gigabytes of space on my C: drive despite having the program installed on and downloading to a completely separate partition on a completely separate hard drive. 

### How often does this problem occur? On which sources?
This happens every time I try to download something, I've only tried rule34.xxx as that's the specific site I downloaded Grabber for. 

### What version of the program are you using? On what operating system?
5.5.2 on WIndows 10 64-bit

### Please provide any additional information below
I have no idea if downloading 20,000 images in a single batch is something one is not supposed to do but it certainly seems to break Grabber. Also, the massive amount of space that grabber seems to eat up on my C: drive doesn't come back. I can't find whatever files it's creating that take up so much space. Even restarting my computer doesn't get the space back.

**Comment by Bionus** [comment] 2018-01-27 15:34
Where are those files located?
Are those temporary files? (`C:\Users\%USERNAME%\AppData\Local\Temp`)

Can you upload your log? Maybe there's some information there.

**Comment by Pollin2** [comment] 2018-01-27 22:35
They aren't temp files. My temp folder is 760 kilobytes, while I watched 20 gigabytes disappear from my free space as Grabber ran. Nothing else was running at the time and it wasn't even downloading to the C: partition. I was downloading files to an external hard drive labelled H: While the files did appear in the folder correctly, Grabber also ate up a significant chunk of my C: drive despite not being targeted there. I cannot figure out how it did that or why, or even where on my C: drive the files are that have eaten up this much space. 

As for the log, I believe that the log file from that session disappeared when my PC crashed after grabbed ate up every single byte of free space on my C drive. I apologize for not being more helpful.

**Comment by Bionus** [comment] 2018-01-27 23:15
I don't see why it would do this either. Grabber does indeed save some temporary files, but it should not be that much. With the location of the files it could help understand, however.

Do you not know where those 30~40 GB appear on C:?
Something like [WinDirStat](https://windirstat.net/) could help.

It could also be `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\cache`?

**Comment by Pollin2** [comment] 2018-01-28 01:44
After doing some in-depth research with WinDirStat, I believe I have found the problem. My antivirus program, Webroot, creates a database file for every program that runs on my PC for monitoring purposes. When i ran Grabber, it created a 16.7 gig file. My guess would be that Webroot created an entry for each individual file it downloaded, causing a massive file size. I'll test it again with Webroot turned off and see if that changes things.

**Comment by Pollin2** [comment] 2018-01-28 02:15
That was it. Webroot created a .db file for each time I tried to run a batch, and the larger the batch, the larger the file. So hopefully if I disable Webroot whenever I use Grabber it should work fine.

**Comment by Bionus** [comment] 2018-02-20 16:18
Seems like a pretty big issue on Webroot's side if they don't clear/limit their db files. :confused:
In any case, I'll close this issue since the cause has been found!

**Closed by Bionus** 2018-02-20 16:18 UTC
