### ISSUE TITLE
Thumbnail loading cancelled (empty url)

### ISSUE THREAD

**Issue by Tiffys** [Bionus/imgbrd-grabber#637] opened 2016-10-14 12:21 UTC
### What steps will reproduce the problem?

search for any tag with only source as chan.sankakucomplex..com
### What is the expected behavior? What do you get instead?

Expected thumbnails and program to actually work, program does not work.

[07:05:47.318] Loading results...
[07:05:47.319] Loading page https://chan.sankakucomplex.com/post/index?login=&password_hash=&limit=20&page=2&tags=makya
[07:05:47.813] Receiving page https://chan.sankakucomplex.com/post/index?login=&password_hash=&limit=20&page=2&tags=makya
[07:05:47.813] Thumbnail loading cancelled (empty url).
[07:05:47.814] Thumbnail loading cancelled (empty url).
[07:05:47.814] Thumbnail loading cancelled (empty url).
[07:05:47.814] Thumbnail loading cancelled (empty url).
[07:05:47.814] Thumbnail loading cancelled (empty url).
[07:05:47.814] Thumbnail loading cancelled (empty url).
[07:05:47.815] Thumbnail loading cancelled (empty url).
[07:05:47.815] Thumbnail loading cancelled (empty url).
[07:05:47.815] Thumbnail loading cancelled (empty url).
[07:05:47.815] Thumbnail loading cancelled (empty url).
[07:05:47.815] Thumbnail loading cancelled (empty url).
[07:05:47.815] Thumbnail loading cancelled (empty url).
[07:05:47.816] Thumbnail loading cancelled (empty url).
[07:05:47.816] Thumbnail loading cancelled (empty url).
[07:05:47.816] Thumbnail loading cancelled (empty url).
[07:05:47.816] Thumbnail loading cancelled (empty url).
[07:05:47.816] Thumbnail loading cancelled (empty url).
[07:05:47.816] Thumbnail loading cancelled (empty url).
[07:05:47.817] Thumbnail loading cancelled (empty url).
[07:05:47.817] Thumbnail loading cancelled (empty url).
### What version of the program are you using? On what operating system?

4.8.3 and Windows 8.1 Pro 64-bit
### Please provide any additional information below

Whatever is causing this effectively makes the program non-functional, so it's probably pretty high priority.

**Comment by Tiffys** [comment] 2016-10-14 13:04
I managed to fix this by manually downloading the contents of https://github.com/Bionus/imgbrd-grabber/tree/master/release/sites/Sankaku and putting them in my C:\Users\Tiff\Grabber\sites folder. These are not added by the installer and despite there being icons mentioning there's an update available for various sources I see no way to actually update them.

**Comment by Bionus** [comment] 2016-10-14 14:11
Was this you first install, or did you update from a previous version?

**Comment by Tiffys** [comment] 2016-10-14 14:17
I updated from a previous install. Well, I don't know about updated. I had a previous version installed then downloaded the latest version and installed it. I didn't even see an update option.

**Comment by Bionus** [comment] 2016-10-14 14:44
Yes, that's what I meant.
Seems like the installer didn't overwrite your previous Sankaku files for some reason, I'll check that out.

**Comment by brachna** [comment] 2016-10-27 09:16
Windows 8.1, Grabber v4.8.3.
Same issue with rule34.paheal.net, downloads don't work with it either.
v4.6.0 works fine here as well.

**Comment by Bionus** [comment] 2016-11-05 01:23
That's caused by a bug that makes `rule34.paheal.net` use the RSS source before the Regex source in the latest versions, which doesn't work for paheal.

This will be fixed in the upcoming update (back do regex as default), as well as its RSS source.

**Comment by Bionus** [comment] 2016-11-06 22:12
It's just been uploaded, and I checked that r34 is working on my end.
Feel free to re-open (or open a new issue) in case of problems with it, but I tried browsing, as well as single and batch downloads and it worked.

**Closed by Bionus** 2016-11-06 22:12 UTC

**Comment by brachna** [comment] 2016-11-07 00:16
Thank you!
