### ISSUE TITLE
I can´t login

### ISSUE THREAD

**Issue by NoobIV** [Bionus/imgbrd-grabber#494] opened 2016-03-09 22:00 UTC
![help](https://cloud.githubusercontent.com/assets/15866183/13652008/b874f0c8-e628-11e5-9caf-8d1e182dc94e.png)
sorry for my ignorance , how to login? That error appear in tab credentials too, i need configure something in site/model.xml?

**Comment by Bionus** [comment] 2016-03-10 00:49
The pseudo and password fields on the "Login" tab should not contain your credentials but the name of the fields that should be posted on the form on the URL (which you didn't fill).

For example on Gelbooru, the login page is here:
http://www.gelbooru.com/index.php?page=account&s=login&code=00

By looking at the source code, we can see:
- the name of pseudo field is "user" (`<input type="text" name="user" value="" />`)
- the password field is "pass" (`<input type="password" name="pass" value="" />`)
- the URL is "http://www.gelbooru.com/index.php?page=account&s=login&code=00"
- the method is "POST" (`<form method="post" action="">`)

The cookie is harder to get for non-technical people but it's not really important, it's only used for the testing feature (you didn't set it, that's why you get the "unable to test" message). For Gelbooru it's "user_id", but it's very often "PHPSESSID".

Your actual username and password should be set in the "Credentials" tab. If you can't get it to work, I'll do my best to help if you tell me which source you're trying to add.

**Comment by NoobIV** [comment] 2016-03-11 01:30
![help2](https://cloud.githubusercontent.com/assets/15866183/13690495/a81477fc-e70f-11e5-84a1-c50d9cec63dc.png)
sorry, i forget post the source D:

**Comment by Bionus** [comment] 2016-03-11 02:01
Sankaku is already configured by default. You have to re-check "through url" and put your credentials in the right tab. It can't be tested by design, though (you'll get a "unable to test" message if you try). But since you're logging in I guess it's to bypass some limitation for guest accounts, so you can just check if they are properly removed after putting your credentials (page limit maybe?).

**Comment by NoobIV** [comment] 2016-03-11 02:21
![help3](https://cloud.githubusercontent.com/assets/15866183/13691219/cc3bd124-e715-11e5-9a2c-9f4bc3b78375.png)
i trying download this tag and can see 11877 but just download 1000 images or below
I need to do something with this ?
![help5](https://cloud.githubusercontent.com/assets/15866183/13691328/a6866d4e-e716-11e5-8ba4-2cf0c495fd8f.png)
![help6](https://cloud.githubusercontent.com/assets/15866183/13691331/ac592446-e716-11e5-899e-0db86a6333a3.png)
Sorry for my bad english

**Comment by NoobIV** [comment] 2016-03-11 02:58
i think this now fixed
![thinkfix](https://cloud.githubusercontent.com/assets/15866183/13691954/d69ffc2a-e71b-11e5-88fc-d65940055aaf.png)

reached 101 pages

**Comment by Bionus** [comment] 2016-03-12 13:15
So you got it to work eventually? :smile:

From this screenshot:
![](https://cloud.githubusercontent.com/assets/15866183/13691331/ac592446-e716-11e5-899e-0db86a6333a3.png)

It looked like you didn't hash your password at that time, but seems like it's good now so I'm closing this issue.

**Closed by Bionus** 2016-03-12 13:15 UTC

**Comment by Tiffys** [comment] 2016-10-14 12:27
I have this same problem trying to log in for Sankaku with "Unable to test" but I don't have a "Hash a password" button. So I don't see any way to resolve it.
