### ISSUE TITLE
Rule 34 paheal shows no result, but I can still see the tags on the side. It's not an IP ban- I already tried multiple VPN locations.

### ISSUE THREAD

**Issue by DS2Gey** [Bionus/imgbrd-grabber#2165] opened 2020-11-01 13:50 UTC
I can't search anything on R34 Paheal, there aren't any results shown. I can open the site on chrome fine, grabber just can't fetch the pics.

Log Here:

[22:45:52.114][Warning] Javascript model not found for Sankaku 
[22:45:52.161][Info] Temp directory purged of 0/0 files (0 failed) 
[22:45:52.482][Info] New session started.
[22:45:52.483][Info] Software version: 7.3.2.
[22:45:52.483][Info] Software CPU architecture: x64.
[22:45:52.483][Info] Computer CPU architecture: x86_64.
[22:45:52.483][Info] Qt CPU architecture: x86_64.
[22:45:52.483][Info] Computer platform: Windows 10 (10.0).
[22:45:52.483][Info] Path: C:/Program Files/Grabber
[22:45:52.484][Info] Loading preferences from C:/Users/chesw/AppData/Local/Bionus/Grabber/settings.ini
[22:45:52.485][Info] Temporary path: C:/Users/chesw/AppData/Local/Temp\Grabber
[22:45:52.491][Info] SSL libraries: OpenSSL 1.1.1d 10 Sep 2019
[22:45:52.501][Info] Setting language to 'English' (C:\Program Files\Grabber\languages\English.qm)...
[22:45:52.502][Info] 20 sources found: anime-pictures.net (Anime pictures), api.twitter.com (Twitter), behoimi.org (Danbooru), danbooru.donmai.us (Danbooru (2.0)), derpibooru.org (Philomena), e-hentai.org (E-Hentai), e621.net (E621), exhentai.org (E-Hentai), gelbooru.com (Gelbooru (0.2)), hijiribe.donmai.us (Danbooru (2.0)), konachan.com (Moebooru), nhentai.net (NHentai), rule34.paheal.net (Shimmie), rule34.xxx (Gelbooru (0.2)), safebooru.org (Gelbooru (0.2)), sonohara.donmai.us (Danbooru (2.0)), tentaclerape.net (Shimmie), www.pixiv.net (Pixiv), www.zerochan.net (Zerochan), yande.re (Moebooru)
[22:45:52.546][Info] Updating checkboxes.
[22:45:52.548][Info] [rule34.paheal.net] Logging in...
[22:45:53.495][Info] [rule34.paheal.net] Login finished: failure.
[22:45:53.499][Info] Updating checkboxes.
[22:45:53.508][Info] Monitoring starting
[22:45:53.512][Info] Monitoring tick
[22:45:53.513][Info] Next monitoring will be in 84024 seconds
[22:45:56.267][Info] Loading results...
[22:45:56.268][Info] [rule34.paheal.net][Html] Loading page http://rule34.paheal.net/post/list/1
[22:45:56.624][Info] [rule34.paheal.net][Html] Receiving page http://rule34.paheal.net/post/list/1
[22:45:56.626][Info] [rule34.paheal.net][Html] Parsed page http://rule34.paheal.net/post/list/1: 0 images (0), 10 tags (10), -1 total (10000), 500 pages (500)

**Comment by Bionus** [comment] 2020-11-02 17:57
Closing as duplicate of issue #2155.

**Closed by Bionus** 2020-11-02 17:57 UTC
Labels: bug, duplicate, source
