### ISSUE TITLE
Bug with loading problem images

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#881] opened 2017-04-10 01:07 UTC
Sometimes some images becames **problem images**, it means, that they sucessfully loads from site with all related metadata, their thumbnails shows in results grid as any other normal images. In preview they show correct tag list, details window info and preview window caption, but without image. And without any error messages or bad log strings.

### What steps will reproduce the problem?
1. search  for some request
2. some of results images are problem images, but their thumbnails loaded fine and looks like normal thumbnails. 
3. you opening one of normal images in preview window. All goes normal.
4. you are going to the next (problem) image, and see this:
after pressing ">" button tags from taglist changes to tags for next (problem) image, Window caption also changes to the caption of next (problem) image, BUT image in preview isn't changes.
5. So now you see, that tags and window label doesn't related to visible image. Moreover, now it's hard to detemine, where in the results you are standing, because for example in next and previous images both problem images, then going ">" and "<" will cause confusion for user.
6. If you go back(via going to previous\next images) to any normal image in preview, then window label, taglist and image will be show correct, but if you will go to the problem image again, the bug will appear again, so if you have some problem images in your results, then this bug is 100% repeatable

I don't see any strange behavior in log file.
Restart of the Grabber solves the problem, and all (problem)images loads correct after that. So I guess problem Images DON'T have problems on server side(according to log).

### What is the expected behavior? What do you get instead?
I'm expecting to see at least upscaled thumbnail image from results grid, if now original image isn't aviable for some reason. But showing previous correct image instead confuses me a lot.

### How often does this problem occur?
if you have some problem images in your results, then this bug is 100% repeatable

### What version of the program are you using? On what operating system?
5.2.4, win7x64 as always

### Please provide any additional information below
Here is the video of the process and part of log file:
https://drive.google.com/open?id=0B3SK4Pf9wsnmYWxyNEJsOW5Hb00

**Comment by MasterPetrik** [comment] 2017-04-10 01:55
Looks like This bug caused by too much faster scrolling images in preview window(via mouse for example)
Sooner or later you can get this error message:

![image](https://cloud.githubusercontent.com/assets/22294259/24843142/895fffea-1da8-11e7-91e7-292c72685c3d.png)

Looks like images became problem images after appearing this error at least at one time.
After closing error message, some of images becames problem images,(much more then one image!) but new error messages are not appears.

**Comment by MasterPetrik** [comment] 2017-04-10 09:51
I guess this errors appears because of too many requests to the server at once(Caused by too much faster scrolling images in preview window). So server just refuses to process new requests and this causes problem images

![image](https://cloud.githubusercontent.com/assets/22294259/24855694/10b0c1ea-1deb-11e7-9e38-d4e5ec16e443.png)

**Comment by MasterPetrik** [comment] 2017-05-24 00:15
still occures in 5.3.2

> This bug also caused by too much faster scrolling images in preview window(via mouse for example)

looks like there are exist other causes of this bug. My current one definitely wasn's caused by scrolling.

**Comment by Bionus** [comment] 2017-05-24 00:29
Do you always get the error message before this start to happen?

After this problem start to happen, does it only apply to new images that you try to open, or also "older" (opened before the problem started) ones?

**Comment by MasterPetrik** [comment] 2017-05-24 00:42
> Do you always get the error message before this start to happen?

No. Looks like there are not one way to get this bug or.. it's two separated bugs

>  After this problem start to happen, does it only apply to new images that you try to open, or also "older" (opened before the problem started) ones?

Yes it happens even with already seen images, for example, image from the screenshot:
![2017-05-24_031532 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26382041/d6bb9dac-4031-11e7-88ae-98fb7280d6b4.png)
it has been opened in preview in this search session many times, but since some moment it starts open in preview window with no image, and some neighbors images too(often 2-3).
I even start think about connection problems... but! I saved THIS image via right click menu from grid and... it has been sucsessfully saved! And in preview window "save" button changed to "delete" but still no image in image area... very strange.
So THIS problem looks like not connected to connection problems, more like displaying problems.

**Comment by MasterPetrik** [comment] 2017-05-24 00:57
> It seem to keed "old" images ok. But does all new images afterwards have this problem? Or only some?

Not really understand you. How this bug visually looks like: in new search results session or in already seen search results session some images sometimes(this bug appears randomly but not very often) becames "problem images", often it happens not with one, but with groups of images(1-5 images in a row for example) after bug first time appears no other images becames "problem images", only these. All other images works normal in preview exept "problem images" which shows blank space instead of image in preview.

> Which source does this usually occur on? All?

Did not noticed sources, sorry.

**Comment by Bionus** [comment] 2017-05-25 14:14
I pushed a fix but since I could not reproduce in the first place, I can't guarantee it will fix the issue.

Note that there may still be blank images (if the server rejects your request because of too many requests, for example): the difference is that loading the image again should work.

> No. Looks like there are not one way to get this bug or.. it's two separated bugs

There may indeed be two issues at work here. Note that my fix only applies to when the popup error appears. But maybe they're related and it will fix both? 🙏

**Comment by MasterPetrik** [comment] 2017-05-25 14:44
> I pushed a fix but since I could not reproduce in the first place, I can't guarantee it will fix the issue.

Good to hear!~  
btw, you can give me current develop .exe file or installer so I can test it on my side

**Comment by MasterPetrik** [comment] 2017-05-25 15:01
btw may I post some suggestion mentioned in closed issies as sepatated ones? Will it be OK?

**Comment by Bionus** [comment] 2017-05-25 15:13
>  btw, you can give me current develop .exe file or installer so I can test all changes on my side before release
> I will be glad to do that

5.3.3 was just released. 😛 

> btw may I post some suggestion mentioned in closed issies as sepatated ones? Will it be OK?

It's even better. I'd rather have 3 issues with 1 suggestion than 1 issue with 3 suggestions. :smile:
Especially if said issue is already closed.

**Comment by MasterPetrik** [comment] 2017-05-26 01:31
What can I say? Well done! Good job! 
Now since 5.3.3 all images in preview loads correct and in caused a problem reloads instantly, so there are no more empty spaced "problem images" anymore. Thanks a lot!

Only one little problem thing remained: 299 errors after very fast scrolling. Now it's harmless, because of images reloads, but these errors shows in a big amount in this situation. So I think, maybe you can somehow do an Exception Handling for this case? And then last preview window images switching problem will be completely solved.
![image](https://cloud.githubusercontent.com/assets/22294259/26476942/bd44f25c-41ca-11e7-9721-8ce3f8bf5f03.png)

**Comment by brodycas3** [comment] 2017-05-26 02:27
that looks beautiful

**Comment by Bionus** [comment] 2017-05-26 10:25
> Only one little problem thing remained: 299 errors after very fast scrolling. Now it's harmless, because of images reloads, but these errors shows in a big amount in this situation. So I think, maybe you can somehow do an Exception Handling for this case? And then last preview window images switching problem will be completely solved.

You mean you don't want to show this popup for these cases?

**Comment by MasterPetrik** [comment] 2017-05-26 13:36
> You mean you don't want to show this popup for these cases?

Bunch of 299 error messages? Yes. It's just disturbs users without a good reason now.
If images autoreloads now, then no need to see these errors at all.
Wat's the point of showing user an error, that already fixed in this time? 
Error messages - nessesery info when programm cant fix problem by itself and need user help to fix it, so it shows info about problem, and with this info user may fix it manually or report to developer. But if programm fixes errors automaticaly, then no need any actions from user, so error messages in THIS case are pointless. 

> How would the user be informed an error occurred, then?

Isn't errors writes in log? It's technical information, so user don't need to see it without a good reason.
Writing in log will be enough.
But if you have to inform users about this error anyway, then I can suggest you a fine solution for that:
![2017-05-26_160459 win7 ma st ercore](https://cloud.githubusercontent.com/assets/22294259/26496228/50b061ac-422f-11e7-8ee4-84e9fed6e4f2.png)
instead of showing images-related errors in Preview window you can make an Exception Handling, and show little warning sign at the corder of the window instead, so it will not disturb user, but show him that there is some info for him, so If user is OK with this error, he can ignore it and watch images, but if this error caused an error in image(image is not downloaded\blank space\still thumbnail instead of image) then user obviously notice it and notise appearing of warning sign too, so when he click on that sign with Left mouse button it shows error, and if he click on that sign with right mouse button, it will dissapears. 
When sign is already shown but new error message appears then you can blink watning sign in this moment to attract user attention.
If you like it idea, I can make a separate issue with that. 
But you can just NOT SHOW 299 errors anyway.

**Closed** 2017-07-09 15:07 UTC
Labels: bug
