### ISSUE TITLE
Latest nightly build missing files with install

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1487] opened 2018-10-28 19:58 UTC
**Steps to reproduce**

Install the latest nightly version
You get a message that qscintilla2_q5.dll can't be found by which the program can't be opened

**Screenshots**

![https://i.imgur.com/flwY2RE.png](https://i.imgur.com/flwY2RE.png)

**System information**

Windows 10 with the latest nightly build

**Comment by Bionus** [comment] 2018-10-29 09:08
Sorry, seems like it was caused by #1479, given nightly versions didn't even use QScintilla before.
I just pushed a fix, and the latest nightly should be fixed now. 👌

**Closed** 2019-03-31 14:14 UTC
Labels: build, reproduced
