### ISSUE TITLE
tbib.org no longer works

### ISSUE THREAD

**Issue by LMTMFA** [Bionus/imgbrd-grabber#1789] opened 2019-10-01 14:39 UTC
tbib.org no longer produces results in the searchbox, nor do any items download from previous downloadlists.

When following the link that shows in the log in a browser (https://tbib.org/index.php?page=dapi&s=post&q=index&limit=58&pid=0&tags=test), the site returns zero results, while searching for a term on the site itself will return results just fine.

Maybe they changed their request method?

**Comment by LMTMFA** [comment] 2019-10-01 14:40
aaand apparently it was just a bug on their end, seems to work again now.. D'oh.

**Comment by Bionus** [comment] 2019-10-20 13:18
So this issue seem unrelated to tbib then?

Because from what I see the source works well, even though I can reproduce the issue of it stopping working after a while. But according to issue #1792 it seems to happen across multiple sources?

**Comment by Bionus** [comment] 2019-12-10 17:49
Since it seems to indeed be the same as #1762, I'll close the issue as it's unrelated to tbib. 👌

**Closed by Bionus** 2019-12-10 17:49 UTC
