### ISSUE TITLE
(all get) is crash

### ISSUE THREAD

**Issue by Huzam422** [Bionus/imgbrd-grabber#2613] opened 2022-03-08 17:54 UTC
I will one just choose rule34 download normal.  get all problem booru any download and crashed?

**Comment by Yukkun** [comment] 2022-03-25 19:54
Try 32-bit version. 64-bit version seems to crash

**Comment by Bionus** [comment] 2022-03-31 17:30
Closing as duplicate of #2579
Also please provide your log next time as it might be helpful. Very likely caused by enabling Pixiv without logging in.

**Closed by Bionus** 2022-03-31 17:30 UTC
Labels: duplicate, crash
