### ISSUE TITLE
Some websites don't seem to load images with windows 10

### ISSUE THREAD

**Issue by the612toon** [Bionus/imgbrd-grabber#1104] opened 2017-10-02 20:27 UTC
### What steps will reproduce the problem?
Download Grabber
Type in anything on grabber
Nothing appears

### What is the expected behavior? What do you get instead?
Images appear on my windows 8... but not my windows 10

### How often does this problem occur? On which sources?
All the time... on multiple sources.

### What version of the program are you using? On what operating system?
5.5.1, windows 10

**Comment by Bionus** [comment] 2017-10-09 14:35
Do you have VC redist installed? The 2015 version should be automatically installed by the program, but I've heard of users saying they also needed to install the VC redist 2013.

> on multiple sources

Do you have a list of which sources work/which sources don't? Could it be that the only working ones are the non-HTTPS sources?

**Comment by Bionus** [comment] 2018-05-19 08:25
Closing as duplicate of #767.

**Closed by Bionus** 2018-05-19 08:25 UTC
