### ISSUE TITLE
"preview" images don't load the full image size on Sankaku Complex

### ISSUE THREAD

**Issue by Rigabriezi** [Bionus/imgbrd-grabber#1137] opened 2017-11-04 22:20 UTC
### What steps will reproduce the problem?
2.search something from chan.sankakucomplex.com
2.click on one of the images
3.watch as it loads the image in full resolution but then downscale it to 144x240px image

### What is the expected behavior? What do you get instead?
To load a full or near full sized image, Instead I got a 144x240px image

### How often does this problem occur? On which sources?
Everytime.
Only on chan.sankakucomplex.com

### What version of the program are you using? On what operating system?
5.5.2 
happened on 5.5.1 as well

### Please provide any additional information below
Issue happens regardless if you have proper login information added to the Sources > Credientals page
Will "load the image proper, just blurred because it's loading, but will then load the image in144x240px 
Clicking on the image does not resolve the problem.

Apologies if this has been addressed before. I don't see it. 
Here is an screenshot of the image loading
![complex2](https://user-images.githubusercontent.com/33381922/32409949-aa6a63e6-c18c-11e7-827d-c85c12cb2629.png)
Here is a screenshot of the image fully loaded, it was downscaled massively 
![complex](https://user-images.githubusercontent.com/33381922/32409956-c800c792-c18c-11e7-9f38-c6139d4f8cc1.png)

**Comment by Bionus** [comment] 2017-11-04 22:28
1. Sankaku's developer does not want downloaders to work, and even explicitly asked us to drop the support for it in Grabber, that's why Sankaku doesn't work very well.
2. You can always try to use the [Nightly version](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly) and the latest [model.xml](https://github.com/Bionus/imgbrd-grabber/blob/develop/release/sites/Sankaku/model.xml) file for Sankaku, as it seems to work with it:
![image](https://user-images.githubusercontent.com/882719/32410017-de1f14ea-c1b7-11e7-980b-783372ca1e79.png)

**Comment by MasterPetrik** [comment] 2017-11-05 02:04
also, duplicate of https://github.com/Bionus/imgbrd-grabber/issues/1128 issue

**Comment by Bionus** [comment] 2017-11-05 02:08
Indeed, I'll close this one then, followup in 1128.

**Closed by Bionus** 2017-11-05 02:08 UTC
Labels: source
