### ISSUE TITLE
Searching Gelbooru Always Returns No Results

### ISSUE THREAD

**Issue by Rivalz906** [Bionus/imgbrd-grabber#1186] opened 2018-01-15 03:11 UTC
Searching for anything in Gelbooru returns no results, yet all the other sites are working.

I am on Windows 8 and am using Grabber version 5.5.2.

**Comment by warbear** [comment] 2018-01-15 15:19
Same, using Nightly 5.5.2 421785e4

**Comment by Bionus** [comment] 2018-01-20 14:02
Duplicate of #1184

**Closed by Bionus** 2018-01-20 14:02 UTC
Labels: duplicate, source
