### ISSUE TITLE
Videos dont play

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#903] opened 2017-05-04 00:12 UTC
### What steps will reproduce the problem?

click the play button

### What is the expected behavior? What do you get instead?

Play video in Grabber

### How often does this problem occur?

Every time

### What version of the program are you using? On what operating system?

The latest version as of 5/3/17

### Please provide any additional information below

The only way I can watch a video is if I double click it and play it in an external video player.

**Comment by Bionus** [comment] 2017-05-04 00:36
That's by design. There's no video player in Grabber. There used to be one which added a lot of boilerplate, around 25mo of dlls, made the program leak like crazy and didn't support many video types.

**Comment by brodycas3** [comment] 2017-05-04 01:10
ah, You should make it open it in the external player with a single click
then.

**Comment by brodycas3** [comment] 2017-05-04 01:11
if not just go ahead and close this

**Comment by Bionus** [comment] 2017-05-04 21:12
I don't really want to change the behaviour between videos and images, which is "open in default viewer by double-clicking", and I don't really like the idea of opening VLC by a simple click. I'll close the issue then :smile:

**Closed by Bionus** 2017-05-04 21:12 UTC
