### ISSUE TITLE
THE GELBOORU SITE DOES NOT DOWNLOAD EVERYTHING

### ISSUE THREAD

**Issue by zombieotaku** [Bionus/imgbrd-grabber#2779] opened 2022-08-03 20:53 UTC
**Bug description**

on the gelbooru website from the grabber program when using the get everything option only downloads as a maximum of 100 images, it no longer downloads more of that although more images are missing, the error is only from gelbooru since in danbooru it works correctly

**Steps to reproduce**

**Expected behavior**

I expected to download more than 100 images from gelbooru since in danbooru if you can, in the past you could also download from gelbooru the download of more than 100 images the error is recent.
![Captura de pantalla 2022-08-03 153910](https://user-images.githubusercontent.com/110567610/182708445-fc302945-4fef-4262-a1f4-76e6aa21f2b9.png)

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occurred during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [e.g. 7.9.1]

**Additional context**

As I mentioned the limit of images from the source of gelbooru is only 100 images, but from other sources that limit does not exist, before the source of gelbooru did not have that problem and you could easily download 300 images for example, now they are always 100 even if you use the option to get everything does not work correctly

**Comment by AkatsukiiDesu** [comment] 2022-08-03 23:45
This issue has been resolved in the nightly build of Grabber which can be downloaded at https://github.com/Bionus/imgbrd-grabber/releases/nightly

**Comment by yami-no-tusbas** [comment] 2022-08-06 11:56
Setting the "image per page" value to 100 fixe the issue for the non nightly, but you have to update it manually for each groups.

**Comment by Bionus** [comment] 2022-08-24 18:06
Closing as duplicate of #2765.

**Closed by Bionus** 2022-08-24 18:06 UTC
Labels: duplicate, bug, source, reproduced
