### ISSUE TITLE
"Get this page" and "Get all" doesn't grab the correct creation dates on rule 34 paheal

### ISSUE THREAD

**Issue by the612toon** [Bionus/imgbrd-grabber#834] opened 2017-03-06 06:13 UTC
### What is the expected behavior? What do you get instead?
I want grabber to give me the correct created date but instead it always gives me Wednesday, December 31, 1969, 5:59:59 PM for the images I bulk download off of paheal rule 34. When I download the images individually this doesn't happen.

### What version of the program are you using? On what operating system?
Windows 8, Grabber 5.2.2

**Comment by Bionus** [comment] 2017-03-09 19:48
This issue looks a lot like issue #797, which was fixed in 5.2.1.

I just tried and could not reproduce in 5.2.2, using the `%date:format=yyyy-MM-dd% %md5%.%ext%` filename. Both normal and batch downloads contained the date. Did you do any other manipulation?

**Comment by Yarott** [comment] 2017-03-22 19:03
I have to say that it also happens to me. I find that simply raising the number on the Images Limit fixes it a bit, but that still makes the loading a bit of a pain.

**Closed** 2017-03-27 17:55 UTC
Labels: bug, source
