### ISSUE TITLE
Derpibooru wont work anymore :c

### ISSUE THREAD

**Issue by Kamero4K** [Bionus/imgbrd-grabber#1979] opened 2020-05-27 13:08 UTC
Since.. Weeks..
When you leave the searchbar blank you get the latest 25 uploaded pics. Going to second or third page wont work.
When you search for something.. you get no results. Whatever you searched.
How to fix it?

**Comment by Bionus** [comment] 2020-06-01 21:45
Could it be a duplicate of #1924?
Updating the [model file](https://github.com/Bionus/imgbrd-grabber/blob/develop/src/sites/Philomena/model.ts) or straight using the nightly release should fix this I believe.

**Closed** 2020-06-01 21:46 UTC
Labels: bug, duplicate, source

**Comment by Illern69** [comment] 2020-06-02 09:38
I was having the same issue as _Kamero4K_. I didn't know where to locate the _model file_ in my installation directory, so I opted for the Nightly installation instead. Derpibooru now works fine for me.

For reference, I was running version 6.xx until recently, but my problem remained even after updating to the stable v7.21. Now it works like a charm, using the current v7.21 Nightly build.
