### ISSUE TITLE
Video previews: centering and new play button skin needed

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#777] opened 2017-02-09 21:50 UTC
current video preview can be greatly improved. 
let's take a look...
# Current preview
![2017-02-07_171556 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22803321/7e9799a8-ef25-11e6-9f40-051a1e60cb4c.png)

what's wrong with it?

## 2. Play button is not contrast with background 
![2017-02-10_002106 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22803647/dc20f8a2-ef26-11e6-9050-e902e8637687.png)
## 3. I guess, thumbmnails are needed to upscale to 120%-150% from current size

I guess that it will be much better if you align thumbnail to the center and change play button to something more contrast and will be better to find colored play button for easy finding it on preview page.

# How it can be
![2017-02-07_171556 win7 master89core](https://cloud.githubusercontent.com/assets/22294259/22803907/e09de38a-ef27-11e6-90e1-5681951cc80b.jpg)
I even did a play button png, fell free to use it if you like:
![playg](https://cloud.githubusercontent.com/assets/22294259/22804607/d9d913f0-ef2a-11e6-8ab6-fc693242f9a2.png)

**Comment by barryanders** [comment] 2017-02-09 22:14
@MasterPetrik I gotta give you props for submitting so many ideas to development.

**Comment by Bionus** [comment] 2017-02-10 18:18
> Thumbnail aligned to the left

I thought you were against centering images? As you said is another issue, most imageboards use left-alignment. If you change the alignment depending on the type of image you open, wouldn't it be strange when using the arrow keys and having images sometimes on the left and sometimes centered?

> Play button is not contrast with background

Indeed, I just took the first one I found on google images, yours however is amazing! Kudos, I'll definitely use it instead :smile:

> I guess, thumbmnails are needed to upscale to 120%-150% from current size

It's currently a *2 to the thumbnail size. I guess it could indeed be increased to a *3. Here's the result:

![image](https://cloud.githubusercontent.com/assets/882719/22838299/d739d1bc-efc4-11e6-95a1-308215b5d660.png)

Another option is to scale it to the size of the video. The problem is that it causes the thumbnail to be sometimes upscaled too much:

![image](https://cloud.githubusercontent.com/assets/882719/22838473/942985ec-efc5-11e6-9eea-6b0842e9f4ec.png)

> I gotta give you props for submitting so many ideas to development.

Indeed, I myself don't have lots of ideas currently for the project (except for mainly technical stuff), so suggestions really help improving the program!

**Comment by MasterPetrik** [comment] 2017-02-10 19:09
> I thought you were against centering images? As you said is another issue, most imageboards use left-alignment. If you change the alignment depending on the type of image you open, wouldn't it be strange when using the arrow keys and having images sometimes on the left and sometimes centered?

Yes. I made two separate issues because I think that preview window behavior shouldn't be the same for images and for videos. Image preview is a real preview mode like in the almost all image viewers, but video preview mode is just a shortcut with thumbnail. So you don't expect that user will look at the video preview as it look on image, you expect that user will click on thumbnail and play video, so preview window purpose for images and for video a bit different. 

I based my suggestion on this ideas:
* **user dont want to see so much thumbnails in image preview mode**, because  they originals loads really fast, but in video preview mode user prefer to see thumbnail instead of nothing, and a loading is much longer
* **user want to differ images and video**
That's why I suggest fixed preview size, because you need to clearly understand that it's not an image thumbnail, but a video thumbnail. Now about size. I dont think that size more that 500x500 make sence, because almost all videos in fact has not a very high resolution(almost all videos from anime are from 480x280 to 1280x768), and dont forget that video thumbnail is just a shortcut so it should have constant size for all videos. look at windows explorer:
![image](https://cloud.githubusercontent.com/assets/22294259/22839709/ad8848e6-efdb-11e6-83fc-c37b89a14587.png)
all thumbnails have constant size regardless of real video size, for video I guess will be clever to set not very big preview image(approximately somewhere from 300x300 to 500x500) but its just a my opinion.
![e09de38a-ef27-11e6-90e1-5681951cc80b](https://cloud.githubusercontent.com/assets/22294259/22839525/d9255ab2-efda-11e6-8955-5360fe2c2a2f.jpg)
* **user want to press play button in predictable place, regardless of size of window.**
That's why I suggest align video thumbnail to center, it make sence because it's more easily for user to press in the middle of window.

P.S.
sorry for all that wall of text -___-

**Comment by MasterPetrik** [comment] 2017-02-10 19:27
> > I gotta give you props for submitting so many ideas to development.
> 
> Indeed, I myself don't have lots of ideas currently for the project (except for mainly technical stuff), so suggestions really help improving the program!

I dont fully understand what "props for submitting" do you guys mean,(my github expiriense is not so big) but i will be glad to help any way I can.
And yes, I have some kind of list with suggestions) but i planing to post it here gradually. (dont want to cause Bionus overwork)
And I someday pull myself together and will do Russian translation.

**Comment by Bionus** [comment] 2017-02-10 20:04
> I dont fully understand what "props for submitting" do you guys mean,(my github expiriense is not so big) but i will be glad to help any way I can.

It means "good job", or "respect" (cf [urban dictionary](https://www.urbandictionary.com/define.php?term=props)).

> And yes, I have some kind of list with suggestions) but i planing to post it here gradually. (dont want to cause Bionus overwork)

If you already have a list, it'd be better to directly make some issues if you want them done. :smile:

Since I don't have much free time, I usually only start working on the project after a few issues are open, and do them all in one go. This way I can save time. If you check previous releases, most issues are fixed in groups, usually on the weekend, when I have enough time to do a lot of them. Especially small issues ^^

>  And I someday pull myself together and will do Russian translation. meh...

No pressure. If you don't want to open the language files and setup everything, you can also directly send the translations in some issue.

**Comment by Bionus** [comment] 2017-02-10 20:16
> user want to differ images and video

Indeed, but if you differ too much won't you confuse him? If you use next/previous a lot, in the same way you don't want small thumbnails being replaced very fast by the big version, I'm not sure you want the image to move from the left side to the center every now and then.

> That's why I suggest fixed preview size, because you need to clearly understand that it's not an image thumbnail, but a video thumbnail.

Isn't the big red play button enough for this? Small movies stuff can also be added around it, just like in your windows image, but that seems a little bit kitsch:

![](https://www.ise.gov/sites/default/files/featured/Video-Icon-crop.png)

> Now about size. I dont think that size more that 500x500 make sence, because almost all videos in fact has not a very high resolution(almost all videos from anime are from 480x280 to 1280x768), and dont forget that video thumbnail is just a shortcut so it should have constant size for all videos.

Currently, the calculation is: `min(thumbnail size * 3, video size)`.

So if a video is 1080p, the thumbnail will be displayed in a 450x450 box (150x150 * 3), so 450x253. And if it's a small video, let's say 280x160, the thumbnail will be exactly 280x160: it doesn't make sense to have it bigger than the actual video.

> user want to press play button in predictable place, regardless of size of window.

The whole right area of the window can be double-clicked to open the file, even the empty space. If the user is used to have the images appear on the left side of the window, having it on the center would not be very predictable for him?

**Comment by MasterPetrik** [comment] 2017-02-10 20:58
> Indeed, but if you differ too much won't you confuse him? If you use next/previous a lot, in the same way you don't want small thumbnails being replaced very fast by the big version, I'm not sure you want the image to move from the left side to the center every now and then.

Take a look from another point of view. When user quickly changing image sin preview window he may not  notice the video among them if it will be aligned to the left too. and no visual elements will help differ images from videos when fast scrolling, exept different alignment. And when user will quick scrolling images in preview and one image blinks and change its alignment, he will surely know that that was video. Because its very native for user to align images to the left(boorus, chans, forums) and align videos to center(almost all video hostings), so I guess it will not be a problem.

> Isn't the big red play button enough for this? Small movies stuff can also be added around it, just like in your windows image, but that seems a little bit kitsch:

I guess you are right and button and center alignment will be enough. I dont fully understood the "kitsch" part but replace the tiny thumbnails with the some kind of video emblem is the very bad idea, because... hmm... its already preview window, and user expects any preview image from video instead of noninformational icon.

> Currently, the calculation is: min(thumbnail size * 3, video size).
> So if a video is 1080p, the thumbnail will be displayed in a 450x450 box (150x150 * 3), so 450x253. 

sounds very good exept one thing. The the calculation formula doesn't considers situation where same video from different boorus will have different thumbnail resolution in preview because of different booru thumbnail resolutions on these boorus. for example in one booru thumbnail is 120x120 and in another is 180x180, and they will cause different video preview image for same video.

So I guess thumbnail preview size limit should not depend of booru thumbnail size and be 500x500 or 450x450 or etc. but constant.

> And if it's a small video, let's say 280x160, the thumbnail will be exactly 280x160: it doesn't make sense to have it bigger than the actual video.
absolutely agree.

**Comment by MasterPetrik** [comment] 2017-02-10 21:21
> > And yes, I have some kind of list with suggestions) but i planing to post it here gradually. (dont want to cause Bionus overwork)
> 
> If you already have a list, it'd be better to directly make some issues if you want them done. :smile:
> 

I sending bugreports immidiatly, as for suggestions, all remaining issies need a proper description and images. I do not hurry. All will be posted someday)

> Since I don't have much free time, I usually only start working on the project after a few issues are open, and do them all in one go. This way I can save time. If you check previous releases, most issues are fixed in groups, usually on the weekend, when I have enough time to do a lot of them. Especially small issues ^^

Heh, I already noticed that.
To be honest, I usually start working on describing issues, when I see changes on Gragger network graph, it's a very good motivation)

**Closed** 2017-02-25 15:10 UTC
Labels: enhancement
