### ISSUE TITLE
Javascript filename missing variable references.

### ISSUE THREAD

**Issue by fawkinguy** [Bionus/imgbrd-grabber#1108] opened 2017-10-07 01:58 UTC
### What steps will reproduce the problem?

Use copyright or character tags. (possibly others).

### What is the expected behavior? What do you get instead?

a string of the copyrights or characters.

### How often does this problem occur? On which sources?

Always, latest release.

### What version of the program are you using? On what operating system?

5.5.1
Windows 10

### Please provide any additional information below

Javascript I am using:

search_1 + '/' + 
copyright+'/' + 
character + '/' + 
score + '_' + 
md5.slice(0,4) + '_' +
id + '_' +  '.' + 
ext

Javascript I am attempting to use (end goal):
search_1 + '/' + (
  copyright.split('+').contains(search_1) ? 
  copyright.split('+').filter(function(x){
    return x!== search_1 && x.indexOf(search_1) >= 0 ;
  }):
 'misc/'
) + 
character + '/' + 
score + '_' + 
md5.slice(0,4) + '_' +
id + '_' +  '.' + 

ext

**Comment by Bionus** [comment] 2017-10-08 14:39
Indeed, I could reproduce the missing variables in Javascript.

I just pushed a fix to add them back. And I also saw you doing `copyright.split('+')` so I added a `copyrights` variable for an already-split array. It should land in nightly soon, or you can wait for the 5.5.2 release. :smile:

**Comment by fawkinguy** [comment] 2017-10-14 04:20
I'll have to wait as I can't seem to get it to build.. -.-

**Comment by Bionus** [comment] 2017-10-14 10:22
> I'll have to wait as I can't seem to get it to build.. -.-

If you're on Windows, the nightly built successfully and is available in the downloads automatically.
On Linux, I just built it 1h ago, so I don't think the build is broken (both CI are green after all).

> Also thanks for the pre-split array. does it use whatever delimiter is specified in the settings?

For the moment, because of some old bad design issues, I'd say yes. But in the future it should simply be the "unmerged" array instead of "merged then split again", therefore the delimiter won't be relevant at that time.

**Closed** 2017-10-29 16:23 UTC
Labels: bug
