### ISSUE TITLE
rule34hentai.net DOWN?

### ISSUE THREAD

**Issue by lee27** [Bionus/imgbrd-grabber#2130] opened 2020-09-15 20:52 UTC
**Bug description**
does not enter the site
when i try to enter the site i get a cloudfire block and i can't enter
**System information**
Windows 10

**Comment by yami-no-tusbas** [comment] 2020-09-16 22:41
Work fine on nightly, site is up on the internet, and I don't think this is the support for rule34. If they are down, grabber can do nothing about it.

**Comment by lee27** [comment] 2020-09-17 12:04
I know this is not the right place for this request, but I just wanted to know what to do to get back on the site! thanks

**Comment by ayoits0913** [comment] 2020-09-21 01:23
That site hasn't worked in 9 months: https://github.com/Bionus/imgbrd-grabber/issues/1858

They added Cloudflare to their site :( Unless something has changed?? Were you able to access it lately?

**Comment by yami-no-tusbas** [comment] 2020-09-21 06:48
`[08:46:00.588][Info] [rule34.xxx][Html] Loading page https://rule34.xxx/index.php?page=post&s=list&tags=&pid=0
[08:46:00.588][Info] [rule34.xxx][Xml] Loading page https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
[08:46:00.636][Info] [rule34.xxx][Xml] Receiving page https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
[08:46:00.658][Info] [rule34.xxx][Xml] Parsed page https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=: 20 images (20), 0 tags (446), 3681962 total (3681962), 184099 pages (184099)
[08:46:00.677][Info] [rule34.xxx][Html] Receiving page https://rule34.xxx/index.php?page=post&s=list&tags=&pid=0
[08:46:00.715][Info] [rule34.xxx][Html] Parsed page https://rule34.xxx/index.php?page=post&s=list&tags=&pid=0: 42 images (42), 85 tags (85), -1 total (-1), -1 pages (-1)`

Not a single problem here, maybe because i'm from belgium ? Some kind of regional blockin or security ?

**Comment by Bionus** [comment] 2020-09-22 23:55
I'll close this as a duplicate of #1858.
The issue is caused by the CloudFlare protection that blocks bots/scrapers such as Grabber.

@yami-no-tusbas `rule34hentai.net`, `rule34.paheal.net`, and `rule34.xxx` are different websites.
Only the `rule34hentai.net` (that uses Shimmie) is affected because it's hidden behind CloudFlare. Others are indeed fine 👍

**Closed by Bionus** 2020-09-22 23:55 UTC
