### ISSUE TITLE
Crashing on Large Batch Downloads

### ISSUE THREAD

**Issue by rushuna86** [Bionus/imgbrd-grabber#1113] opened 2017-10-14 12:01 UTC
### What steps will reproduce the problem?

Load up the tag list total images approximate 14-15k pics(List Provided). And Start Download
Batch setting do nothing, follow download, removed ticked.

### What is the expected behavior? What do you get instead?
Expect batch to complete and complete tags removed from list.
Instead it opens up multiple windows of Downloaded, Ignored Skipped files and then crashes.
Sometime just crashes 1/2 way through downloading.

### How often does this problem occur? On which sources?
Everytime a large batch list is done. Danbooru.

### What version of the program are you using? On what operating system?
Version 5.5.1
Windows 10 Pro 64bit

**Comment by Bionus** [comment] 2017-10-14 19:35
>  Instead it opens up multiple windows of Downloaded, Ignored Skipped files and then crashes.

Does it always happen?
Does it ever happen if you start downloads one by one? (instead of using "Download all")

>  Sometime just crashes 1/2 way through downloading.

Do you have in your downloads list batches for which you already downloaded a lot of images? i.e. you already downloaded 90% of tags for "tag_test" and you add a "Get all" batch on that tag. From the log file you provided, it seems that could be the base. I've had reports that this could cause crashes (see issue #1059) but I have yet to investigate it properly.

**Comment by rushuna86** [comment] 2017-10-14 23:50
it only happens when you download all with list, if you download one by one it works fine.

**Comment by rushuna86** [comment] 2017-10-14 23:55
and yes im just updating the tag for pictures i dont have so I do have most of the pictures already

**Comment by warbear** [comment] 2017-10-29 13:05
+1 This issue. Attempting to issue a download batch of ~75K images, skipping ones already downloaded (Library update). Crashes.

**Comment by rushuna86** [comment] 2017-10-29 13:07
i've been playing around with it. If you just do a "download selected" only it does crash.....

**Comment by warbear** [comment] 2017-10-29 13:10
Confirming what you said, that seems to work just fine.

**Comment by Bionus** [comment] 2017-10-29 14:11
Is your "simultaneous downloads" setting (in the "Save" category) set to a value higher than 1? If you put it back to 1, does it stop crashing?

Also, if you open your `settings.ini` file (in "C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber"), and add a line `packing_size=100000` just after `[General]`, does the crashes stop?

Another option is to try using the nightly version to see if the crash was fixed there (I did a lot of changes). You can find it here: https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly

If none of these work, I'll continue investigating. :smile:

**Comment by warbear** [comment] 2017-10-29 15:02
> Is your "simultaneous downloads" setting (in the "Save" category) set to a value higher than 1? If you put it back to 1, does it stop crashing?

My simultaneous was set to 3, changed to 1 - no longer crashes.

**Comment by Bionus** [comment] 2017-10-29 16:30
In that case that may have been fixed in v5.5.2. :+1:

If you update you should be able to re-increase it to 3 and it hopefully shouldn't crash.

**Comment by rushuna86** [comment] 2017-10-30 02:30
i'll give this a shot when i get home later from work, with just library update. And if it still crashes i'll try nightly n give u logs for it.

**Comment by rushuna86** [comment] 2017-10-30 08:52
Can confirm 15k batch with some tags that are only for updating, it no longer crashes. Have setting on download 10 simultaneous downloads as well. :)

**Comment by Bionus** [comment] 2017-10-30 10:26
That's great to hear!
I'll be closing this issue then. :smile:

As for the "remove" checkbox, it seems to be the same issue as #812. I never could reproduce, but I'll give it another go.

**Closed by Bionus** 2017-10-30 10:26 UTC
Labels: crash
