### ISSUE TITLE
The bottom panel disappeared while viewing the image

### ISSUE THREAD

**Issue by Oleksandrigo** [Bionus/imgbrd-grabber#3155] opened 2024-05-14 18:24 UTC
**Bug description**
See screenshot
![image](https://github.com/Bionus/imgbrd-grabber/assets/36889089/aaac7a86-24d9-4b1e-9f80-fa4dcbd3cfe5)
The plus sign isn't clickable
PS Sometimes such an error pops up.
`[21:31:29.712][Warning] [Qt][default] QIODevice::read (QNetworkReplyHttpImpl): device not open`

**Steps to reproduce**
Open any source, open any image - profit

**Expected behavior**
It should display a panel with the ability to save, etc.

**Context**
Grabber appdata folder 
[Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/15312476/Grabber.zip)

**System information**

- OS: Windows 11
- Grabber version: 7.12.1

**Comment by Eathearth** [comment] 2024-05-16 04:33
Same issue on Linux (Flatpak) since 7.12.1,click Tools > Options > ok the bottons will reappear
![屏幕截图_20240516_122147](https://github.com/Bionus/imgbrd-grabber/assets/57564279/2fbac1f5-c88a-4b20-af3c-18d232d46642)

**Comment by Bionus** [comment] 2024-07-20 17:39
Closing as duplicate of issue #3071, let's keep the discussion there 👍

**Closed by Bionus** 2024-07-20 17:39 UTC
Labels: duplicate, bug, ui, reproduced
