### ISSUE TITLE
Decided to press report

### ISSUE THREAD

**Issue by Herkules97** [Bionus/imgbrd-grabber#591] opened 2016-08-25 06:45 UTC
### What steps will reproduce the problem?

Trying to download from one site which has more than 2500-10000 images.
### What is the expected behavior? What do you get instead?

Crash, CPU and Memory stays under 50% use so it shouldn't be because of that.
### What version of the program are you using? On what operating system?

4.6.0/Windows 10
### Please provide any additional information below

My log file is located in appdata - local - bionus - grabber, but the crash reporter said users - user - grabber.. And I didn't seem to be able to change that.
[Almost empty log file](https://github.com/Bionus/imgbrd-grabber/files/436320/main.txt)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/436319/settings.txt)
Just checked it and it doesn't seem to contain anything before the crash

It's probably a very common issue, well I tried it again to get a log file filled, maybe that helps.. Idk.
[Filled log file](https://github.com/Bionus/imgbrd-grabber/files/436340/main.txt)

I am using another program that uses 10-15% of my cpu, I will try downloading with as little programs as possible in a few hours.
Just checked with the task manager, it gets up to 1800mb memory loading (downloading pages/Preparing images) 87K images from one source (safebooru.org)
-and from 1-10% cpu downloading pages to 27-30% cpu preparing images, it freezes on preparing images every time, tho now it's been stuck for more than 5min..
The memory usage goes up 0.1MB every 6th second...and now it crashed. 
Can't sadly share the dump files as they all fail creation.
[Log file 87k image source](https://github.com/Bionus/imgbrd-grabber/files/436365/main.txt) as told by the last line

**Comment by Herkules97** [comment] 2016-08-25 07:18
I don't remember it crashing this much before (a few months ago) tho I used the same version today before I updated to 4.6.0 so maybe it has to do with programs I have open, who knows. Will try without most of them open in a few days. It could all be my memory and that it did actually crash this badly. But I don't see why that would be when I have a folder with 18.9GB of one tag created 21 June, which means I'm able to download a lot of files.. or was. The folder contains 40552 files.

**Comment by MasterPetrik** [comment] 2017-09-05 23:29
for @Bionus about that issue:

- many similar and more fresh issues(#618 for example)
- crash report was made about old batch download system, it changed in next versions, so this report is not relevant anymore
- maybe already solved in newer versions or autor solved it by other ways

# **I recommend to close this issue.** 
And if the issue is still relevant, then autor can ask to reopen it anytime anyway.

**Closed** 2018-04-29 13:28 UTC
Labels: bug, crash
