### ISSUE TITLE
Image viewer button settings not saving between launches on latest nightlies

### ISSUE THREAD

**Issue by Wryyyong** [Bionus/imgbrd-grabber#3110] opened 2024-03-07 07:24 UTC
**Bug description**

Upon launching an instance of 'Grabber', the program fails to load the values set to `activeButtons` and `allButtons` within `settings.ini`, followed by overwriting the aforementioned settings with `@Invalid()` values.

This results in the buttons in the viewer being completely absent until you get the program to write fresh values to `activeButtons` and `allButtons` (even as little as opening the Options dialog and immediately clicking 'OK' out of it will suffice). Following this, the problem will not occur again until 'Grabber' is closed and re-launched.

This has the added effect of needing to re-create your preferred button settings everytime you wish to use the program.

**Steps to reproduce**

1. Launch an instance of 'Grabber' by running its executable.
2. Run a search with any source(s).
3. Click on any result to open the image viewer.
4. Notice the lack of buttons inside of the viewer window.

**Expected behavior**

'Grabber' loading the values saved to `activeButtons` and `allButtons` properly, thus allowing for the user's configuration for the buttons to be saved between program launches.

**Context**

While I won't upload the full logs and settings here, I _will_ include the portions of both relevant to this issue:

- Immediately following the temp directory purge log, two instances of the following line appear in the log:
```
[Warning] [Qt][default] QVariant::load: unknown user type with name QList. 
```
- Upon launching the program, it failing to load the values before writing to `settings.ini` results in this:
```ini
[Viewer]
activeButtons=@Invalid()
allButtons=@Invalid()
```

If further information is desired, feel free to ask for it.

**System information**

- OS: Windows 10 22H2
- Grabber version: 7.11.2-a9b8d443

**Comment by Bionus** [comment] 2024-07-20 17:43
Thanks for the report and the details provided! They actually helped reproduce and pinpoint the root cause of the issue, so I'll be able to provide a fix ASAP 🎉 

Closing as duplicate of issue https://github.com/Bionus/imgbrd-grabber/issues/3071 though, since even if this one has more details, that one is older, so I'll move the discussion there 👍

**Closed by Bionus** 2024-07-20 17:43 UTC
Labels: duplicate, bug, ui, reproduced
