### ISSUE TITLE
2000+ images downloaded but only 800 is in the artist folder 

### ISSUE THREAD

**Issue by Sprenzy** [Bionus/imgbrd-grabber#1148] opened 2017-11-15 04:59 UTC
I don't know what the problem is but shouldn't all 2000 images should be in the folder with the artist's name? 
here is what I use for file name %artist%/%copyright%/%character%/%md5%.%ext% (btw it's a little clunky because I so many images are in like miles and miles of folders, any way to make it more simpler)?

**Comment by MasterPetrik** [comment] 2017-11-15 11:09
There is an easy explanation. Many sources doesn't recognize artist, copyright, character TYPES of tags, they define them as ordinar tags, so it's impossible for grabber to sort images from such sources in such folders. That's not a Grabber problem, that's a some source tag system problems. And moreover, not all images have all these tags(artist, copyright, character) so your folders tree will fail with sorting such images. So it's not a bug at all, all works as it should.

Also there are already exist opened issues https://github.com/Bionus/imgbrd-grabber/issues/916 and https://github.com/Bionus/imgbrd-grabber/issues/1100 that can at least particulary solve this problem in the future. So no other new issues required.

**Comment by Sprenzy** [comment] 2017-11-15 15:30
I tried downloading into a separate folder, can you observe any issues?
[New WinRAR ZIP archive.zip](https://github.com/Bionus/imgbrd-grabber/files/1475271/New.WinRAR.ZIP.archive.zip)

**Comment by Bionus** [comment] 2017-11-15 20:50
Could it be that you simply have the "If a file already exists globally" setting set to "Don't save"? If so, all images that you already downloaded, even if by another batch download, won't be downloaded again.

![image](https://user-images.githubusercontent.com/882719/32859465-e0fa7b10-ca4e-11e7-8a4b-1cccc09fa1b9.png)

**Comment by Sprenzy** [comment] 2017-11-16 03:41
I checked and it is on save

**Comment by MasterPetrik** [comment] 2017-11-16 12:29
I have seen your video and didn't saw anything strange. Then I downloaded ke-ta(btw good taste) from every source too. And didn't saw anything strange too. I got ~800 images, as it should be.

I guess I am understood your problem. You see over 2k images and think "hey, where are all these images, I have only 800+!?" But you should understand that there is never was more than 800+ unique images in all sources. most of sources gets their images from the ONE site - Pixiv, so if some artist made new artwork, 6 different boorus grabbed it and posted on their sites. But if you will download images from all these boorus, you will download only one image, and 5 times Grabber will tell you that another 5 files are already existing, because it's the same image, it will be saved as one image anyway, but otherwize it would be rewritten from each next source. And in the end you would have still  only one image.
![image](https://user-images.githubusercontent.com/22294259/32889273-4d4db62e-cadb-11e7-97f0-ec51889762b1.png)
So don't be confused by these numbers, they only indicates you that Grabber did'nt rewrited the same images.

**Comment by Sprenzy** [comment] 2017-11-16 18:32
Oh I see, thanks for the help. now I understand :) 

btw you know any other artists I would like? It doesn't have to be the same style. I'm just looking for well drawn characters so I can study the anatomy and style

**Comment by MasterPetrik** [comment] 2017-11-22 21:51
> I'm just looking for well drawn characters so I can study the anatomy and style

you can't study the anatomy from such artists, they all are uses different anatomy and style, if you wanna study you need to start with something less detailed, scetches for example

@Bionus a qurstion is answered, you can close the issue.

**Closed** 2017-11-22 22:35 UTC
