### ISSUE TITLE
Sankaku doesn't work properly

### ISSUE THREAD

**Issue by fighuass** [Bionus/imgbrd-grabber#1045] opened 2017-08-26 14:14 UTC
### What steps will reproduce the problem?

Just downloading a few images, really. In my case, I tried downloading groups. Some images get green check marks and are therefore successfully downloaded, but some stay as blue download icons, even though they're 100% downloaded. After that, I only get those blue download icons when downloading, so nothing can be downloaded. I'm also temporarily banned from https://sankakucomplex.com, but not from https://chan.sankakucomplex.com, interestingly.

### What is the expected behavior? What do you get instead?

I'm expecting to be able to download images in batch just like any other booru, but I keep getting banned, so I can't download images in batch using Grabber and am forced to do it manually by using the site. (Which is a huge chore)

### How often does this problem occur? On which sources?

Every time I try to download multiple images from Sankaku, source: chan.sankakucomplex.com

### What version of the program are you using? On what operating system?

Grabber version 5.5.0
OS: Windows 10 Home Premium 64-bit

### Please provide any additional information below

I tried changing the download settings in site options to this: https://i.imgur.com/l1z5Ha1.png

As this was recommended in another issue.

**Comment by MasterPetrik** [comment] 2017-08-29 14:31
another duplicate of #997?

**Comment by fighuass** [comment] 2017-08-29 19:26
Yes 🙄

**Comment by Bionus** [comment] 2017-08-31 11:26
Closing for duplicate then.
As said there, unfortunately Sankaku is blocking Grabber. 😢

**Closed by Bionus** 2017-08-31 11:26 UTC
