### ISSUE TITLE
Crashes on search

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#712] opened 2016-12-14 14:25 UTC
### What steps will reproduce the problem?
Search Werewolf

### What is the expected behavior? What do you get instead?
Should come up with results in either Merged or non-merged view, instead I crash

### What version of the program are you using? On what operating system?
v5.0.1 win7

### Please provide any additional information below
I search with 25 set for images.
Here' s my crash log.
https://volafile.io/r/9662agx8
If there's anything else you need, please ask me to upload it.

**Comment by Bionus** [comment] 2016-12-16 19:00
>  If there's anything else you need, please ask me to upload it.

The `main.log` file right after a crash (before restarting Grabber) would be of great help!
Because I couldn't reproduce said crashes, even with the crash dumps.

**Comment by SultrySamthepennanceman** [comment] 2016-12-16 21:23
resposted

**Comment by Drakonas** [comment] 2016-12-18 09:15
I believe I may have had this crash as well, however I cannot reproduce it.. I wonder if it's related to the Sankaku issue that was fixed... Sorry that I can't provide a log.. What I had problems with is merged view was not loading so I turned merged view off, reloaded, then changed it back and as soon as I ticked the box I got a crash.

**Comment by ItsSohma** [comment] 2017-07-06 13:50
@SultrySamthepennanceman @Drakonas still happening?

**Comment by Drakonas** [comment] 2017-07-07 20:59
I just tested and it did not crash. It may have been related to my reported issue where searching and then changing from non-merged to merged or vice versa while it is searching would cause a crash, but the developer fixed that issue already. But of course I'm not sure if that was the issue with this submission. The OP is a bit vague here.

**Comment by BarryMode** [comment] 2017-08-04 03:46
In that case, I'm guessing this can be closed then.

**Closed** 2017-08-04 09:48 UTC
Labels: crash
