### ISSUE TITLE
Thumbnail Video Loading is Slow and Bottom Setting Button Not Showing

### ISSUE THREAD

**Issue by Kukuru97** [Bionus/imgbrd-grabber#3168] opened 2024-05-19 23:02 UTC
**Bug description**

-Thumbnail Video Loading is Slow or sometimes fail to load (Especially in Gelbooru and rule34.paheal.net)
-Bottom Setting Button Not Showing (the one with Detail, Open, Save, etc. when viewing an image)

**Steps to reproduce**

1. Open the program.
2. View random image.
3. Observe that the buttons at the bottom (e.g., Detail, Save, Open) do not show up.
4. How i fix this, Interface -> Base Style and change the style to anything else (e.g., from Windows style to WindowsVista or Fusion). The problem will disappear.
5. Even if you revert back to the original style, the problem remains fixed after changing the style once. This issue occurs with all styles, not just the Windows style. However, when I reopen the app, the problem reoccurs.

Additionally, when I click on the '+' button, nothing happens; the options do not appear

For the thumbnail issue:

1. When searching for animated images/videos, the thumbnails load very slowly or fail to load altogether.
2. This problem is especially noticeable on Gelbooru and rule34.paheal.net

**Context**

[main_2024.05.20-05.33.17.998.log](https://github.com/Bionus/imgbrd-grabber/files/15371047/main_2024.05.20-05.33.17.998.log)
[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/15371050/settings.zip)

**Screenshots**
![image](https://github.com/Bionus/imgbrd-grabber/assets/100615360/b4520b1a-5e1b-46c1-bafc-92c1b4727c24)
![image](https://github.com/Bionus/imgbrd-grabber/assets/100615360/7a7b0e72-1c66-4a90-8846-5d6319a3bf95)
![image](https://github.com/Bionus/imgbrd-grabber/assets/100615360/8bfb183e-f56b-4080-887b-b52cc6d2244f)

**System information**

- OS: Windows 11 23H2 (OS Build 22631.3593)
- Grabber version: 7.12.2

**Additional context**

I tried using Grabber version 7.11.2 and didn't encounter any of the issues mentioned above. Therefore, the thumbnail loading issue is not due to my connection

**Comment by A5MRT** [comment] 2024-05-20 04:09
I'm having the same issue, I'm guessing its not an isolated issue.

**Comment by Bionus** [comment] 2024-07-20 17:40
Thanks for the report and the details provided!
Closing as duplicate of issue #3071 though, let's move the discussion there 👍

**Closed by Bionus** 2024-07-20 17:40 UTC
Labels: bug, ui, reproduced
