### ISSUE TITLE
Derpibooru is still not working Images aren't loading correctly

### ISSUE THREAD

**Issue by SvyraCosmix** [Bionus/imgbrd-grabber#643] opened 2016-10-20 00:49 UTC
### What steps will reproduce the problem?

Any tags
### What is the expected behavior? What do you get instead?

Whenever I search a tag, "crossdressing" for example, I get less image results than expected, 741 is what grabber says yet there is 2111 on the website. So in short images are loading properly. They aren't downloading properly either, I click the "get all" button. It says it's going to download 741, again should be 2111, but even then when the download starts, it said blank/165, it only download 165. I'm not sure why this is happening. If it's the program or something I'm not doing right. I added the API to the credentials so thats not the problem.
### What version of the program are you using? On what operating system?

4.8.3 The one that says "Fixed Derpibooru" but hasn't
Windows 7

**Comment by Bionus** [comment] 2016-10-20 01:05
`crossdressing` returns 1,631 images while logged out and 3,075 when logged in. I confirmed the logged out version properly downloads everything just now (1,631 images downloaded, no credentials provided).

Where did you get the 2,111 number?

> I added the API to the credentials so thats not the problem.

By this, you mean you added your API key in the "password" field of the credentials I suppose?

**Comment by SvyraCosmix** [comment] 2016-10-20 01:39
Sorry, I was thinking of the "femboy" tag, but still, like you I do get 1,631 results, I don't know how you got the 3.075, because derpibooru the website says there are 3.529 results for crossdressing. It's doing this for every tag. 
Yes I added the API to the password field that way I was able to also view the explicit images since I am using the "Everything" filter on the website.
![capture](https://cloud.githubusercontent.com/assets/19334444/19543292/fe69b46a-963b-11e6-9a07-8d9c0885a27c.PNG)

**Comment by Bionus** [comment] 2017-05-18 22:38
Moving to most recent #907

**Comment by Bionus** [comment] 2017-05-18 23:36
Re-opening because the issue here is that the image/page count used for results is the one from the Regex API instead of the JSON API, which is different because the API key does not work in Regex mode.

**Closed** 2017-05-20 18:12 UTC
Labels: bug, source

**Comment by SvyraCosmix** [comment] 2017-05-20 18:22
Please explain to me what all of that means.
