### ISSUE TITLE
Error on search. can't search any booru at all.

### ISSUE THREAD

**Issue by notlewd** [Bionus/imgbrd-grabber#1043] opened 2017-08-26 00:29 UTC
### What steps will reproduce the problem?
clicking search source danbooru.donmai.us

name: %md5%.%ext%

click ok

log 
![xhbof02](https://user-images.githubusercontent.com/31360074/29736873-051e0178-8a0e-11e7-8eb4-f94f3af6615e.png)

### What is the expected behavior? What do you get instead?
searching images.

nothing. log errors

### How often does this problem occur? On which sources?
always when i try to search on
pages results:
-behoimi.org: Nothing
-capi.sankakucomplex.com: Nothing
-chan.sankakucomplex.com: Nothing
-danbooru.donmai.us: Nothing
-derpibooru.org:  @Nothing
-e621.net: Nothing
-gelbooru.com: Nothing
-hijiribe.donmai.us: Images
-ichijou.org: No result (Service Temporarily Unavailable)
-idol.sankakucomplex.com: Nothing
-konachan.com: Images.
-rule34.paheal.net: Images.
-rule34.xxx: Nothing
-rule34hentai.net: Images.
-safebooru.org: Images
-sonohara.donmai.us: Images
-Tentaclerape.net: No result
-Zerochan.net: Nothing
-yande.re: Nothing

### What version of the program are you using? On what operating system?
5.5.0 on Windows 10

### Please provide any additional information below
same issue  as #1034

**Comment by MasterPetrik** [comment] 2017-08-26 03:06
> same issue as #1034 

If it's the same issue, then why did you deсided to make duplicate of it? 
what for?

**Comment by notlewd** [comment] 2017-08-27 00:37
No one replied on that post. so i opened a new one.

**Comment by Bionus** [comment] 2017-08-31 11:28
I'll close here then.
Feel free to bump other issues if they go unnoticed :smile:

**Closed by Bionus** 2017-08-31 11:28 UTC
