### ISSUE TITLE
Gelbooru 0.1 sites not opening 

### ISSUE THREAD

**Issue by sak444** [Bionus/imgbrd-grabber#2241] opened 2021-01-22 07:01 UTC
it says No result, Possible Reasons: servers offline even though its online. i tried every other version and downloaded the latest version of visual c++ nothing is working whats the problem? help please thank you

**Comment by yami-no-tusbas** [comment] 2021-01-22 07:45
Seem to be a duplicate of #2214

**Comment by sak444** [comment] 2021-01-22 13:50
bro can you please tell me how to do user agents, cookies , or model.js files? or is there some tutorials on them? i searched it up but couldnt find any i would really appreciate if you help me man

**Comment by sak444** [comment] 2021-01-22 14:21
OK i fixed it. In case anyone having problems this is what you gotta do: add the gelbooru site to the sources, after that open options of the site you entered in the sources, get to headers, And put: ''User-Agent'' to the name and put:
 ''Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0'' to Value and that should fix it

**Closed** 2021-01-22 14:21 UTC
