### ISSUE TITLE
No results on Gelbooru search

### ISSUE THREAD

**Issue by ElGroog** [Bionus/imgbrd-grabber#2679] opened 2022-05-03 18:20 UTC
**Bug description**
When I go to search for something (Ex: Blonde_Hair) using Gelbooru as a source, it returns with "No Result" this issue persists on any tag/search.

**Context**
I tried installing different versions of the program using both x64 and x86 versions, and I still get this same issue. I removed all traces of grabber and installed new bone stock versions of the application but the issue still persisted, I also tried installing it on different drivers to no avail. Could this be a network issue on my end? because searching up the same tags and such on the actual Gelbooru website and things work fine over there. 

Log file can be found below
[main.log](https://github.com/Bionus/imgbrd-grabber/files/8612725/main.log)

**System information**

OS: Win 10 Ver 21H2 (Build 19044.1645)
Grabber Ver: 7.8.1 x64

**Comment by ElGroog** [comment] 2022-05-06 18:13
**UPDATE**

Tried Grabber Ver: 5.3.3 and everything works as intended. This could be an issue with my vcredist version, gonna update it and see if that'll fix things up.

**Comment by Bionus** [comment] 2022-05-07 11:05
Have you tried deleting the `sites` folder in the settings directory after updating to 7.8.1?
There has been a recent fix for Gelbooru but since 7.8.0 the sites files are now in Program Files.

**Comment by Bionus** [comment] 2022-05-07 11:05
Closing as duplicate of #2668

**Closed by Bionus** 2022-05-07 11:05 UTC
Labels: duplicate, bug, source, cant-reproduce
