### ISSUE TITLE
[bug/suggestion] %num% filename token does not go beyond 10 in a batch download, and is invalid as a token unless it's the sole non-extension token.

### ISSUE THREAD

**Issue by Mythrrinthael** [Bionus/imgbrd-grabber#978] opened 2017-07-07 13:16 UTC
### What steps will reproduce the problem?
Source: idol.sankakucomplex.com

1. Pick tags related to cosplay set (or tag for cosplay set name if it has one), with order:ID and rating:s metatags
2. Receive expected search results
3. Set destination as subfolder within Grabber's default destination folder, named after the cosplay set 
4. Set filename "%num%.%ext%"
5. Click "Get all"
6. Go to download page and click "Download"
---

Repeat steps 1. through 3.
4. Set filename to include %num% and any amount of other tokens, before or after %num%, that isn't related to file extensions. 

### What is the expected behavior? What do you get instead?
Expectation: all images downloaded to "(...)\Grabber\[chosen folder name]", all images named starting from "001.[extension]" and counting to whatever the number count of the last image is.

Result: only the first 10 images downloaded to "(...)\Grabber\[chosen folder name], named "1.[extension]" up to "10.[extension]". The rest are considered "already existing" and are ignored.

---

Expectation: tokens are all considered valid and result in expected output.

Result: Error message "The %num% token does not exist and will not be replaced"

### How often does this problem occur?
With every cosplay set I tried, but I have only tried with idol.sankakucomplex.com as a source. I have used different subfolder destinations, and with repeat attempts of the same set I first deleted pre-existent subfolder contents.

### What version of the program are you using? On what operating system?
Version: 5.4.0
Windows 10 Home

### Please provide any additional information below
Using "%num%.%ext%" tag did produce a warning about non-unique filenames, but I assumed this would not be a problem if each batch was sent to different folders.

If it is a bug (which I consider likely) but also not a present feature, please consider changing %num%'s behavior to prefix the first file with zeroes equal to the number of digits of that specific download batch total (If there's 283 images, prefix the first download in that batch with two zeroes and continue from there as applicable).

**Comment by MasterPetrik** [comment] 2017-07-07 15:39
> Using "%num%.%ext%" tag did produce a warning about non-unique filenames, but I assumed this would not be a problem if each batch was sent to different folders.

Try this: %search%\%num%.%ext%

**Comment by Mythrrinthael** [comment] 2017-07-07 21:58
>Try this: `%search%\%num%.%ext%`
![Seems ineffective](http://i.imgur.com/cLDpik2.png). I tried again (Cleared folder) with a regular slash instead of a backslash because I thought that might be a mistake, but this leads to the exact same result as in the image.

**Comment by MasterPetrik** [comment] 2017-07-07 22:36
maybe `%num%` prefix works wrong then...?

**Comment by Bionus** [comment] 2017-07-08 17:40
I could indeed reproduce that the `%num%` token was behaving weirdly, caused by non-natural sorting at some point in the code making it always think the last saved file is "9" therefore generating a num of "10" indefinitely.

I pushed a fix that should arrive in the next nightly, or you can wait for the next update if you prefer, and if you actually have only one folder per batch download, you could also use `%count%` as a temporary replacement for `%num%`.

> If it is a bug (which I consider likely) but also not a present feature, please consider changing %num%'s behavior to prefix the first file with zeroes equal to the number of digits of that specific download batch total (If there's 283 images, prefix the first download in that batch with two zeroes and continue from there as applicable).

The point is `%num%` is not related to the batch download itself, so it can't use any "total" count (283 in your example). It's only here to prevent overwriting when multiple images could have the same name (the warning in Grabber is actually misleading). That's also why you could have multiple files named "1" in a given folder if you use `%num%.%ext%`: "1.png" and "1.jpg". Since neither would overwrite the other, they're both given the value of 1.

If what you want is a count per batch, `%count%` is the way to go, and is relative to **all** batches you start at a given time (i.e. if you start 2 batches using "Download all" they will share the same `%count%`)..

Could it be that what you want is almost like num, except for the part about the extensions not increment the count? (i.e. in my example having "1.jpg" and "2.png")

**Comment by Mythrrinthael** [comment] 2017-07-08 20:42
Good to know I helped you determine several instances of unusual behavior.

Sadly, using `%count%` still leaves me with a significant problem. Repeating all conditions and steps in my original post, the result of using `%count%.%ext%` as filename tokens is only the first image in the batch downloaded and the rest ignored because "they already exist". 1.[extension], and that's it.

---

My request for an extension-insensitive incremental `%num%` came from how I assumed the nature of the bugs I encountered were different than they actually were (example: your mention of the misleading warning about `%num%`). Never getting more than _**one sole image**_ downloaded properly when using plain incremental number filenaming seems too ludicrous to be true, but here I am.

**Closed** 2017-07-09 15:07 UTC
Labels: bug, reproduced
