### ISSUE TITLE
Filename/Tag Parsing issue when restarting Grabber

### ISSUE THREAD

**Issue by xodiack** [Bionus/imgbrd-grabber#2351] opened 2021-04-28 00:43 UTC
**Bug description**

When restarting grabber due to a connection to a source getting stuck/hanging I noticed upon resuming downloads the images added to my download list would not parse the tags correctly for filenaming/directory sorting.

**Steps to reproduce**

- On Danbooru search "md5:a4392791c5909936f974ea5ee0b8f88b"
- Highlight the image then "Get selected"
- Close and reopen grabber.
- Upon reopening, in the Downloads tab, hit the "Download" button.
- The image will then be downloaded ignoring the booru tags.

This also occurs on the shall not be named source.
I tested the same image on Gelbooru and it correctly downloaded with tags after restarting the software.

**Expected behavior**

When downloading via single images added via "Get selected" if the program needs be restart it should (I hope) be able to download with the tags related to the image when added to the single images list.

For reference, my naming convention follows: **%copyright:sort%/%artist:sort%_%character:sort%_%md5%.%ext%**

**Context**

[Issue-Apr2021.zip](https://github.com/Bionus/imgbrd-grabber/files/6388342/Issue-Apr2021.zip)

Inside is the main.log of after searching and adding to the download list and one after restarting the software and starting the download. Image included of the test image if its needed.

**System information**
W10, Grabber 7.5.1

**Additional context**

I'm not sure if this is a new bug or something that has been around, I just happened to have a window opened showing the files as they were added to the directory, and noticed a majority of them were ending up as anonymous_md5goeshere.ext

Please let me know if there's anything more I could provide to help recreate this issue.

**Comment by Bionus** [comment] 2021-04-28 13:23
Thanks for the report 👍 
I could indeed reproduce the issue.

It was caused by tags being saved as basic list of tags without any type information in download list files (IGL files). I just pushed a fix which will store tags with all their information (count, ID, type) from now on.

**Closed** 2021-07-05 14:29 UTC
Labels: bug, reproduced
