### ISSUE TITLE
Broken QsciScintilla on Ubuntu

### ISSUE THREAD

**Issue by 523334** [Bionus/imgbrd-grabber#546] opened 2016-06-27 04:45 UTC
I was affected by the segfault builds on my Linux Mint 17.3 system. Commit a3856511072a6cf8b5073300054250b39803bc8a fixed that (thanks btw!), but I still can't compile the latest source due to references to missing QsciScintilla parts.

```
g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o Grabber aboutwindow.o addgroupwindow.o adduniquewindow.o batchwindow.o blacklistfix.o blacklistfix2.o commands.o conditionwindow.o crashhandler.o customwindow.o detailswindow.o downloader.o emptydirsfix.o emptydirsfix2.o favorite.o favoritestab.o favoritewindow.o filenamewindow.o functions.o image.o imagethread.o json.o main.o mainwindow.o md5fix.o optionswindow.o page.o pool.o pooltab.o QAffiche.o QBouton.o qclosabletabwidget.o searchtab.o searchwindow.o site.o sitewindow.o sourcessettingswindow.o sourceswindow.o startwindow.o tag.o tagtab.o textedit.o zoomwindow.o qcommandlineoption.o qcommandlineparser.o rename-existing-1.o rename-existing-2.o qrc_resources.o moc_aboutwindow.o moc_addgroupwindow.o moc_adduniquewindow.o moc_batchwindow.o moc_blacklistfix.o moc_blacklistfix2.o moc_conditionwindow.o moc_customwindow.o moc_detailswindow.o moc_downloader.o moc_emptydirsfix.o moc_emptydirsfix2.o moc_favoritestab.o moc_favoritewindow.o moc_filenamewindow.o moc_image.o moc_imagethread.o moc_mainwindow.o moc_md5fix.o moc_optionswindow.o moc_page.o moc_pooltab.o moc_QAffiche.o moc_QBouton.o moc_searchtab.o moc_searchwindow.o moc_site.o moc_sitewindow.o moc_sourcessettingswindow.o moc_sourceswindow.o moc_startwindow.o moc_tagtab.o moc_textedit.o moc_zoomwindow.o moc_rename-existing-1.o moc_rename-existing-2.o   -L/usr/X11R6/lib64 -lQt5MultimediaWidgets -L/usr/lib/x86_64-linux-gnu -lQt5Multimedia -lQt5Widgets -lQt5Script -lQt5Sql -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
filenamewindow.o: In function `FilenameWindow::FilenameWindow(QString, QWidget*)':
filenamewindow.cpp:(.text+0x14f): undefined reference to `QsciScintilla::QsciScintilla(QWidget*)'
filenamewindow.cpp:(.text+0x16b): undefined reference to `QsciLexerJavaScript::QsciLexerJavaScript(QObject*)'
filenamewindow.o: In function `FilenameWindow::format()':
filenamewindow.cpp:(.text+0x1b0a): undefined reference to `QsciScintilla::text() const'
collect2: error: ld returned 1 exit status
make[1]: *** [Grabber] Error 1
```

I have libqscintilla2-dev and libqt5scintilla2-dev installed.

**Comment by Flat** [comment] 2016-06-29 18:19
Seems like you may be missing header files for QScintilla2. Can you post the output of 
```ls /usr/include/qt/Qsci```?

Make sure to ```qmake Grabber.pro``` and  ```make clean``` before running ```make```

If you don't need syntax highlighting for the javscript editors you can also comment out the line ```CONFIG += use_qscintilla``` from ```gui/gui.pro```

**Comment by Bionus** [comment] 2016-06-29 23:59
I can reproduce the same issue (on Fedora though), I'll investigate, but from the build line it seems that qscintilla is not being linked properly by g++ (`-lQt5Multimedia -lQt5Widgets -lQt5Script -lQt5Sql -lQt5Xml -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread`).

As Flat said, the simplest option is to simply disable it for now.
I'll fix it in my VM and push a fix ASAP. :smile:

**Comment by Flat** [comment] 2016-06-30 00:02
This may be related to a3856511072a6cf8b5073300054250b39803bc8a, but I'm fairly sure that's the correct name for the library on ubuntu and redhat based systems.

**Comment by Flat** [comment] 2016-06-30 00:22
Looks like Fedora/Ubuntu place libqt5scintilla2 in the lib folder directly. #552 should fix this. Just compiled it on my Ubuntu 16 VPS. Sorry about that

**Comment by Bionus** [comment] 2016-06-30 00:22
After re-reading the PR, it definitely is linked.

If you're on unix (not macx) and none of the two files exist, the library won't be included. I didn't see it before, and that useless CI is always broken. 😄

**Comment by Flat** [comment] 2016-06-30 00:27
In regards to the broken CI, I don't have much experience with travis, but have you tried to change the ```install``` section to ```before_install``` as outlined here https://docs.travis-ci.com/user/installing-dependencies/

**Comment by Bionus** [comment] 2016-06-30 00:31
It's actually already fixed on the [develop branch](https://github.com/Bionus/imgbrd-grabber/blob/develop/.travis.yml), but I haven't merged it yet, I'll merge it for the next small update.

**Closed** 2016-06-30 01:11 UTC
Labels: linux
