### ISSUE TITLE
Downloaded images are broken

### ISSUE THREAD

**Issue by GalangKaluluwa** [Bionus/imgbrd-grabber#1061] opened 2017-09-08 10:46 UTC
### What steps will reproduce the problem?
I searched a tag from sankukaku in the first tab, get all the images from that page, and head to the download tab to download them. The images are downloaded but are broken or corrupted.

### What is the expected behavior? What do you get instead?
I wanted to download images from sankukaku. Instead I get broken files. FML

### How often does this problem occur? On which sources?
It's the first time I used this program after transferring from Danbooru Downloader because it wouldn't let me download images over 1000. The source is from Sankukaku

### What version of the program are you using? On what operating system?
Latest program I guess? Windows 10 

### Please provide any additional information below
Also, when I open the images, I get "Expired link - please reload the site". Please help me guys. This is so frustrating

**Comment by GalangKaluluwa** [comment] 2017-09-08 12:07
Update: I was able to download from Gelbooru. Sankukaku downloads remain broken however

**Comment by Bionus** [comment] 2017-09-08 12:48
Duplicate of #1057. Let's move the discussion there.

But please note that Sankaku is blocking downloaders (disabled API, lots of limitations, etc.), so Grabber is not really working with it for now (see issue #997).

**Closed by Bionus** 2017-09-08 12:48 UTC
