### ISSUE TITLE
No result on sites with Gelbooru Beta 0.1.11

### ISSUE THREAD

**Issue by bhear** [Bionus/imgbrd-grabber#2214] opened 2020-12-24 17:11 UTC
When trying to load images from sources that use Gelbooru 0.1.11, nothing shows up, except "No results. Possible reasons server offline, (Even though it is online), No valid source of the site returned result."

Steps to reproduce:
Choose sources that use Gelbooru 0.1.11 (I've checked it on 6 booru's), then search blank, and the message shows up.
Expected behavior: images showing up.

Main log: [main.log](https://github.com/Bionus/imgbrd-grabber/files/5740154/main.log)
Settings: [settings.txt](https://github.com/Bionus/imgbrd-grabber/files/5740163/settings.txt)

System information
- OS: Windows 8
- Grabber version: 7.3.2 x64 (Latest)

**Comment by SymphonyOfTheAFKLord** [comment] 2020-12-27 06:35
Can confirm I am also having the same issue with sources using Gelbooru 0.1.11. Also using Grabber 7.3.2 x64 however on Windows 10 Pro.

**Comment by SymphonyOfTheAFKLord** [comment] 2020-12-27 06:52
I've just tested using the latest nightly (x64) as well as 7.3.0 and 7.2.0 (both x86) and they're having the exact same issue as well. Can't find anything recent on the Gelbooru forums about any changes to 1.11 so no idea why why this has suddenly become an issue.

**Comment by FuzzyWuggzy** [comment] 2021-01-05 00:22
Have you tried the model.js files provided in #2176 ? It seems as if it's not an isolated incident, every gelbooru based site I tested other than gelbooru.com itself ironically returned the 403 error. As for the reason, it seems to be their adoption of CloudFlare that's the culpit.

**Comment by yami-no-tusbas** [comment] 2021-01-06 10:53
Same as here, put a user agent and it should work. #2223 and you need a "cf_clearance" cookie, you can have it from your web browser and copy paste it to grabber in a new cookie. They *.booru.org will work. But we need Bionus to find a way for it's app to get the cookie itself.

here is the log before and after updating the cookie to add cloudflare clearance : 

```
[11:48:06.179][Info] [furry.booru.org][Xml] Receiving page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
[11:48:06.180][Error] [furry.booru.org][Xml] Loading error: Error transferring https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags= - server replied: Service Temporarily Unavailable (403)
[11:48:06.180][Warning] [furry.booru.org] Loading using Xml failed. Retry using Html.
[11:48:06.181][Info] [furry.booru.org][Html] Loading page https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0
[11:48:06.250][Info] [furry.booru.org][Html] Receiving page https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0
[11:48:06.250][Error] [furry.booru.org][Html] Loading error: Error transferring https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0 - server replied: Service Temporarily Unavailable (403)
[11:48:06.251][Warning] [furry.booru.org] No valid source of the site returned result.
```
**adding the cookie**
[11:48:26.306][Info] Updating checkboxes.

```
[11:48:27.188][Info] Loading results...
[11:48:27.189][Info] [furry.booru.org][Xml] Loading page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
[11:48:28.317][Info] [furry.booru.org][Xml] Receiving page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
[11:48:28.796][Info] [furry.booru.org][Xml] Parsed page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=: 20 images (20), 0 tags (349), 2311191 total (2311191), 115560 pages (115560)
```

It live !!! Well, as long as the cloudflare cookie stay valid...

**Comment by GiovanH** [comment] 2021-01-09 02:30
This is a duplicate of #2176, yes

**Comment by FuzzyWuggzy** [comment] 2021-01-10 02:34
> Same as here, put a user agent and it should work. #2223 and you need a "cf_clearance" cookie, you can have it from your web browser and copy paste it to grabber in a new cookie. They *.booru.org will work. But we need Bionus to find a way for it's app to get the cookie itself.
> 
> here is the log before and after updating the cookie to add cloudflare clearance :
> 
> ```
> [11:48:06.179][Info] [furry.booru.org][Xml] Receiving page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
> [11:48:06.180][Error] [furry.booru.org][Xml] Loading error: Error transferring https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags= - server replied: Service Temporarily Unavailable (403)
> [11:48:06.180][Warning] [furry.booru.org] Loading using Xml failed. Retry using Html.
> [11:48:06.181][Info] [furry.booru.org][Html] Loading page https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0
> [11:48:06.250][Info] [furry.booru.org][Html] Receiving page https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0
> [11:48:06.250][Error] [furry.booru.org][Html] Loading error: Error transferring https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0 - server replied: Service Temporarily Unavailable (403)
> [11:48:06.251][Warning] [furry.booru.org] No valid source of the site returned result.
> ```
> 
> **adding the cookie**
> [11:48:26.306][Info] Updating checkboxes.
> 
> ```
> [11:48:27.188][Info] Loading results...
> [11:48:27.189][Info] [furry.booru.org][Xml] Loading page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
> [11:48:28.317][Info] [furry.booru.org][Xml] Receiving page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
> [11:48:28.796][Info] [furry.booru.org][Xml] Parsed page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=: 20 images (20), 0 tags (349), 2311191 total (2311191), 115560 pages (115560)
> ```
> 
> It live !!! Well, as long as the cloudflare cookie stay valid...

You're a lifesaver, I swear, adding the cookies and the user agent from Firefox was the first thing I did like a month or two back, but for some reason it didn't work at the time, but trying it now it's perfect. Since then I've deleted, pulled, and compiled Grabber multiple times, downloaded the hotfix .js files, modified and added a user agent to the existing model files, and as a last resort created a new user with a clean home directory and a basic xfce setup just in case a rogue config file was messing with it. 

Thanks once again.

**Comment by VanTuz5** [comment] 2021-03-02 21:11
> Same as here, put a user agent and it should work. #2223 and you need a "cf_clearance" cookie, you can have it from your web browser and copy paste it to grabber in a new cookie. They *.booru.org will work. But we need Bionus to find a way for it's app to get the cookie itself.
> 
> here is the log before and after updating the cookie to add cloudflare clearance :
> 
> ```
> [11:48:06.179][Info] [furry.booru.org][Xml] Receiving page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
> [11:48:06.180][Error] [furry.booru.org][Xml] Loading error: Error transferring https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags= - server replied: Service Temporarily Unavailable (403)
> [11:48:06.180][Warning] [furry.booru.org] Loading using Xml failed. Retry using Html.
> [11:48:06.181][Info] [furry.booru.org][Html] Loading page https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0
> [11:48:06.250][Info] [furry.booru.org][Html] Receiving page https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0
> [11:48:06.250][Error] [furry.booru.org][Html] Loading error: Error transferring https://furry.booru.org/index.php?page=post&s=list&tags=&pid=0 - server replied: Service Temporarily Unavailable (403)
> [11:48:06.251][Warning] [furry.booru.org] No valid source of the site returned result.
> ```
> 
> **adding the cookie**
> [11:48:26.306][Info] Updating checkboxes.
> 
> ```
> [11:48:27.188][Info] Loading results...
> [11:48:27.189][Info] [furry.booru.org][Xml] Loading page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
> [11:48:28.317][Info] [furry.booru.org][Xml] Receiving page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=
> [11:48:28.796][Info] [furry.booru.org][Xml] Parsed page https://furry.booru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=: 20 images (20), 0 tags (349), 2311191 total (2311191), 115560 pages (115560)
> ```
> 
> It live !!! Well, as long as the cloudflare cookie stay valid...

Don't work for me...

**Comment by Bionus** [comment] 2021-07-30 19:13
Most current Gelbooru 0.1.11 sites are hosted on booru.org, and usually need a change in user-agent.
Sometimes a Cloudflare cookie as well (the Cloudflare error should now be logged more clearly in the logs).

After changing it, I verified that it's working well, so I'll close the issue.

**Closed by Bionus** 2021-07-30 19:13 UTC
