### ISSUE TITLE
download from rule34hentai.net

### ISSUE THREAD

**Issue by lee27** [Bionus/imgbrd-grabber#1142] opened 2017-11-08 17:00 UTC
hi, it's been a long time since I'm trying to download all the images in a tag, but I've never been able to. how can I do it to succeed? please help me

**Comment by MasterPetrik** [comment] 2017-11-09 05:04
dammit, it's duplicate of https://github.com/Bionus/imgbrd-grabber/issues/1139 need to close

**Comment by Bionus** [comment] 2017-11-11 16:24
Closing for duplication.

**Closed by Bionus** 2017-11-11 16:24 UTC
