### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by angaratosurion** [Bionus/imgbrd-grabber#1054] opened 2017-09-02 18:14 UTC
[crashes.zip](https://github.com/Bionus/imgbrd-grabber/files/1272392/crashes.zip)

### What steps will reproduce the problem?

download images 

### What is the expected behavior? What do you get instead?
to not crash

### How often does this problem occur? On which sources?

everytime

### What version of the program are you using? On what operating system?

5.5.50

**Comment by MasterPetrik** [comment] 2017-09-02 18:52
very poor description

**Comment by angaratosurion** [comment] 2017-09-02 19:01
if i knew what it caused it will be more detailed ..
i just search for images and  select to download them and after sometime unattended it crashes ..

**Comment by MasterPetrik** [comment] 2017-09-02 20:09
crashes happens in batch downloads or in single images download?
right after pressing download button\ in the process of download\ after download ends?
Does any images appers in the destination folder? How many images downloads before crash?
What amount of images(in total) you are trying to download?(better post here screenshot of download list before downloads)

**Comment by angaratosurion** [comment] 2017-09-02 20:13
on batch downloads .. i never tried  or noticed if the download only one
image exists .
the number of images  that exists in the download folder some times are 0
sometimes are 600 or even 6000 .. the number is never the same ..

Παρακαλώ αν γίνεται να επικοινωνούμε γραπτώς για την αποφυγή παρεξηγήσεων
και για διατήρηση αρχείου επικοινωνίας

2017-09-02 23:09 GMT+03:00 MasterPetrik <notifications@github.com>:

**Comment by angaratosurion** [comment] 2017-09-02 20:24
these crashes happened in around different   character downloads .. i also i usually iam away from pc when i download anything o ihave no idea what happens  what the gui shows  before it crashes ..

**Comment by BarryMode** [comment] 2017-09-04 15:16
Just as an update on crashes (since there are currently 20 issues open regarding crashes), here's some potentially useful information:

#1054 @angaratosurion v5.5.5 - User is active, crash appears to stand
#1048 @Still34 v5.5.0 - User is active, crash appears to stand
#1022 @alicemargatroid v5.4.2 - User is active, crash appears to stand
#1003 @fobear697 v5.4.2 - Crash appears to stand. Waiting for user to reply since Jul 28, 2017
#973  @DJPlaya - Duplicate of #618 and #591
#937  @bootyfunker v5.3.3 - Irrelevant: site blocks the program
#870  @ivaskaj v5.2.4 - Crash appears to stand. Waiting for user to reply since Mar 31, 2017
#858  @SultrySamthepennanceman v5.2.3 - User is waiting for a reply from @Bionus since Mar 26, 2017
#840  @Akibaku v5.2.2 - Crash appears to stand, waiting for user reply since Mar 10, 2017
#812  @MasterPetrik v5.2.2 - User is active, crash appears to stand
#795  @SultrySamthepennanceman v5.1.1 - Dupe of #870, waiting for user reply since Feb 20, 2017
#758  @SultrySamthepennanceman v5.1.0 - Waiting for user reply since Jan 27, 2017
#756  @SultrySamthepennanceman v5.1.0 - Dupe of #870
#736  @SultrySamthepennanceman v5.0.1 - Dupe of #870, waiting for user reply since Jan 8, 2017
#706  @SultrySamthepennanceman v5.0.0 - Dupe of #870
#618  @brodycas3 - Appears to be a duplicate of #591
#591  @Herkules97 v4.6.0 - Crash appears to stand
#492  @SultrySamthepennanceman v4.3.0 - Appears to be no longer relevant
#473  @SultrySamthepennanceman
#464  @SultrySamthepennanceman

**Comment by Still34** [comment] 2017-09-04 19:42
It might be more useful if you could provide some information regarding the crash dump.

**Comment by MasterPetrik** [comment] 2017-09-05 02:01
Indeed, crash dumps without settings file, .igl file and log file are not very useful

**Comment by MasterPetrik** [comment] 2017-09-05 03:08
> I personally haven't experienced a crash since v3. 

I'm facing with crashes of Grabber all the times, even now fo me it crashes sometimes, but I don't post  crash reports if I don't know where is the problem, because otherwise it will be not informative and most likely will not be fixed, as in some examples below.

You did a good job by making this crashes list, but for me there are many mistakes in it, so I a bit changed your list, maybe it will improve it.

#issue @author version (problem type) - status

#1054 @angaratosurion v5.5.0 (batch download) - May be a dupe of #618
#1048 @Still34 v5.5.0 (batch download) - dupe of #618 
#1022 @alicemargatroid v5.4.2 (batch download) - User is active, crash appears to stand
#1003 @fobear697 v5.4.2 (download) - User is not replied, also no tech info
#973 @DJPlaya (batch download) - duplicate of #618 
#937 @bootyfunker v5.3.3 (batch download) - No tech info, (may be dupe of #618?) sankaku-related
#870 @ivaskaj v5.2.4 (batch download) - User is not replied, also no tech info, (may be dupe of #618?)
#858 @SultrySamthepennanceman v5.2.3 (unclear) - User waiting for reply from @Bionus since 03.2017
#840 @Akibaku v5.2.2 (batch download) - User is not replied, also no tech info
#812 @MasterPetrik v5.5.0 (GUI) - crash appears to stand, User waiting for reply from @Bionus
#795 @SultrySamthepennanceman v5.1.1 (browsing) - User is not replied, also no tech info dupe of #758
#758 @SultrySamthepennanceman v5.1.0 (browsing) - User is not replied, also no tech info
#756 @SultrySamthepennanceman v5.1.0 (unclear) - @Bionus is not replied, (may be dupe of #618?)
#736 @SultrySamthepennanceman v5.0.1 (batch download) - User is not replied, also no tech info
#706 @SultrySamthepennanceman v5.0.0 (batch download) - Dupe of #618, also no tech info 
#618 @brodycas3 (batch download) - still relevant, current main huge downloads crashes discussion
#591 @Herkules97 v4.6.0 (batch download) - dupe of #618, no longer relevant
#492 @SultrySamthepennanceman v4.3.0 - Big bunch of issues from v4.3.0, may be no longer relevant
#473 @SultrySamthepennanceman (unclear)
#464 @SultrySamthepennanceman (source)

**Comment by BarryMode** [comment] 2017-09-05 04:56
@MasterPetrik thanks for reworking the list. I didn't spend a ton of time on it, so it needed some refining. Hopefully it's helpful toward the development. The reason I haven't experienced a crash in a long time is most likely due to my minimal use of the program. I haven't batch downloaded since then :)

**Comment by angaratosurion** [comment] 2017-09-05 12:52
restore.igol, settings and the log.
[Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/1277425/Grabber.zip)

**Comment by MasterPetrik** [comment] 2017-09-05 21:57
@angaratosurion you are trying to download 28560 images in one batch for "rias_gremory" tag
looks like that's too much images for your grabber, don't try to download batchs 10k+ images and crashes will be over maybe. Because now your crash looks like a duplicate of #618

**Comment by MasterPetrik** [comment] 2017-09-07 14:14
@Bionus, look something strange in .igl file:
![2017-09-06_234613 win7 mastercore](https://user-images.githubusercontent.com/22294259/30167637-b5773bc6-93ef-11e7-9a49-c93b75b051ea.png)

I guess that's the origin of the problem. For this tag even in all sources are ~5000 results images, and here is written that only on gelboru there are 28k of them. That's impossible. Any ideas, how this could happened?

**Comment by brazenvoid** [comment] 2017-09-10 02:42
@angaratosurion I would suggest that you limit your search to gelbooru.com as it has most images for characters from anime/touhou category. Essentially limit it to one source.

I do not experience any crashes unless image count is over 120k for a tag from gelbooru.com. I would suggest the following steps to workaround the issue:

1. Select a safe download limit of 10k, 20k or 30k files. 
2. Once the download finishes, change the "Page" setting for the next batch. Like for the first one for 10k images would be 1 and the next ones would be multiples of 10. 
3. Restart the program.
4. Click the Download button to start the batch(s).
5. For the last batch download with less images than the selected limit, change the "Image Limit" value to that value.

You can do the above regiment for multiple batches but then you will have to keep the count values somewhere or keep looking them up through search to not accidentally add an impossible image limit or page value.

**Comment by angaratosurion** [comment] 2017-09-10 13:36
Also in gelborou it says that the image is not found. and tries every possible extension until eternity or it stops..
Also how you can tell it to not include files that are not images ?

**Comment by MasterPetrik** [comment] 2017-09-10 13:48
just enable https on gelbooru

**Comment by angaratosurion** [comment] 2017-09-10 14:00
thanks this it worked  the image not found error or taleast ebcame less :P

**Comment by brazenvoid** [comment] 2017-09-12 13:53
@angaratosurion when you encounter the infinite loop of image not found, just hit the Skip button. Whenever I encounter it, its always when it has already downloaded the whole page. The image it mentions as not found is not even listed in the page it is downloading.  

The skip button will make it proceed to the next page and for most cases you will never encounter that bug again for that particular batch.

If you leave the program as is, it will eventually crash anyways.

**Comment by Bionus** [comment] 2018-04-29 13:52
Dang, I totally missed this issue for some reason.

Thanks @MasterPetrik and @BarryMode for the list of old crash issues! I closed the ones that should have been, it should cleanup the issue list a little 👍

-----

> @Bionus, look something strange in .igl file:
> ![2017-09-06_234613 win7 mastercore](https://user-images.githubusercontent.com/22294259/30167637-b5773bc6-93ef-11e7-9a49-c93b75b051ea.png)
> 
> I guess that's the origin of the problem. For this tag even in all sources are ~5000 results images, and here is written that only on gelboru there are 28k of them. That's impossible. Any ideas, how this could happened?

Yes, the origin was that the tag count was wrongly detected in a bunch of sources. This has been fixed in a more recent commit/release (forgot which).

-----

> I do not experience any crashes unless image count is over 120k for a tag from gelbooru.com. I would suggest the following steps to workaround the issue:
> [...]

While annoying, this is a working workaround for this issue.
Good explanation! :+1:

-----

> Also in gelborou it says that the image is not found. and tries every possible extension until eternity or it stops..

Fixed in v5.5.1.

> Also how you can tell it to not include files that are not images ?

You'd have to define "not image". If that's videos & stuff, you can add ad `filetype` post-filter in v5.5.2.

-----

In any case, this is a duplicate of issue #618 ("crash on big downloads"), so I'll close this issue as well.

**Closed by Bionus** 2018-04-29 13:52 UTC
Labels: crash
