### ISSUE TITLE
Installer keeps nuking the portable installation and its settings

### ISSUE THREAD

**Issue by dsp2003** [Bionus/imgbrd-grabber#2402] opened 2021-07-02 23:10 UTC
**Bug description**

Every single time I'm updating this program, not only its installer doesn't give a damn about the installation in question being a portable, but also about the integrity of its settings.

**Steps to reproduce**

1. Install an "update" over the portable installation.
2. As a result, get all your settings, cookies, API hashes and user-agents **nuked**.
3. The program no longer starts until you'll repeat the steps to make it portable again.

**Expected behavior**

Recognize the portable installation and do not attempt to:
* blindly delete its settings without absolute necessity
* forcefully convert the installation into non-portable

**Comment by Bionus** [comment] 2021-07-05 12:46
Not sure what you mean by "nuked" or "integrity of its settings" here?

The installer is "stupid" and always install stuff in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`, whether it's a local installation or not. I don't really have any plan to change this at the moment TBH.

In those cases, nothing stops you from re-copying the stuff from there to your portable installation directory?
Although if you overwrite the `sites.txt` files, your custom sources will disappear (although your custom settings for those should remain since they're in separate files not included in the installer, and as such that it won't overwrite).

**Comment by Bionus** [comment] 2021-07-30 19:56
Closing as duplicate of #2055, but I see what you mean so I'll push a fix 👍

**Closed by Bionus** 2021-07-30 19:56 UTC
Labels: bug, build, duplicate, reproduced, windows
