### ISSUE TITLE
Tag blacklist ignored when supplying credentials to chan.sankakucomplex.com

### ISSUE THREAD

**Issue by LordOfLA** [Bionus/imgbrd-grabber#701] opened 2016-12-03 14:02 UTC
### What steps will reproduce the problem?

1. Set some blacklisted tags
2. Supply login details for chan.sankakucomplex

### What is the expected behavior? What do you get instead?

- Expected: Ignore images with blacklisted tags.
- Get: All images downloaded 

### What version of the program are you using? On what operating system?

5.0.0 Windows 10

**Comment by Bionus** [comment] 2016-12-04 23:56
Which blacklist are you referring to, exactly?

Grabber's blacklist, that can be set in the settings, or Sankaku's, that is set on your account settings on their website? (in My account > Settings > Tag Blacklist) If it's the latter, that's "semi-intended", in the way that it's up to Sankaku to return filtered results.

If they don't, the best solution in this case it to simply copy your blacklist in Grabber's settings. This way, it will also be applied to other sources.

**Comment by LordOfLA** [comment] 2016-12-05 14:11
Grabber's blacklist is being ignored. If I don't supply credentials grabber ignores images with blacklisted tags. If I supply credentials Grabber will just download everything irrespective of whether or not there are blacklisted tags attached to a file.

I have Sankaku set with the same blacklist minus a few but Sankaku isn't filtering either unless I browse manually but thats an issue for them.

**Comment by Bionus** [comment] 2017-02-05 12:16
Strange, I just tried (sorry for the delay) and could not reproduce this issue in v5.1.0. Which is pretty expected considering the authentication and blacklist filtering are completely dissociated in Grabber.

![image](https://cloud.githubusercontent.com/assets/882719/22626051/bba5e2d4-eba4-11e6-8443-e8dceb4d1f97.png)

![image](https://cloud.githubusercontent.com/assets/882719/22626054/bee3e2de-eba4-11e6-873d-abc192aa0b5a.png)

Is the "Get blacklisted" column properly set to "false" for these downloads?

**Comment by LordOfLA** [comment] 2017-02-06 09:48
Yes, it's set to false by default.

I just tried again however with 5.1.1 and it worked as expected. Not sure who fixed what but I'll keep an eye on it and see if it ignores the blacklist again at any point.

**Comment by Bionus** [comment] 2017-02-06 13:31
I'm closing the issue then.
Feel free to re-open here if the issue occurs again.

I believe it came from the fact that the Sankaku tag recognition was sometimes broken, leading to having images "without" tags during downloads. And without tags, no blacklist.

**Closed by Bionus** 2017-02-06 13:31 UTC
Labels: bug, source
