### ISSUE TITLE
Grabber constantly crashes when attempting to open any image.

### ISSUE THREAD

**Issue by Damocles-VI** [Bionus/imgbrd-grabber#2711] opened 2022-06-08 12:08 UTC
I have unintalled and reintalled multiple times, restarted my laptop. cleared data, still have this issue. Searching works fine but as soon as click on an image Grabber crashes, no matter what. Any help appreciated. 
Here's the log

[13:06:13.734][Warning] Javascript 'model.js' file not found for 'Booru-on-rails' in [C:/Program Files/Grabber/sites/Booru-on-rails/model.js](file:///C:/Program%20Files/Grabber/sites/Booru-on-rails/model.js) 
[13:06:14.029][Warning] Javascript 'model.js' file not found for 'Sankaku' in [C:/Program Files/Grabber/sites/Sankaku/model.js](file:///C:/Program%20Files/Grabber/sites/Sankaku/model.js) 
[13:06:14.409][Info] Start loading MD5 database 
[13:06:14.421][Info] MD5 database loaded (2098 entries) 
[13:06:14.462][Error] JavaScript helper file could not be opened 
[13:06:15.011][Info] Temp directory purged of 67/67 files (0 failed) 
[13:06:26.940][Info] Software version: 7.9.0.
[13:06:26.941][Info] Software CPU architecture: x86.
[13:06:26.942][Info] Computer CPU architecture: x86_64.
[13:06:26.943][Info] Qt CPU architecture: i386.
[13:06:26.943][Info] Computer platform: Windows 10 Version 2009.
[13:06:26.944][Info] Path: [C:/Program Files/Grabber](file:///C:/Program%20Files/Grabber)
[13:06:26.945][Info] Loading preferences from [C:/Users/redho/AppData/Local/Bionus/Grabber/settings.ini](file:///C:/Users/redho/AppData/Local/Bionus/Grabber/settings.ini)
[13:06:26.947][Info] Temporary path: [C:/Users/redho/AppData/Local/Temp\Grabber](file:///C:/Users/redho/AppData/Local/Temp/Grabber)
[13:06:26.948][Info] Sources found: 25
[13:06:26.948][Info] SSL libraries: OpenSSL 1.1.1o 3 May 2022
[13:06:27.022][Info] Setting language to 'English' ([C:\Program Files\Grabber\languages\English.qm](file:///C:/Program%20Files/Grabber/languages/English.qm))...
[13:06:27.030][Info] 25 sources found: anime-pictures.net (Anime pictures), api.rule34.xxx (Gelbooru (0.2)), api.twitter.com (Twitter), behoimi.org (Danbooru), danbooru.donmai.us (Danbooru (2.0)), derpibooru.org (Philomena), e-hentai.org (E-Hentai), e621.net (E621), exhentai.org (E-Hentai), gelbooru.com (Gelbooru (0.2)), hijiribe.donmai.us (Danbooru (2.0)), konachan.com (Moebooru), nhentai.net (NHentai), nijie.info (Nijie), rule34.paheal.net (Shimmie), safebooru.org (Gelbooru (0.2)), sonohara.donmai.us (Danbooru (2.0)), tentaclerape.net (Shimmie), wallhaven.cc (WallHaven), www.artstation.com (ArtStation), www.deviantart.com (DeviantArt), www.pixiv.net (Pixiv), www.reddit.com (Reddit), www.zerochan.net (Zerochan), yande.re (Moebooru)
[13:06:27.315][Warning] It seems that Imgbrd-Grabber hasn't shut down properly last time.
[13:06:30.856][Info] Loading 0 downloads
[13:06:30.905][Info] Updating checkboxes.
[13:06:34.011][Info] [gelbooru.com] Logging in...
[13:06:34.012][Info] [rule34.paheal.net] Logging in...
[13:06:37.476][Info] [rule34.paheal.net] Login finished: failure.
[13:06:49.912][Info] [gelbooru.com] Login finished: failure.
[13:06:49.983][Info] Updating checkboxes.
[13:06:50.012][Info] Saving sources...
[13:06:50.012][Info] Updating checkboxes.
[13:06:50.086][Info] Loading results...
[13:06:50.104][Info] [api.rule34.xxx][Html] Loading page https://rule34.xxx/index.php?page=post&s=list&tags=&pid=0
[13:06:50.105][Info] [api.rule34.xxx][Xml] Loading page https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&limit=800&pid=0&tags=
[13:06:50.107][Info] [e621.net][Html] Loading page https://e621.net/posts?limit=800&page=1&tags=&login=King_Anon_69&api_key=deadpool10009
[13:06:50.108][Info] [e621.net][Json] Loading page https://e621.net/posts.json?limit=800&page=1&tags=&login=King_Anon_69&api_key=deadpool10009
[13:06:50.110][Info] [gelbooru.com][Html] Loading page https://gelbooru.com/index.php?page=post&s=list&tags=&pid=0
[13:06:50.111][Info] [gelbooru.com][Xml] Loading page https://gelbooru.com/index.php?page=dapi&s=post&q=index&limit=800&pid=0&tags=
[13:06:50.112][Info] [rule34.paheal.net][Html] Loading page http://rule34.paheal.net/post/list/1
[13:06:50.115][Info] Monitoring starting
[13:06:50.224][Info] Monitoring tick
[13:06:50.225][Info] Monitoring finished
[13:06:50.973][Info] [gelbooru.com][Html] Receiving page https://gelbooru.com/index.php?page=post&s=list&tags=&pid=0
[13:06:50.974][Info] [gelbooru.com][Html] Redirecting page https://gelbooru.com/index.php?page=post&s=list&tags=&pid=0 to https://gelbooru.com/index.php?page=post&s=list&tags=all
[13:06:50.976][Info] [gelbooru.com][Html] Loading page https://gelbooru.com/index.php?page=post&s=list&tags=all
[13:06:57.408][Info] [e621.net][Json] Receiving page https://e621.net/posts.json?limit=800&page=1&tags=&login=King_Anon_69&api_key=deadpool10009
[13:06:57.462][Warning] [e621.net][Json] SessionLoader::AuthenticationFailure
[13:06:57.463][Warning] [e621.net] Loading using Json failed. Retry using Html.
[13:07:01.369][Info] [e621.net][Html] Receiving page https://e621.net/posts?limit=800&page=1&tags=&login=King_Anon_69&api_key=deadpool10009
[13:07:01.431][Info] [e621.net][Html] Parsed page https://e621.net/posts?limit=800&page=1&tags=&login=King_Anon_69&api_key=deadpool10009: 0 images (0), 0 tags (0), -1 total (-1), -1 pages (-1)
[13:07:10.136][Info] [rule34.paheal.net][Html] Receiving page http://rule34.paheal.net/post/list/1
[13:07:10.415][Info] [rule34.paheal.net][Html] Parsed page http://rule34.paheal.net/post/list/1: 70 images (70), 10 tags (10), -1 total (400000), 500 pages (500)

**Comment by Bionus** [comment] 2022-06-08 13:40
Duplicate of #2711

**Closed by Bionus** 2022-06-08 13:40 UTC

**Comment by Damocles-VI** [comment] 2022-06-08 22:47
i'm a bit confused as how this can be duplicate post when i only made one? Either way a solution would be muvh appreciated.

**Comment by Bionus** [comment] 2022-06-08 23:16
> i'm a bit confused as how this can be duplicate post when i only made one? Either way a solution would be much appreciated.

Isn't this the same as #2710, created at the same time?
