### ISSUE TITLE
Crash when mass downloading

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#820] opened 2017-02-28 19:25 UTC
### What steps will reproduce the problem?

Download every image on every booru

### What is the expected behavior? What do you get instead?

not crash

### What version of the program are you using? On what operating system?

v5.2.2 windows

### Please provide any additional information below

Had to upload my log to this site since half the internet is down from the amazon outage,

https://u.nya.is/ebpgnm.zip

**Comment by MasterPetrik** [comment] 2017-02-28 21:06
> Download every image on every booru
> expected not crash

Heh, what could go wrong? Right? 
I don't really think that there are exist some downloader, who can do it.

P.S.
haw many images of 14 000 000 are you downloaded?

**Comment by brodycas3** [comment] 2017-02-28 22:20
I got 22,415 images downloaded.

**Comment by brodycas3** [comment] 2017-02-28 22:21
well you could say. This was sorta a test of the new system.

**Comment by MasterPetrik** [comment] 2017-02-28 23:10
Not bad! I wonder, how your IP still not bannd on boorus...

**Comment by brodycas3** [comment] 2017-02-28 23:12
lol

**Comment by brodycas3** [comment] 2017-03-01 22:21
@Bionus Wanna check this out for me?

**Comment by MasterPetrik** [comment] 2017-03-03 23:02
I think that this issue related to https://github.com/Bionus/imgbrd-grabber/issues/618

**Comment by brodycas3** [comment] 2017-03-04 22:11
Here is crash number two,  
[Crash two.zip](https://github.com/Bionus/imgbrd-grabber/files/818967/Crash.two.zip)

**Comment by MasterPetrik** [comment] 2017-03-05 03:04
I think that this issue may be connected with https://github.com/Bionus/imgbrd-grabber/issues/547

**Comment by Bionus** [comment] 2017-06-24 21:10
The crash occured when downloading a 145MB file (**NFSW**: [file](http://atfbooru.ninja/data/3335a08cad0f4fffe76311bfb588fcab.mp4) & [page](http://atfbooru.ninja/posts/164550)), so the crash is more than likely to be caused by the size of said file.

See issue #954 and #963 for follow-up, I'll be closing this issue.

**Closed by Bionus** 2017-06-24 21:10 UTC
Labels: crash
