### ISSUE TITLE
original images are still downloaded even after un-checking download original images

### ISSUE THREAD

**Issue by maxman2103** [Bionus/imgbrd-grabber#2067] opened 2020-07-30 09:28 UTC
**Bug description**
even after un-checking download original images i am still downloading original images.

**Steps to reproduce**

i was trying download from sankaku using the tag ( infinite_stratos ~scan ~official_art )

grabber version latest 7.3.1

**Comment by Bionus** [comment] 2020-07-30 16:42
Hello

Sankaku has been deprecated for a while.
Are you able to reproduce this issue with another source?

**Comment by maxman2103** [comment] 2020-07-30 18:39
> Hello
> 
> Sankaku has been deprecated for a while.
> Are you able to reproduce this issue with another source?

no when i used Gelbooru it worked fine

**Comment by Bionus** [comment] 2020-08-01 07:49
Alright, then I'll close the issue since Sankaku isn't supported anymore.
Feel free to re-open if you can reproduce on another source. 😄

**Closed by Bionus** 2020-08-01 07:49 UTC

**Comment by maxman2103** [comment] 2020-08-02 06:21
> Alright, then I'll close the issue since Sankaku isn't supported anymore.
> Feel free to re-open if you can reproduce on another source. 😄

OK thanks for the help.... my only question would be why Sankaku  is so complicated when it comes to download from the site. like 1000 download limit or batch download bans ur ip stuff like this ( i am not a programmer so i dont have knowledge in this stuff)
