### ISSUE TITLE
Sankaku link expired error (old version 6.0.6)

### ISSUE THREAD

**Issue by VanishingBlaze** [Bionus/imgbrd-grabber#2333] opened 2021-04-14 06:37 UTC
When trying to download some images from sankaku i get images downloaded that say error link expired. i can see the image in the search results but when i check the info the link is wrong. any have any idea what to do to fix it?

**Comment by yami-no-tusbas** [comment] 2021-04-14 09:06
Wich Sankaku, do  you have logs ? As far as I remember it's been a while that sankaku is not supported anymore, so it won't be fixed. At least not by Bionus.

**Comment by VanishingBlaze** [comment] 2021-04-14 09:25
chan.sankakucomplex , idk where to look for logs at

**Comment by yami-no-tusbas** [comment] 2021-04-14 17:45
Log should be in "C:\Users\<UserName>\AppData\Local\Bionus\Grabber\main.log" but #1888 seems to indicate it'll never made working again.

**Comment by VanishingBlaze** [comment] 2021-04-14 20:18
well it does work for some images and it doesn't work on others. i think it may have something to do with that credentials access, not to sure. by chance is there any downloader for chan.sankakucomplex out there that isn't grabber?

**Comment by Bionus** [comment] 2021-04-19 17:09
Yes, Sankaku isn't supported, and v6.0.6 even less 😅

The latest version that supported Sankaku is [v7.1.1](https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.1.1) so you can always try using that. I remember fixing something similar one or two years ago.

If it works when browsing but not downloading, make sure you're not having too many simultaneous downloads as well.

**Closed by Bionus** 2021-04-19 17:09 UTC

**Comment by Desk5103** [comment] 2021-04-25 06:12
I was able to download content after setting Sources to "json" (in sankaku options panel)

**Comment by Desk5103** [comment] 2021-04-25 06:15
i was able to download content after setting Source to json (in sankaku options panel)
![image](https://user-images.githubusercontent.com/72625865/115982808-6e202580-a5bb-11eb-8ae1-d49729a89045.png)

it downloads now
![image](https://user-images.githubusercontent.com/72625865/115982822-855f1300-a5bb-11eb-97e8-70c709b07cfe.png)

and ahhh for some reason I have a feeling this will download thumbnails for some posts when downloading so keep your eyes open (i havent encountered something like this by using json as source its just a feeling)

**Comment by VanishingBlaze** [comment] 2021-04-25 06:27
What version are you using? when i set it to json i can't get images to show up

**Comment by Desk5103** [comment] 2021-04-25 06:38
@VanishingBlaze 
![image](https://user-images.githubusercontent.com/72625865/115983482-f05e1900-a5be-11eb-94c8-42d88a60b530.png)

**Comment by VanishingBlaze** [comment] 2021-04-25 06:48
ok i installed that version, but images still don't show up in the search for me

**Comment by Desk5103** [comment] 2021-04-25 07:42
i just found out that my sankaku folder (in sites folder) is bit different from the one that was posted by "yami-no-tusbas " in #1888
here sankaku.zip - [https://mega.nz/file/jK5ARI7K#nVUlARbPcllu7jP5R9H430NVHKENPZwingO-3t50Pos](url)

**Comment by VanishingBlaze** [comment] 2021-04-25 07:58
i clicked the mega link, nothing showed up

**Comment by Desk5103** [comment] 2021-04-25 08:07
ehhh for some reason u gotta select the link and copy paste it in the browser 
![image](https://user-images.githubusercontent.com/72625865/115985873-6e282180-a5cb-11eb-9116-2654304236ca.png)

**Comment by Desk5103** [comment] 2021-04-25 08:09
nvm just the click the link now in the comment. fixed it

**Comment by VanishingBlaze** [comment] 2021-04-25 08:32
ty. i got the file now. where does it go?

**Comment by VanishingBlaze** [comment] 2021-04-25 08:36
nvm, figured it out, but the images im trying to get don't show up now, i guess its a tagging issue?

**Comment by Desk5103** [comment] 2021-04-25 08:36
what are u trying to search?

**Comment by VanishingBlaze** [comment] 2021-04-25 08:42
an example would be a tag like goat-chan and when searched no results found but on the website there's 121 images

**Comment by Desk5103** [comment] 2021-04-25 09:20
ahhhh this is happening because login isnt working when using json api as i can see (even tho it says success in options tab, it always shows success for anything u type in password and username)
ill see if i can do something

**Comment by VanishingBlaze** [comment] 2021-04-25 09:25
thanks, I appreciate it. I hope you can find a solution for this

**Comment by Desk5103** [comment] 2021-04-25 14:24
ehhh so found a way but theres no way to edit the source files (sankaku folder) to get it to work.
so im gonna show how to get it to work manually.

so in short u have to make a header value with the "access_token" which u can get by using your sankau accounts username and password


**first u need to get your access_token**

1. go to [https://reqbin.com/z6vx4vsp](https://reqbin.com/z6vx4vsp) where i have already set up the json body and the url 
2. go to tab call "raw" that is below the url  
![image](https://user-images.githubusercontent.com/72625865/115996301-5fa62e00-a5fc-11eb-9949-66b13f60a8a8.png)
3. change "ero103@live.jp" to your sankaku username and "killer103" to your password
4. then press blue send button
5. after that u will get the response text at the right side of the screen 
6. copy the text which belongs to "access_token" key 
![image](https://user-images.githubusercontent.com/72625865/115996447-ed821900-a5fc-11eb-9cae-d96c9f211360.png)

**now u have to create a new header to your sankaku source**

1. open "Grabber" then go to "Sources" panel
2. press "Options" in front of the "chan.sankakucomplex.com" source
3. then go to "Headers" tab press "Add"
![image](https://user-images.githubusercontent.com/72625865/115996961-f5db5380-a5fe-11eb-9cd3-28bde946c7bd.png)
4. after adding the empty row type "Authorization" in "Name" column
5. then for the "Value" column type "Bearer " (u need to put a white space after writing "Bearer" ) then paste the access token u copied before
![image](https://user-images.githubusercontent.com/72625865/115997171-d09b1500-a5ff-11eb-9fc4-81d472f115a4.png)
6. then press "Confirm" and "Ok"

**Now you're able to search whatever u want**

**Comment by Desk5103** [comment] 2021-04-25 14:36
and btw it seems u dont have to put an interval between downloads now? im not sure tho

**Comment by VanishingBlaze** [comment] 2021-04-25 19:52
Oh wow, I saw somehow able to do that. THANK YOU! You are a genius

**Comment by VanishingBlaze** [comment] 2021-04-25 21:04
update. the download seems slower, but thats ok when if work, so was downloading stuff everything was working fine, but at a half way point it started downloading the error images again

**Comment by Desk5103** [comment] 2021-04-25 21:08
what image was it that downloaded the error image like do u know whcih md5 or the id? can u send it?

**Comment by VanishingBlaze** [comment] 2021-04-25 22:34
i exited out of it so i'll have to tried to get the log again. it may take an hour or 2. you want the text from the log right?

**Comment by VanishingBlaze** [comment] 2021-04-25 23:55
Ok i'll keep the log open incase you need some info from it. the test i did was the goat-chan tag that is 121 images on site, 2 of which are blocked but i know that. so the grabber grabs 119 link. 1-30 download normally, but 31-119 download as link expired image from sankaku

**Comment by Desk5103** [comment] 2021-04-26 03:43
hmmm weird can u show the log where image started failing to download (downloading the link expired link image),
or its fine if u tell me the md5 of one of the images which failed to download

**Comment by VanishingBlaze** [comment] 2021-04-26 03:52
what's an md5?

**Comment by Desk5103** [comment] 2021-04-26 03:58
its an unique identifier for a post 
well if u dont know that probably u dont have it anywhere saved (i keep md5 as the file name when downloading)

ig u have to send the log so i can reproduce the issue

**Comment by VanishingBlaze** [comment] 2021-04-26 04:42
you want me to send you the txt file?

**Comment by Desk5103** [comment] 2021-04-26 04:42
yea

**Comment by VanishingBlaze** [comment] 2021-04-26 04:47
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6374358/main.log)
ok, i hope that's right

**Comment by Desk5103** [comment] 2021-04-26 06:26
ah ok found it, i think ure not using the json as the source right?
https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826265346

**Comment by VanishingBlaze** [comment] 2021-04-26 06:38
currently my source 1 is json so i think it was like that when i was testing the download

**Comment by Desk5103** [comment] 2021-04-26 06:47
hmmm can u search "md5:ed8f9b2f962a64b96b764a38590e3326" download only that image tell me if it downloads successfully or not.

**Comment by VanishingBlaze** [comment] 2021-04-26 06:54
ok i did that. i did successfully downloaded that image

**Comment by Desk5103** [comment] 2021-04-26 06:56
eh wut im not sure but it seems u had html as your source when you were downloading "goat-chan" try downloading now there wont be a problem

**Comment by Desk5103** [comment] 2021-04-26 06:57
> update. the download seems slower, but thats ok when if work, so was downloading stuff everything was working fine, but at a half way point it started downloading the error images again

about the download speed, u can now download 10 images at the same time without intervals (i did download them without any problems). so u should try that.

**Set download intervals to 0 and simultaneous downloads to 10**
![image](https://user-images.githubusercontent.com/72625865/116038743-76459700-a687-11eb-8489-dbf104a68e20.png)

**Set simultaneous downloads to 10 in options menu**
![image](https://user-images.githubusercontent.com/72625865/116039052-dccab500-a687-11eb-8fd1-616620ccd706.png)

**u can now download 10 images at the same time without intervals**
![image](https://user-images.githubusercontent.com/72625865/116039332-3b902e80-a688-11eb-86eb-8240bd7e1cc1.png)

**Comment by VanishingBlaze** [comment] 2021-04-26 07:01
ok, i'll try the batch again, will update on it

**Comment by VanishingBlaze** [comment] 2021-04-26 07:03
i also copied those settings, here's hoping

**Comment by VanishingBlaze** [comment] 2021-04-26 07:41
ok. its downloaded the 119 this time. 5 need to be redownloaded, but this time it prompted me to do so and worked. so what was causing the problem?

**Comment by Desk5103** [comment] 2021-04-26 07:52
hmmm i have no idea, only way u can get those error images to download is to set source to html.

**Comment by VanishingBlaze** [comment] 2021-04-26 07:58
hmm, odd. well i'm trying another tag now. hopefully it succeeds too. would using json for rule34 help as well? been having a problem with that

**Comment by Desk5103** [comment] 2021-04-26 08:33
im not sure with rule34 i dont use anything other than sankaku u should create a new issue for that

**Comment by VanishingBlaze** [comment] 2021-04-26 09:03
alright, well thank you. this helped a lot. i also tried another tag. got a few expired links images, but now i think its just a time thing and not failure to find the link. after the 1st run i'll delete the expired images and do a second run. i think my 1 of my problems was the not having multiple downloads enabled. it just seems slow downloading atm with about 160 KB/s

**Comment by Desk5103** [comment] 2021-04-26 10:04
ohhhh now i get wut's causing this i will fix this right away (ig wut im going to do will fix it probably)

**Comment by Desk5103** [comment] 2021-04-26 11:09
here the updated [one](https://mega.nz/file/CPw2jY4S#OdcVj79VElqwnT12Dc6AqvgPBHrGHBvbfxNFThENFco)

basically i added detail property to the javascript file 
```javascript
details: {
    url: function (id, md5) {
        return "https://capi-v2.sankakucomplex.com/posts/" + id;
    },
    parse: function (src) {
        var data = JSON.parse(src);
        var tags = data["tags"].map(function (tag) {
            return {
                id:tag["id"],
                name: tag["name_en"],
                count: tag["count"],
                typeId: tag["type"],
            };
        });
        return {
            tags: tags,
            imageUrl: data["file_url"],
            createdAt: data["created_at"]["s"],
        };
    },
}
```

afaik this will get call every moment where grabber downloads an image so it will refresh the download link right before downloading
before, image url will expire after a short amount of time and grabber wont update it cause the javascript file didnt have any information about how to refresh it so it just downloads a "link expired" image returned from sankaku

**Comment by yami-no-tusbas** [comment] 2021-04-26 12:46
> 
> 
> ehhh so found a way but theres no way to edit the source files (sankaku folder) to get it to work.
> so im gonna show how to get it to work manually.
> 
> so in short u have to make a header value with the "access_token" which u can get by using your sankau accounts username and password
> 
> **first u need to get your access_token**
> 
>     1. go to https://reqbin.com/z6vx4vsp where i have already set up the json body and the url
> 
>     2. go to "Content" tab that is below the url
>        ![image](https://user-images.githubusercontent.com/72625865/115997619-5d929e00-a601-11eb-85af-fd28e7ef8014.png)
> 
>     3. change "[ero103@live.jp](mailto:ero103@live.jp)" to your sankaku username and "killer103" to your password
> 
>     4. then press blue send button
> 
>     5. after that u will get the response text at the right side of the screen
> 
>     6. copy the text which belongs to "access_token" key
>        ![image](https://user-images.githubusercontent.com/72625865/115996447-ed821900-a5fc-11eb-9cae-d96c9f211360.png)
> 
> 
> **now u have to create a new header to your sankaku source**
> 
>     1. open "Grabber" then go to "Sources" panel
> 
>     2. press "Options" in front of the "chan.sankakucomplex.com" source
> 
>     3. then go to "Headers" tab press "Add"
>        ![image](https://user-images.githubusercontent.com/72625865/115996961-f5db5380-a5fe-11eb-9cd3-28bde946c7bd.png)
> 
>     4. after adding the empty row type "Authorization" in "Name" column
> 
>     5. then for the "Value" column type "Bearer " (u need to put a white space after writing "Bearer" ) then paste the access token u copied before
>        ![image](https://user-images.githubusercontent.com/72625865/115997171-d09b1500-a5ff-11eb-9fc4-81d472f115a4.png)
> 
>     6. then press "Confirm" and "Ok"
> 
> 
> **Now you're able to search whatever u want**

He buddy, could you at least hide my personnal data from your screenshot ? and you quote, I have changed my password but it's not very good that you gave it freely without my consent.

**Comment by Desk5103** [comment] 2021-04-26 13:09
oh god damn I thought it was just a dummy account someone created because it was in there at the very beginning where I started using sankaku in grabber most probably because it was in sankaku.zip u shared
I have edited my comment
I'm extremely sorry for this ;-;

**Comment by VanishingBlaze** [comment] 2021-04-26 20:39
> **here the updated [sankaku.zip](https://mega.nz/file/CPw2jY4S#OdcVj79VElqwnT12Dc6AqvgPBHrGHBvbfxNFThENFco)**
> 
> basically i added detail property to the javascript file
> 
> ```js
> details: {
>     url: function (id, md5) {
>         return "https://capi-v2.sankakucomplex.com/posts/" + id;
>     },
>     parse: function (src) {
>         var data = JSON.parse(src);
>         var tags = data["tags"].map(function (tag) {
>             return {
>                 id:tag["id"],
>                 name: tag["name_en"],
>                 count: tag["count"],
>                 typeId: tag["type"],
>             };
>         });
>         return {
>             tags: tags,
>             imageUrl: data["file_url"],
>             createdAt: data["created_at"]["s"],
>         };
>     },
> }
> ```
> 
> afaik this will get called every moment where grabber downloads an image so it will refresh the download link right before downloading
> before, image url will expire after a short amount of time and grabber wont update it cause the javascript file didnt have any information about how to refresh it so it just downloads a "link expired" image returned from sankaku

so i just need to drag and drop and everything should be fine?

**Comment by Desk5103** [comment] 2021-04-26 20:44
yep just download the [sankaku.zip](https://mega.nz/file/CPw2jY4S#OdcVj79VElqwnT12Dc6AqvgPBHrGHBvbfxNFThENFco) and replace it in sites folder

**Comment by VanishingBlaze** [comment] 2021-04-26 20:50
alright, thank you. hopefully everything is smooth sailing now

**Comment by VanishingBlaze** [comment] 2021-04-28 04:34
seems like the images aren't showing up now. any suggestions?

**Comment by Desk5103** [comment] 2021-04-28 04:37
html method is working now u can switch back
(images are not showing cause your authorization token is expired u can renew it by the method i showed previously but i recommend switching to html cause json is very buggy and unstable)

**Comment by VanishingBlaze** [comment] 2021-04-28 04:55
i also switched to my account. that should be fine?

**Comment by Desk5103** [comment] 2021-04-28 04:57
yea

**Comment by VanishingBlaze** [comment] 2021-04-28 05:00
Cool. When did the html get fixed?

**Comment by Desk5103** [comment] 2021-04-28 05:02
[like eight hours ago i think](https://github.com/Bionus/imgbrd-grabber/issues/2348#issuecomment-827933219)

**Comment by VanishingBlaze** [comment] 2021-04-28 05:08
Well that's good. Hoping it stays flowing

**Comment by DarknestOne** [comment] 2021-04-29 08:24
@Desk5103 hey thank you for your amazing fix! Everything worked fine until a few hours ago. Now HTML downloads "Link expired" and json is not downloading, returning "authorization required". I've tried updating my token, but looks like it expires right away

**Comment by Desk5103** [comment] 2021-04-29 08:29
@DarknestOne 
u sure u didnt miss anything [here](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826333230)?
u sure u add "Bearer" and a whitespace before your auth token?

**Comment by DarknestOne** [comment] 2021-04-29 08:31
yes, I did everything as peer instruction, and been downloading for a few days using bearer and my token. Got around 200k images, and then it started downloading "link expired". After that when I changed tokens it would not download and even failed to search. Guess third (forth?) time's the charm

**Comment by Desk5103** [comment] 2021-04-29 08:40
hmm sankaku downloading expired link happend to me too but i cancelled the download process and restarted it then it worked fine(i deleted the "link expired" images from download directory before restarting)

and failing to search happened too or it was more like it dosent return anything not even a error just stuck at "Loading page {url}", i restarted grabber and without searching anything straightly started the download process and it worked.

**Comment by DarknestOne** [comment] 2021-04-29 08:42
Well it seems like it's downloading again now, so perhaps it was a false alarm from my side.

**Comment by Desk5103** [comment] 2021-04-29 09:30
@DarknestOne ah btw to prevent grabber from downloading "link expired image" use this [sankaku](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826748490) (put it in the sites folder)

**Comment by DarknestOne** [comment] 2021-04-29 09:31
yup, already did, thank you!

**Comment by DarknestOne** [comment] 2021-04-29 09:34
UPD: I think I see the problem. "premium only" pages return this error. At lease I think they're premium only
https://capi-v2.sankakucomplex.com/posts/19959568 as an example

**Comment by Desk5103** [comment] 2021-04-29 09:41
> UPD: I think I see the problem. "premium only" pages return this error. At lease I think they're premium only
> https://capi-v2.sankakucomplex.com/posts/19959568 as an example

that post is actually deleted 
[https://chan.sankakucomplex.com/post/show/19959568](https://chan.sankakucomplex.com/post/show/19959568)
so theres no link to download anyway (ehh when json link returns empty(null) link to a post it tries to create a link from taking the preview link which returns a expired link so grabber downloads the "expired link image")

**Comment by DarknestOne** [comment] 2021-04-29 09:43
yes but the problem is in my case grabber just "hangs" on this post. And if there's 10 deleted posts in queue - it hangs completely until I press skip. I guess I'd rather it download "expired link" in that case tbh, cause now I have to babysit the downloads
