### ISSUE TITLE
Conditional filenames with illegal characters

### ISSUE THREAD

**Issue by fusedragon** [Bionus/imgbrd-grabber#2347] opened 2021-04-24 07:51 UTC
**Bug description**

Conditional file naming does not work if tag contains illegal characters in Windows e.g. : ? "

**Steps to reproduce**

File naming is set as %artist:spaces%/%websitename% %date:format=yyyy.MM.dd% <"re:zero_kara_hajimeru_isekai_seikatsu"?re-zero:%copyright%> %character% %artist% %id%.%ext%

**Expected behavior**

Image should be saved as "re-zero" as copyright tag but is saved as "re_zero_kara_hajimeru_isekai_seikatsu" instead. Using "re_zero_kara_hajimeru_isekai_seikatsu" in conditional file naming gives the same result.

Also tried on tags containing other illegal characters and got similar results.

---

An unrelated question but is there a way to add ratings into default file naming to determine folder name? Basically I would like to save all "questionable" and "explicit" images in a separate folder, but also set up conditionals to rename certain tags e.g. "kaguya-sama_wa_kokurasetai_~tensai-tachi_no_renai_zunousen~" to "kaguya-sama".

Edit// Never mind, had the general idea but couldn't get it to work earlier but figured it out. In case anyone's interested: %artist:spaces%/<rating:explicit|rating:questionable?NSFW:%nothing%>/%websitename% %date:format=yyyy.MM.dd% %copyright% %character% %artist% %id%.%ext%

On that note maybe good to have more examples in the filename documentation for people to refer to or just copy-paste.

**System information**

- OS: Windows 10
- Grabber version: 7.5.1

**Comment by Bionus** [comment] 2021-04-28 13:54
Indeed, that was caused by the `:` causing it to be treated as a meta-tag search (like `rating:safe`).
I just pushed a fix.

**Closed** 2021-07-05 14:29 UTC
Labels: bug, reproduced
