### ISSUE TITLE
[Anime-pictures] 'Open in browser' redirects to wrong link

### ISSUE THREAD

**Issue by adem4ik** [Bionus/imgbrd-grabber#2726] opened 2022-06-24 10:32 UTC
**Bug description**

 'Open in browser' redirects to link like https://anime-pictures.net/pictures/view_post/759056?lang=en&type=json

**Steps to reproduce**

1. Search for something on Anime-pictures
2. Perform right mouse click on any result
3. Select 'Open in browser'

**Expected behavior**

A valid image page is opened in the browser. i.e. https://anime-pictures.net/pictures/view_post/759056?lang=en

**Context**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/4707112/175516701-085537e5-e2ca-46fb-9cc4-1d4b13aba947.png)

**System information**

- OS: Windows 10
- Grabber version: 7.9.0

**Additional context**

The problem comes from `&type=json` inside the url. But if you delete it from model.ts, tags won't be shown in the Image window.
       https://github.com/Bionus/imgbrd-grabber/blob/812ce2d2bd77ac91a0edd788eefdd7b5ef15fc7c/src/sites/Anime%20pictures/model.ts#L155
![image](https://user-images.githubusercontent.com/4707112/175517034-0a4d65fd-3c60-40c3-8bb4-19a753d90b93.png)

**Comment by Bionus** [comment] 2022-06-24 19:37
I know that this is a different source, but I'll close this as a duplicate of #2716 since it's the same root issue.

**Closed by Bionus** 2022-06-24 19:37 UTC
Labels: duplicate
