### ISSUE TITLE
error with e621 (fetch error, site returned Forbidden (201)

### ISSUE THREAD

**Issue by gatekeepergate** [Bionus/imgbrd-grabber#1931] opened 2020-04-10 11:44 UTC
this may also apply with some other sources

code snippet:
```
[04:41:23.771][Info] Saving sources...
[04:41:23.771][Info] Updating checkboxes.
[04:41:25.568][Info] Loading results...
[04:41:25.570][Info] [e621.net][Html] Loading page https://e621.net/post/index?limit=20&page=1&typed_tags=true&tags=toriel
[04:41:25.570][Info] [e621.net][Xml] Loading page https://e621.net/post/index.xml?limit=20&page=1&typed_tags=true&tags=toriel
[04:41:25.663][Info] [e621.net][Html] Receiving page https://e621.net/post/index?limit=20&page=1&typed_tags=true&tags=toriel
[04:41:25.664][Info] [e621.net][Html] Redirecting page https://e621.net/post/index?limit=20&page=1&typed_tags=true&tags=toriel to https://e621.net/posts?tags=toriel&page=1
[04:41:25.665][Info] [e621.net][Html] Loading page https://e621.net/posts?tags=toriel&page=1
[04:41:26.262][Info] [e621.net][Xml] Receiving page https://e621.net/post/index.xml?limit=20&page=1&typed_tags=true&tags=toriel
[04:41:26.263][Error] [e621.net][Xml] Loading error: Error transferring https://e621.net/post/index.xml?limit=20&page=1&typed_tags=true&tags=toriel - server replied: Forbidden (201)
[04:41:26.263][Warning] [e621.net] Loading using Xml failed. Retry using Json.
[04:41:26.264][Info] [e621.net][Json] Loading page https://e621.net/post/index.json?limit=20&page=1&typed_tags=true&tags=toriel
[04:41:27.188][Info] [e621.net][Html] Receiving page https://e621.net/posts?tags=toriel&page=1
[04:41:27.192][Info] [e621.net][Html] Parsed page https://e621.net/posts?tags=toriel&page=1: 0 images (0), 0 tags (0), -1 total (-1), -1 pages (-1)
[04:41:27.461][Info] [e621.net][Json] Receiving page https://e621.net/post/index.json?limit=20&page=1&typed_tags=true&tags=toriel
[04:41:27.462][Error] [e621.net][Json] Loading error: Error transferring https://e621.net/post/index.json?limit=20&page=1&typed_tags=true&tags=toriel - server replied: Forbidden (201)
[04:41:27.463][Warning] [e621.net] Loading using Json failed. Retry using Html.
[04:41:27.463][Info] [e621.net][Html] Loading page https://e621.net/posts?tags=toriel&page=1
[04:41:28.406][Info] [e621.net][Html] Receiving page https://e621.net/posts?tags=toriel&page=1
[04:41:28.409][Info] [e621.net][Html] Parsed page https://e621.net/posts?tags=toriel&page=1: 0 images (0), 0 tags (0), -1 total (-1), -1 pages (-1)
```

"toriel" here was just a test word to see if the program was working properly, testing with other words has the same result regardless

**Comment by Bionus** [comment] 2020-04-10 11:50
Marking as duplicate of issue #1895.
Please post there if you have additional questions. FYI, e621 is already fixed in [nightly releases](https://github.com/Bionus/imgbrd-grabber/releases/nightly) 👍

**Closed by Bionus** 2020-04-10 11:50 UTC
Labels: duplicate
