### ISSUE TITLE
[Nightly] grabber:inMd5List filter stopped working

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1961] opened 2020-05-12 23:21 UTC
**Bug description**

I use this filter in negation mode globally but somehow it is now matching a very limited number of files. Tags that I have had searched and downloaded in bulk are now showing all of the downloaded files again.

Meaning, suppose say you have about 20 files on a page in your md5 list but the filter will only filter or grab 5 or so. I have not been able to decipher why only the few get matched fine.

I am basing this on the observation that existing files that don't get filtered, show "MD5 already exits" or "Already exists" on the save button when previewed. 

I have tried running md5 fixer to no avail.

**Steps to reproduce**

1. Search something on Gelbooru / r34 xxx / r34 paheal
2. Download the page or many files
3. Add the post filter -grabber:inMd5List
4. Now you will still see some of the earlier downloaded files in the page
5. Opening preview will show either "MD5 already exits" or "Already exists"

**System information**

- OS: Windows 10 1909
- Grabber version: Nightly c9a1bab4

**Comment by Bionus** [comment] 2020-05-14 19:15
I just tried reproducing to no avail:

1. Selected the 3 sources you mentioned
2. Download the first page of some random tag there
3. Search the same tag with the `-grabber:inMd5List` post-filter
4. "All images filtered"

What setting do you use for the "if a file already exists globally" setting? (and "keep deleted")
Did you change any specific option for those sources? (especially in the "Sources" tab)

Did this change happen recently?

**Comment by brazenvoid** [comment] 2020-05-14 19:19
- Setting "if a file already exists globally": **Don't Save**
- Setting "keep deleted": **Checked**
- Did you change any specific option for those sources? **R34 XXX has login information**
- Did this change happen recently? **Yes**

**Comment by brazenvoid** [comment] 2020-05-14 19:28
Now that I have checked it matches no file when used in non-negation.

**Comment by brazenvoid** [comment] 2020-05-14 19:35
Oh and I only use it for animated files. Could that be an issue?

**Comment by Bionus** [comment] 2020-05-14 19:42
Could it be that those files are in your MD5 list but has been deleted from your disk?
Because there was indeed a change recently and maybe some behavior changed by accident.

**Comment by brazenvoid** [comment] 2020-05-14 19:44
Yes they are no longer on disk, at least not with same names.

**Comment by Bionus** [comment] 2020-05-14 19:46
Alright thanks.
Then I found the issue, I'll push a fix ASAP :+1:

**Comment by Bionus** [comment] 2020-05-14 22:38
Well it took longer than I thought because I had to re-write a big part of this.
I should have also fixed one or two other bugs related to the MD5 list at the same time 🤔 

For example, if you set "when already exists globally, save" (or move/copy) and "keep deleted files in the list" at the same time, if you try to download a file that is already in the list but was deleted, it wouldn't follow the "save" rule and would rather ignore the image. You wouldn't be able to see it in the image window either.

While it doesn't really make sense to keep deleted files in the list if you save duplicates anyway, that was a weird behavior showing a few weaknesses in this system, I'll change a few things in the next few days to correct the remaining problems.

**Comment by brazenvoid** [comment] 2020-05-29 23:26
@Bionus The current logic is only working for images. Existing animated and video files are still being shown.

**Comment by brazenvoid** [comment] 2020-05-29 23:54
Sorry, its working fine in the latest nightly. Fabulous work on the favorites pane though!

**Closed** 2020-06-03 13:32 UTC
Labels: bug, reproduced
