### ISSUE TITLE
%filename% not working on Danbooru and replaced by the image's MD5

### ISSUE THREAD

**Issue by Vorch** [Bionus/imgbrd-grabber#1239] opened 2018-04-08 05:51 UTC
### What steps will reproduce the problem?
Any sort of image save

### What is the expected behavior? What do you get instead?
To get the nice little "Fake" filename you would get if you downloaded the image from Danbooru, instead all i get is a bunch of untidy numbers and letters

### How often does this problem occur? On which sources?
Every time since today, currently only using Danbooru

### What version of the program are you using? On what operating system?
5.5.2

**Comment by Bionus** [comment] 2018-04-11 18:19
Most likely caused by an change in the page.

* Old format: `__original_drawn_by_akashi_kaikyou__b8ea486b9229aa42ab32a8a6f122a8dc.jpg`
* Current (MD5): `b8ea486b9229aa42ab32a8a6f122a8dc`
* New format: `original drawn by akashi kaikyou - b8ea486b9229aa42ab32a8a6f122a8dc.jpg`

I'll see what I can do to update the filename detection.

**Comment by Vorch** [comment] 2018-04-11 18:38
Thank you!

**Comment by Bionus** [comment] 2018-04-11 19:46
The fix will be included in the next release.

In the meantime, you can reproduce this change in your `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites\Danbooru (2.0)\model.xml` file:
https://github.com/Bionus/imgbrd-grabber/commit/3ea57dbf656185952099e6af1600b7ecde9b7446#diff-4124402ea1c541809e173f9e662db473

**Comment by RinKotori** [comment] 2018-05-23 19:14
Hi, sorry to be a bother, but I am still having this issue on the latest nightly (98d803eb), it still saves as the md5. It seems the images are pointing to one url (e.g. https://danbooru.donmai.us/data/c8c1754eeb4bb1bef73e2afa4979d848.jpg) rather than the "proper" one (e.g. https://danbooru.donmai.us/data/__watanabe_you_love_live_and_love_live_sunshine_drawn_by_rozen5__c8c1754eeb4bb1bef73e2afa4979d848.jpg)

It is probably something I have done wrong, but I would appreciate any info you have about this, thank you.

**Comment by Bionus** [comment] 2018-06-01 19:37
@Pobuo you don't need to do anything that complicated. And for the `model.xml` solution, it doesn't apply to more recent versions.

If you want the very latest version, you can directly download the [nightly installer](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly). It should contain the `%filename%` fix.

**Comment by RinKotori** [comment] 2018-06-02 02:53
Hi again, just to confirm that after testing with the latest nightly version, %filename% seems to work as intended once again. Thank you very much for your help and all your effort!

**Closed** 2018-06-08 20:19 UTC
Labels: bug, reproduced, source
