### ISSUE TITLE
chan.sankakucomplex.com not downloading

### ISSUE THREAD

**Issue by anon1593** [Bionus/imgbrd-grabber#1082] opened 2017-09-23 09:34 UTC
### What steps will reproduce the problem?
downloads from chan.sankakucomplex.com

### What is the expected behavior? What do you get instead?
sits at 100% but no file is downloaded

### How often does this problem occur? On which sources?
always 

### What version of the program are you using? On what operating system?

5.5.0 on windows 10

**Comment by MasterPetrik** [comment] 2017-09-23 14:22
Seriously? Another duplicate of https://github.com/Bionus/imgbrd-grabber/issues/997?

**Comment by MrCrackR** [comment] 2017-09-23 15:56
Byebye Sankakucomplex [commit](https://github.com/Bionus/imgbrd-grabber/commit/a4af4990e207afc8329d61f9a816e26935ea586e)

**Comment by MasterPetrik** [comment] 2017-09-23 16:11
13 duplicated issues in total)))

**Comment by Bionus** [comment] 2017-09-23 16:12
Just out of the default sources.
So not only it will not do anything when updating (the `sites.txt` file does not get overwritten), you can still add it manually anyway.

BTW, closing this issue for duplication.

**Closed** 2017-09-23 16:12 UTC

**Comment by MasterPetrik** [comment] 2017-09-23 16:13
@Bionus will you close original issue or not? are you expecting fix sankaku some day or completely removing it?

**Comment by Bionus** [comment] 2017-09-23 16:19
I'll be waiting for their new API to update the model file.
