### ISSUE TITLE
About sankaku JSON API

### ISSUE THREAD

**Issue by urain39** [Bionus/imgbrd-grabber#1321] opened 2018-06-24 06:12 UTC
See Projects:
    https://github.com/CryShana/Sankaku-Channel-Downloader
    https://github.com/urain39/KngetPy

**Comment by urain39** [comment] 2018-06-24 06:13
It still works.

**Comment by Bionus** [comment] 2018-06-25 17:56
Duplicate of #1250?

Any difference between the implementation in those projects compared to Grabber?
The one I saw is headers.

**Comment by urain39** [comment] 2018-06-26 03:34
I think so, like if you try to download images without 'referer' in headers that you will get this problem, but i still dno't know why it still works on sometimes when i not set it.(may magic yet?)

**Closed** 2018-07-29 17:40 UTC

**Comment by urain39** [comment] 2018-07-29 17:47
Sorry for my issues, cuz that my English is not well.😥
