### ISSUE TITLE
Crashing when downloading lots of pictures at once

### ISSUE THREAD

**Issue by Acurisu** [Bionus/imgbrd-grabber#547] opened 2016-06-27 18:16 UTC
So when I try to download about 100'000 pics the grabber.exe just stops working after about 8'000.
Why is that so? 
I'll upload the dump files as attachment. If you need something more just say it.

[crashes.zip](https://github.com/Bionus/imgbrd-grabber/files/335549/crashes.zip)

[INFO]
I use the latest version and I clean installed it multiple times.

[UPDATE]
So if I start from page one it'll crash after about 8'500 - 8'700.
But if I start from page 290  I don't have that problem anymore.
(The download is still ongoing so maybe it crashes later or not Idk but it surpassed those 8'700)

[UPDATE]
It crashed after about 23'100 pics

[UPDATE]
I continued with page 1060 and it crashed after about 6092 pics

**Comment by Bionus** [comment] 2016-06-29 19:04
So it seems to crash after a given time more than at a fixed position then?
I'll investigate, with my current download speed it'll take a while to even arrive at 8K images, so the crash dumps you uploaded should help.

**Comment by Acurisu** [comment] 2016-06-30 11:38
I forgot to do the last update. I could download the rest without any problem. That would be about 62'000 pics. I don't think that it is a given time because it didn't crash after the same time. I could test some more since my internet speed 1Gbit/s. And I wanted you to ask is there a way to add luscious.net? I don't think it uses the types of image boards which are available at the moment.

**Comment by lllllllllllllllllllllllll** [comment] 2016-07-23 19:32
I can confirm I get a similar crash. Whenever I try to download more than 100k images from a single source, say gelbooru, it crashes bewteen the 2000 and 10000 mark. Sometimes it crashes before it even loads all the pages. 

80-90k images works in a single go most of the time, however.

**Comment by Bionus** [comment] 2016-07-27 00:23
So it indeed sounds like a RAM overuse issue. The fact that it may crash even before finishing loading the pages is actually quite strange, but that's valuable info, thanks.

I'll debug RAM usage during big batch downloads to see what may cause this.

**Comment by Flat** [comment] 2016-08-29 20:06
I'd also recommend running [Valgrind](https://wiki.gnome.org/Valgrind) on Grabber to see if there are any apparent memory related errors, (such as leaks). Running Grabber through Valgrind will slow Grabber down to a crawl while it is analyzing the program however.

**Comment by MasterPetrik** [comment] 2017-08-29 22:02
for @Bionus about that issue:

- autor is not actve on github over a half year(probably will not respond)
- the problem is outdated and related to old grabber version with old batch download system
- this issue may be solved by new implemented changes in the batch download system
- many similar issues from another users, and since the problem is still ongoing, oldest crashreports are less relevant compare to newer one like #618

# **I recommend to close this issue.** 
Because it's related to the old batch downloads and not relevant no more.
The same issue to #618, but #618 is about new batch downloads system, so it's still relevant.

**Closed** 2017-09-04 14:05 UTC
Labels: crash
