### ISSUE TITLE
Crash when downloading very big files

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#954] opened 2017-06-18 13:24 UTC
### What steps will reproduce the problem?

Title

### How often does this problem occur?

Every time, It just sometimes takes longer.

### What version of the program are you using? On what operating system?

![tcv8g5e](https://user-images.githubusercontent.com/19770864/27257332-5b177c16-53a0-11e7-8d37-c7782bd83e35.png)

### Please provide any additional information below

[Desktop.zip](https://github.com/Bionus/imgbrd-grabber/files/1083106/Desktop.zip)

It's quite annoying to download so many images...

**Comment by MasterPetrik** [comment] 2017-06-18 23:00
> Still crashes when mass downloading

Maybe then you post it in already created by you and still opened TWO issues!?
This - https://github.com/Bionus/imgbrd-grabber/issues/820 and that -https://github.com/Bionus/imgbrd-grabber/issues/618
What's the point of creating a multiple crash report issues about same problem. They are still opened, that means that they are NOT fixed, so of course it Still crashes.

**Comment by brodycas3** [comment] 2017-06-18 23:44
Sorry, didn't realize that they were still open.

**Comment by brodycas3** [comment] 2017-06-19 22:40
I have a new development, it crashed when downloading large files. I'm thinking if you stay of a single file long enough it will crash.

**Comment by Bionus** [comment] 2017-06-19 22:48
Do you have an example of such file that can reproduce the crash?
Or at least a batch download that guarantees a fast crash? (without needing to download 50K images)
From what you say, wouldn't that mean that someone with a very very slow connection will always get a crash?

**Comment by brodycas3** [comment] 2017-06-19 23:00
I will check TeamViewer and as soon as it crashes on a big file I will
share the link

**Comment by brodycas3** [comment] 2017-06-19 23:01
the files were 100 + mb when they crashed

**Comment by brodycas3** [comment] 2017-06-20 01:31
@Bionus i got a link that creates a crash in the batch download and is reproducible, warning please as idk whats in it, http://atfbooru.ninja/data/3335a08cad0f4fffe76311bfb588fcab.mp4

**Comment by brodycas3** [comment] 2017-06-20 17:34
I can't do any testing for a week now since my PC crashed and I won't be home for a week.

**Comment by brodycas3** [comment] 2017-06-22 23:43
Ehh, turns out I'll be home tomorrow and can then do some testing for you.

**Comment by Bionus** [comment] 2017-06-22 23:55
Well if the issue is with very big files such as the few you shared, I can also reproduce the crashes, so there shouldn't be any additional testing to do.

Fixing it may be harder on my end though: until now, files are entirely loaded in memory, then either displayed (image window), or saved on disk. To avoid the issue, I will have the image window simply not try to load or display files above a certain size, and the downloader load the image and write it directly to the disk without putting anything in RAM.

**Comment by brodycas3** [comment] 2017-06-22 23:57
Sounds good, hope this is fixed when I get home. ♥️

**Comment by Bionus** [comment] 2017-06-24 17:04
The crashes related to big files will be fixed in 5.4.0.

Too big files (above 200mo) will now be marked as errors during batch downloads (instead of crashing). In the image window, Grabber won't even try to load them (which caused crashes before), and will show a warning window "File is too big to be displayed" instead.

However, saving from the image window will work, even for huge files (I tried with your 1GB link).

**Comment by Bionus** [comment] 2017-06-24 17:05
Batch download of "very big files" require a lot of architectural changes and therefore won't be implemented in 5.4.0, as it could totally break downloads.

**Comment by brodycas3** [comment] 2017-06-24 20:29
>Too big files (above 200mo) will now be marked as errors during batch downloads

You sure that you shouldn't go lower? I crash at only 100mb

**Comment by Bionus** [comment] 2017-06-24 20:36
I will see after doing tests. This "limit" depends on the computer, OS, etc. I wouldn't want to have users who before could download files have them un-downloadable after the update.

**Closed** 2017-07-09 15:07 UTC
Labels: crash
