### ISSUE TITLE
Logo instead of image chan.sankakucomplex.com

### ISSUE THREAD

**Issue by tg4f34** [Bionus/imgbrd-grabber#2348] opened 2021-04-24 19:53 UTC
![e3d1073a9cf2d685fd55da44f1110900](https://user-images.githubusercontent.com/62241487/115971192-c15c8e80-a54f-11eb-8c69-7ec2bd74319f.jpg)

**Comment by tg4f34** [comment] 2021-04-24 19:55
if anything after reinstalling windows

**Comment by yami-no-tusbas** [comment] 2021-04-25 10:07
This board is no longer supported anymore, you won't get help here. I suggest you to close this issue.

**Comment by Donny-Pandairaz** [comment] 2021-04-25 16:35
Yeah, Sankaku Complex is no longer supported due to the owner of the site shutting off access to the API out of spite.

**Comment by tg4f34** [comment] 2021-04-25 16:46
but it worked for me three days ago

**Comment by tg4f34** [comment] 2021-04-25 16:48
but it worked for me three days ago

**Comment by Blobbus23** [comment] 2021-04-26 01:44
I kinda curious about this issue as well

**Comment by Desk5103** [comment] 2021-04-26 08:52
ig this will help here too
just read this issue #2333, I fixed it there (temporary dirty solution but works perfectly fine)

1. download the sankaku folder from [here](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826275583) and replace it with the current one in "C:\Users\your uesrname\AppData\Local\Bionus\Grabber\sites"
2. [set the source to json](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826265346)
3. and now to login you have to do [this](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826333230)
4. and ehh something extra, u can [download posts without an interval now](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826560861)

**Comment by tg4f34** [comment] 2021-04-26 09:20
thank you very much

**Comment by tg4f34** [comment] 2021-04-26 09:21
thank you very much

**Comment by Blobbus23** [comment] 2021-04-26 17:43
big mcthankies from mcspankies

**Comment by Desk5103** [comment] 2021-04-26 17:53
ah i forgot to tell here that i have update the [sankaku.zip](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826748490)

**Comment by KoroloSV** [comment] 2021-04-27 21:10
should be working again, servers were fixed and site changes were reverted

**Comment by heywolf15** [comment] 2021-05-07 20:07
> 
> 
> ig this will help here too
> just read this issue #2333, I fixed it there (temporary dirty solution but works perfectly fine)
> 
>     1. download the sankaku folder from [here](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826275583) and replace it with the current one in "C:\Users\your uesrname\AppData\Local\Bionus\Grabber\sites"
> 
>     2. [set the source to json](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826265346)
> 
>     3. and now to login you have to do [this](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826333230)
> 
>     4. and ehh something extra, u can [download posts without an interval now](https://github.com/Bionus/imgbrd-grabber/issues/2333#issuecomment-826560861)

It doesn't work for me
Internal Server Error (401)

**Comment by Desk5103** [comment] 2021-05-07 20:11
@heywolf15 why are you using that method now, html is working properly now theres no need to change anything

**Comment by heywolf15** [comment] 2021-05-07 21:32
@Desk5103 It doesn't work when I tried to add chan.sankakucomplex.com for the first time, that's why I do that.
I need to delete it then re-open it to work

**Comment by Bionus** [comment] 2021-07-05 11:37
Closing as a duplicate of #2333.
And good job @Desk5103 for your work on managing to make it work on newer versions, I didn't even know it was possible 😅

**Closed by Bionus** 2021-07-05 11:37 UTC
