### ISSUE TITLE
%filename% no longer working

### ISSUE THREAD

**Issue by amped777** [Bionus/imgbrd-grabber#1243] opened 2018-04-10 12:16 UTC
The %filename% option doesn't seem to be working properly anymore.  It seems to name files to their md5 instead of to the name starting with _ that you'd otherwise get when simply right clicking and saving an image directly from danbooru.  

It was working properly for me just last week, so the problem probably started occurring some time after that.

**Comment by amped777** [comment] 2018-04-10 12:18
As an example I get "c96761e51bac109f745e2bc3f3b5bc45" when I'd expect to get "__hamakaze_kantai_collection_drawn_by_10eki_tenchou__c96761e51bac109f745e2bc3f3b5bc45"

**Comment by Vorch** [comment] 2018-04-10 22:49
Same here, can't figure it out.

**Comment by Bionus** [comment] 2018-04-11 18:17
Duplicate of #1239, moving to there.

**Closed by Bionus** 2018-04-11 18:17 UTC
Labels: bug, source
