### ISSUE TITLE
Tag types not detected on Gelbooru

### ISSUE THREAD

**Issue by herpaderphurr** [Bionus/imgbrd-grabber#515] opened 2016-04-15 11:44 UTC
It looks like tag types aren't detected on Gelbooru at the moment, so things like different coloured tags and saving the %artist% field aren't working.

**Comment by Bionus** [comment] 2017-04-13 23:44
It was caused by a change in their API last year. It should be fixed in recent versions.

**Closed by Bionus** 2017-04-13 23:44 UTC
