### ISSUE TITLE
[Bug/Crash] QMYSQL driver missing from driver options/not loaded

### ISSUE THREAD

**Issue by FallenMei** [Bionus/imgbrd-grabber#1892] opened 2020-03-03 06:35 UTC
**Steps to reproduce**

1. Configure Grabber exactly as described in [the wiki tutorial](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru)
2. Download images

**System information**

- OS: Windows 10 (1909)
- Grabber version: 7.2.1 (x64)

**Expected Behavior**
Grabber should execute SQL commands after downloading a image.

**Context**
This issue is similar to [this issue](https://github.com/Bionus/imgbrd-grabber/issues/1718 ) except the solution from the comments no longer works in Grabber 7.2.1.
Additionally, QMYSQL is missing from the dropdown options for in Options > Commands > Database > Credentials > Driver. When I updated Grabber from 7.1.1 the option had no driver chosen and was blank.

This is what `main.log` reports after downloading an image:
```
[00:45:46.485][Warning] [Qt][default] QSqlDatabase: QMYSQL driver not loaded
[00:45:46.486][Warning] [Qt][default] QSqlDatabase: available drivers: QSQLITE QODBC QODBC3 QPSQL QPSQL7
[00:45:46.486][Warning] [Qt][default] QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
[00:45:46.486][Error] Error initializing commands: Driver not loaded Driver not loaded`
```
When I tried replacing `libmysql.dll` with the file from the latest mysql connector zip (as described in the aforementioned issue's comments) Grabber will crash after downloading an image. `main.log` reports this before the crash:
```
[00:40:48.853][Error] [Qt][default] Cannot mix incompatible Qt library (version 0x50a01) with this library (version 0x50c06)
```
As a test I tried setting my driver to QPSQL, but received the same error `QPSQL driver not loaded`.

I have not been able to find a configuration that allows me to alter my database. If QMYSQL has been intentionally removed the wiki tutorial needs updating. I have temporary downgraded to Grabber 7.1.1.

**Comment by Bionus** [comment] 2020-03-22 16:38
I just pushed a fix that should land in nightly versions very soon and fix the issue, sorry about that!

-----

> When I tried replacing libmysql.dll with the file from the latest mysql connector zip (as described in the aforementioned issue's comments) Grabber will crash after downloading an image. main.log reports this before the crash:

Yes, the Qt version used changed, so the SQL driver won't be the same. Their versions have to match perfectly or you'll crash.

> If QMYSQL has been intentionally removed the wiki tutorial needs updating. 

It wasn't intentional, it's caused by the new build system that uses AppVeyor. Previous versions I built myself manually.

**Comment by FallenMei** [comment] 2020-03-24 08:48
Thanks. If I end up not wanting to use the nightly version what is the version of Qt in Grabber 7.2.1 so I can drop in the correct libmysql.dll?

**Comment by Bionus** [comment] 2020-03-24 09:19
Should be the `5.12.6` version.

You can find the DLL here: https://github.com/thecodemonkey86/qt_mysql_driver/releases/tag/qmysql_5.12.6 (MSVC2017 version)
You should replace `libmysql.dll` as well as `sqldrivers/qsqlmysql.dll`.

**Closed** 2020-06-03 13:32 UTC
Labels: bug, build, reproduced, windows
