### ISSUE TITLE
Scroll to paginate on Android

### ISSUE THREAD

**Issue by 09eragera09** [Bionus/imgbrd-grabber#2858] opened 2022-12-17 23:44 UTC
**Is your feature request related to a problem? Please describe**

Pagination on android sucks, scrolling is more natural

**Describe the solution you'd like**

Scroll to paginate instead of pressing buttons

**Describe alternatives you've considered**

None

**Comment by Bionus** [comment] 2023-03-26 17:48
Closing as duplicate of #2884 even though this one is older since the commits reference the other one.

**Closed by Bionus** 2023-03-26 17:48 UTC
Labels: suggestion, ui, android
