### ISSUE TITLE
Crashes while Download

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#734] opened 2017-01-04 03:57 UTC
### What steps will reproduce the problem?

1.
 
1.1 Pressing Download all or Download selected after Get all

1.2 Downloading 3 or more pages

tag christmas

### What is the expected behavior? What do you get instead?

1.

1.1 Grabber is crashing while it is in the download process of the pictures, instead of running through.

1.2 Grabber is crashing on downloading the 3rd page, instead of loading all 3 pages,

### What version of the program are you using? On what operating system?

Grabber 5.01
Win 7 Home Premium

### Please provide any additional information below

here is all data you need

[model.txt](https://github.com/Bionus/imgbrd-grabber/files/682244/model.txt)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/682245/settings.txt)
[settings2.txt](https://github.com/Bionus/imgbrd-grabber/files/682246/settings2.txt)
[mainlog.txt](https://github.com/Bionus/imgbrd-grabber/files/683007/mainlog.txt)

**Comment by Bionus** [comment] 2017-06-24 21:07
The crash occured when downloading a 173MB file (**NFSW**: [file](https://cs.sankakucomplex.com/data/7b/f3/7bf302162a0546633faca6de62c93e10.mp4) & [page](https://chan.sankakucomplex.com/post/show/5763628)), so the crash is more than likely to be caused by the size of said file.

See issue #954 and #963 for follow-up, I'll be closing this issue.

**Closed by Bionus** 2017-06-24 21:08 UTC
Labels: crash
