### ISSUE TITLE
Crash after batch download with enabled "Remove" checkbox

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#812] opened 2017-02-27 06:49 UTC
![2017-02-27_085943 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23351194/cba7a6d0-fcd0-11e6-8078-24bbf00ea2e8.png)

Win 7x64, 5.2.2

That's it.
I don't know what this checkbox should do, but every time when I enable it, and then try to batch download something, after finishing downloads and showing statistic window it crash Grabber. When I disable it, all became normal. 
100% repeatability for me

**Comment by Bionus** [comment] 2017-02-27 07:36
> I don't know what this checkbox should do

It's supposed to remove the batchs that are finished downloading from the "Downloads" tab.

**Comment by MasterPetrik** [comment] 2017-02-28 00:12
> It's supposed to remove the batchs that are finished downloading from the "Downloads" tab.
Iinstead of it it just crashes grabber, and yes, batchs are not removed after that too...

**Comment by MasterPetrik** [comment] 2017-03-12 01:40
![image](https://cloud.githubusercontent.com/assets/22294259/23828252/52809f70-06dd-11e7-9927-ed341511a49b.png)


@Bionus, you need to reopen this issue because is still crashes with 100% repeatability
here is the info about 2 fresh crashes from 5.2.3: 
http://rgho.st/private/8VZTcLmTP/198abdf7d67049f154bac3fc443948bc

**Comment by Bionus** [comment] 2017-03-12 11:43
* Does it happen 100% whatever download you do, directly from the first download? (if not, can you send an IGL file?)
* Do you enable the setting in the middle of the download/at the end before closing the window/before?

I couldn't reproduce it after the fix so I considered it closed, but in that case the problem is just that I couldn't reproduce in the first place.

**Comment by Bionus** [comment] 2017-03-12 12:20
I couldn't reproduce even with your settings. Are there any steps to take to ensure the crash?

**Comment by MasterPetrik** [comment] 2017-03-12 15:56
https://drive.google.com/open?id=0B3SK4Pf9wsnmcjJIc1lnRGE4RzQ

here is the video of the process

**Comment by MasterPetrik** [comment] 2017-03-12 16:04
> Does it happen 100% whatever download you do, directly from the first download? (if not, can you send an IGL file?)

It happens in 100% cases for different tags and downloads, AFTER all sucessfully downloaded and stats are shown, then crash appears. So, I guess, it happens when Grabber is trying to remove the batchs.

> Do you enable the setting in the middle of the download/at the end before closing the window/before?

I enabled it before download and in the middle of the download, with same result - crack after completing of downloading. I can't set it "at the end before closing" because it colses too quick.

**Comment by MasterPetrik** [comment] 2017-03-28 23:12
@sanddudu @barryanders @ brodycas3 can you please test, Does checked "Remove" checkbox in batch downloads window causes a crash after completing downloading? Because, looks like this bug that is not for all, so I need more statistic, please.

**Comment by sanddudu** [comment] 2017-03-29 01:52
@MasterPetrik Source is e621, with Grabber 5.2.4, doesn't crash.
Let me know if you need more test.

**Comment by barryanders** [comment] 2017-03-30 07:40
I haven't run a batch in a long time but since you asked, I'll run a test.

---

On a 340 image download with v5.2.4 (latest dev branch commit as of this post), I saw no crashing of any kind and the batch download was removed as expected after completion

**Comment by MasterPetrik** [comment] 2017-03-30 10:22
I still have not a single clue, why some people have this bug, but some other don't. My last idea, thai it may be somehow depend of user OS, I use Win7, the guy from https://github.com/Bionus/imgbrd-grabber/issues/866 uses Win10, and as I remember, @barryanders uses Mac, maybe it's for windows only? Or it's just a coincidence...

**Comment by sanddudu** [comment] 2017-04-18 04:20
Today I finally reproduced the problem, I am trying to download about 3000 images.
There is nothing wrong I can see in the log file.
Here is the minidump.
[4e29c9cb-312f-4ce6-92b1-4cdf5b795a72.zip](https://github.com/Bionus/imgbrd-grabber/files/927307/4e29c9cb-312f-4ce6-92b1-4cdf5b795a72.zip)

**Comment by MasterPetrik** [comment] 2017-05-19 23:47
5.3.0 alpha - still crashing

**Comment by Bionus** [comment] 2017-05-20 00:03
@MasterPetrik can you send me the `settings.ini` and IGL file that can reproduce this? I never could reproduce locally. Thanks :smile:

**Comment by MasterPetrik** [comment] 2017-05-20 00:20
>  IGL file that can reproduce this

What this IGL file is? Not sure to understand what is it -___-
here is all other files:
https://drive.google.com/open?id=0B3SK4Pf9wsnmNEZkNEpMZVNicFE

**Comment by Bionus** [comment] 2017-05-20 00:41
> What this IGL file is? Not sure to understand what is it -___-

It's the file you get when clicking "Save" on the Downloads tab. It contains the list of the downloads in JSON format.

> looks like you will be here all night long?

Nah, I'm going to bed soon, but I'll try to fix another batch of issues tomorrow if I have some free time. I'll then release v5.3.0 some time during the week-end.

**Comment by MasterPetrik** [comment] 2017-05-20 00:54
> It's the file you get when clicking "Save" on the Downloads tab. It contains the list of the downloads in JSON format.

I guess that this is pointless because I tested many variants and can surely tell you that problem is not in download process. And that's why:
1. it happens for all downloads, with no exceptions
2. all downloaded images do it sucessfully, no signs of problems with them, even same md5 compare to source
3. it happens even when you trying to download already saved images and ignoring instead of downloading
4. It always happens ONLY after closing this window, when all download prosess has been completed. Grabber won't crash if you will not close this window. But if you will do it, Grabber will immediately crash

![2017-05-20_034846 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/26271494/4714b4c4-3d0f-11e7-8115-d945c6c42d0b.png)

**Comment by BarryMode** [comment] 2017-08-04 03:44
Still happening or is this old news?

**Comment by MasterPetrik** [comment] 2017-08-04 21:46
it's still happening in all versions, and in latest too. So I still wait that it will be fixed someday...

**Comment by MasterPetrik** [comment] 2017-08-08 17:07
@Bionus, considering that you can't reproduce it,  may I ask you, as experiment, try to use another method to clear the grid from downloads? I guess it can be done with different ways. maybe it will fix the problem. At least you can try I guess

**Comment by Bionus** [comment] 2017-08-08 18:57
I could try to fix it blindly but without any ways to reproduce I wouldn't really guarantee it could fix anything. Plus, the way the row is getting removed is already pretty much the only possible way.
https://github.com/Bionus/imgbrd-grabber/blob/develop/gui/src/mainwindow.cpp#L1893-L1906

Actually, does this happen if let's say:
* You close Grabber
* You rename `restore.igl` to something else
* You open Grabber
* You add a single batch download from some basic search
* You click "Download all"
* You enable the "Remove" checkbox during the download

Which is the most basic situation I can think of and using your provided settings and IGL file I can't reproduce the crash.

**Comment by MasterPetrik** [comment] 2017-08-08 19:57
Ok. deleting restore.igl schanged nothing, as I expected.

But I figured out some new info now. When I use only one source with "Remove" checkbox, it clears downloads list properly and everything is OK. I tested it with different sources and everything was OK.
But if you use more then one sources with "Remove" checkbox(even if all of them have been sucessfully removed in solo version) then grabber crashes as always.

It happens as I said, only after you press OK in this window.

![2017-08-08_224232 win7 mastercore](https://user-images.githubusercontent.com/22294259/29091716-801e7e6e-7c8c-11e7-9a21-f9c0794fcd84.png)

![2017-08-08_220500 win7 mastercore](https://user-images.githubusercontent.com/22294259/29091720-87b92782-7c8c-11e7-9863-dec091fbee49.png)

So please check part of code that works when you delete lines one by one. Btw, while it happening, numbers in this window with statistic are decrises in the proces of deleting lines in grid

**Comment by MasterPetrik** [comment] 2017-11-13 07:53
@Bionus So it's already 4 other guys faced with this bug exept me, https://github.com/Bionus/imgbrd-grabber/issues/866 and  https://github.com/Bionus/imgbrd-grabber/issues/1143 and #1113

Considering that you can't reproduce it, maybe you will re make removing part in different way somehow, I can even test all that on nightly and tell, helped it or not.

**Comment by MasterPetrik** [comment] 2017-11-13 14:42
BTW, I don't know why, but if you remove downloads by pressing "delete all" or "delete selected"
then everything works well. All the time. 

![2017-11-13_164041 win7 mastercore](https://user-images.githubusercontent.com/22294259/32730852-62928b8e-c899-11e7-84ce-9d48b5ab92f9.png)

I don't know why, maybe these buttons uses another way to remove items, but it surely work much better then autoremoving. Maybe you will change it's function to one of these?

Baybe using in autoremoving

**Comment by sanddudu** [comment] 2017-11-14 02:34
@MasterPetrik Sometimes even I use "Delete all", it will crash too. And that makes this issue much weird.

**Comment by MasterPetrik** [comment] 2017-11-14 08:37
Anyway, even "sometimes" is much much better then "always" ツ
And also I never expiriensed crashes when deleted items with buttons.

**Comment by Bionus** [comment] 2017-11-22 19:59
The fix should have just landed in nightly.
I hope it fixes this very old issue :smile:

**Comment by brodycas3** [comment] 2017-11-22 20:49
How do I get nightly?

**Comment by Bionus** [comment] 2017-11-22 21:02
https://github.com/Bionus/imgbrd-grabber/releases/nightly

**Comment by MasterPetrik** [comment] 2017-11-22 21:32
@brodycas3 it was me who mentioned you) Hehe

**Comment by MasterPetrik** [comment] 2017-11-23 03:16
@Bionus Looks like it fixed indeed.
But, considering all my suffering and waiting in process of investigation, I will not be satisfied until you will explain me, why and how crashes was happening and also why you couldn't find the problem earlier, considering all these information which I provided.

**Comment by Bionus** [comment] 2017-11-28 23:49
For a bunch of reasons.

The main one being that it occurred depending on the order of your downloads, the order in which they finished, the number of downloads, and the unpredictable order of the elements going out of the [QSet](https://doc.qt.io/qt-5/QSet.html) class.

None of my tries resulted in crashes because on my system, QSet always perfectly sorted the elements, causing my algorithm to work with no issues. I could reproduce the crash by forcefully randomizing the elements I got from that set. Converting it to a normal [QList](https://doc.qt.io/qt-5/QList.html) (with a deterministic order) and then sorting it how I the algorithm requires fixed the crash. Said sorting is critical for the way the elements are removed from the table: otherwise, it'll try to remove elements which are out of the bounds of the table, causing a crash.

You can see this in these two commits:
- 1d65daf416b51803052868a8bc4f4766315fcebe
- b7a5b9623358df7cfbcf96621bcf4bfbfe2758ed

**Comment by MasterPetrik** [comment] 2017-11-29 01:25
Thanks for detailed explanation, only one question left: why pressing "delete all" or "delete selected" buttons  worked all the time, when autoremoving crashed grabber?

**Comment by Bionus** [comment] 2017-11-29 09:49
Because these two buttons were already using QLists, and were being populated in the correct order in the first place (so they could be fed to the algorithm in the correct order too). Only the "remove" checkbox would use q QSet.

**Comment by MasterPetrik** [comment] 2017-11-30 02:55
> Because these two buttons were already using QLists, and were being populated in the correct order in the first place (so they could be fed to the algorithm in the correct order too). Only the "remove" checkbox would use q QSet.

Great... at the end I was right since august -____- meh:
> Because buttons "delete selected" and "delete all" are work correctly in any conditions, **so obviously the problem is in specific code, that not used in buttons pressing procedures, but used in after-downloading-cleaning process, and this part of code cause crash only when number of sources are more then one.**

Thanks for answers anyway.

**Closed** 2018-06-08 20:19 UTC
Labels: crash, reproduced
