### ISSUE TITLE
Gelbooru tags not separated into artist/character/copyright

### ISSUE THREAD

**Issue by Gr0ose** [Bionus/imgbrd-grabber#2236] opened 2021-01-18 06:24 UTC
Ive seen that Gelbooru has done some site updating, and Grabber is no longer properly separating the tags into their respective tag type.

**Comment by yami-no-tusbas** [comment] 2021-01-18 08:56
Duplicate of #2235 it seems

**Closed** 2021-01-18 17:34 UTC
Labels: bug, duplicate, reproduced, source
