### ISSUE TITLE
Sankaku Complex tags problem

### ISSUE THREAD

**Issue by hubgitjack** [Bionus/imgbrd-grabber#727] opened 2017-01-01 17:14 UTC
### What steps will reproduce the problem?

When I search only one tag in Sankaku Complex, I get the total number of results (and I can download them all pressing the "Get all" button) but when I search two tags it doesn´t work.

[Example](http://i.imgur.com/3dgjgFq.jpg)

### What version of the program are you using? On what operating system?

5.0.1 on Windows 8.1

**Comment by Bionus** [comment] 2017-01-02 19:45
Duplicate of #729

**Closed by Bionus** 2017-01-02 19:45 UTC
