### ISSUE TITLE
Ubuntu 18.04.2 Error the redux 

### ISSUE THREAD

**Issue by Teoyaomiqui-01** [Bionus/imgbrd-grabber#1852] opened 2019-12-18 01:11 UTC
Hey so I attempted to install this lovely package today and encountered a few errors. So first I’m running Ubuntu 18.04.2 LTS, and had the same issue as post #1808, after following the instructions included in that post I managed to complete the build.sh script. Afterwords I ran the make install command as suggested in this page
 https://github.com/Bionus/imgbrd-grabber/wiki/GettingStarted.
 Make install concluded with 
 CMake Error at gui/cmake_install.cmake:52 (file):
  file INSTALL cannot find "/home/xaphan/imgbrd-grabber/build/gui
If there is any advice you can give me on how to fix this problem it would be very much appreciated. Thank you as well for producing such a lovely program. I will be including the whole error log below. 
In addition if there is any other information that is needed to resolve this error I would be happy to provide it. # # #
[Imgbrd-grabber make install error log](https://github.com/Bionus/imgbrd-grabber/files/3976171/Imgbrd-grabber.make.install.error.log)

**Comment by Bionus** [comment] 2020-01-16 19:21
Hello!

I just tried on the `master` branch and indeed could reproduce your error.
After checking on the `develop` branch, it seems to be solved. So you can try to checkout that branch and build from there or wait for the next update and it should be fixed! 😄

**Closed by Bionus** 2020-01-16 19:21 UTC
Labels: build, linux
