### ISSUE TITLE
Can not download from gelbooru due to URL error

### ISSUE THREAD

**Issue by lockers120** [Bionus/imgbrd-grabber#1049] opened 2017-08-31 09:41 UTC
### What steps will reproduce the problem?
the **simg4.** cause 404 error
http://simg4.gelbooru.com/images/f2/a1/f2a19345810671bc23d413e411bf1ac4.jpg

**Comment by Bionus** [comment] 2017-08-31 11:25
Duplicate of #1042.
You need to enable HTTPS for Gelbooru to work for now.

**Closed by Bionus** 2017-08-31 11:25 UTC
