### ISSUE TITLE
Button clicks do not register outside of text area.

### ISSUE THREAD

**Issue by TogarUshindi** [Bionus/imgbrd-grabber#2334] opened 2021-04-14 19:23 UTC
**Bug description**

Button mouseclicks do not register on buttons, such as "Ok" or "Get All", unless clicked directly on the text area of the button. Anywhere outside the text, but within the button, do not register as a click.

![image](https://user-images.githubusercontent.com/54905590/114766916-d8afa680-9d1b-11eb-8f11-874c56a43b3f.png)

The button highlights, giving the appearance the button was clicked, but nothing happens.

**System information**

- OS: Linux Mint 20.10
- Grabber version: 7.5.1 (x86) ImageApp

**Comment by Quartz77** [comment] 2021-04-19 02:08
I've been having this issue as well. It only happens for me when using dark theme, it looks like the clickable area on the stylized buttons is smaller than the the graphic. I checked the default theme and it does not have the same issue.

**System info:**

OS: Win 10 Home x64
Grabber version: 7.5.1 (x64)

**Comment by Bionus** [comment] 2021-04-19 19:29
Yes seems like it's caused by the `padding: 5` for `QPushButton`.
Note that this theme is from https://github.com/ColinDuquesnoy/QDarkStyleSheet so I'm not very familiar with it.

They have a new v3 version now, you can try putting it in your `themes` folder and see if you like it more: [themes.zip](https://github.com/Bionus/imgbrd-grabber/files/6338549/themes.zip)
The buttons are fixed but they're much smaller now 🤷‍♂️

**Comment by TogarUshindi** [comment] 2021-04-20 16:46
I do know in GTK and Glade there is a way to adjust this. I might take a look later and see what I can do. Wouldn't mind playing with Qt. Is there a WYSIWYG editor?

**Comment by Bionus** [comment] 2022-01-07 21:41
Fixed by 2cb7851c2b05b1114a86ee40d9a5479d71cd638f in [v7.6.1](https://github.com/Bionus/imgbrd-grabber/releases/v7.6.1).
This was caused by [QTBUG-86587](https://bugreports.qt.io/browse/QTBUG-86587).
Another issue on this topic: #2434

**Closed by Bionus** 2022-01-07 21:41 UTC
Labels: ui
