### ISSUE TITLE
Buttons require multiple clicks

### ISSUE THREAD

**Issue by Merthew** [Bionus/imgbrd-grabber#2356] opened 2021-05-03 20:52 UTC
**Bug description**

Honestly not really sure what is going on if its a bug or just my computer, no crash occurs so its not like I have a log file that would help, but most of the times I got to click any button I have to click it twice or three times or something like that before it registers.

**Steps to reproduce**

Click a button, then do it again

**Expected behavior**

Not having to click the button again?

**System information**

- OS: Windows 10
- Grabber version: 7.5.1

**Comment by GiovanH** [comment] 2021-05-03 23:09
When you say "button", you mean the generic UI buttons like "Download" and "Save"? I'm not able to duplicate that.

**Comment by Merthew** [comment] 2021-05-04 01:09
Yeah, I have had this issue mostly with the "sources" button and at this point I'm thinking it may be the program lagging. There have been some recent lag spikes when trying to load images so it could be related

**Comment by xodiack** [comment] 2021-05-04 12:51
I'm also having this issue, I assumed it was my mouse going bad. I'm also on W10 , specifically Ver 2004 build 19041.867, and Grabber 7.5.1. In my case it isn't every click, maybe 50% of the time it occurs. The only "click" setting I've got is the inverted Ctrl/Click function enabled in the options.

**Comment by JippC** [comment] 2021-05-19 04:09
Same. Windows 10, latest version (7.5.1). Pretty much every button does it.

**Comment by uematsufreak** [comment] 2021-07-23 22:00
I'm having this problem as well on 7.6.0, and have been for many versions now. Right now I'm working around it by clicking and hitting "space" afterwards each time, but it's frustrating nonetheless.

**Comment by Bionus** [comment] 2021-11-11 13:10
Hello

This was caused by [QTBUG-86587](https://bugreports.qt.io/browse/QTBUG-86587) and fixed by the update of Grabber to use Qt 5.12.2 (f27a726f06c10fe1ec0a56e3dc8c3bfaa5eb50a2).
Also tracked as issue #2434

**Closed by Bionus** 2021-11-11 13:10 UTC
Labels: bug, ui, reproduced
