### ISSUE TITLE
Not giving how many images there are/pages/any images for certain sources

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1278] opened 2018-06-09 17:15 UTC
### What steps will reproduce the problem?
When you try to lookup for example nekopara rating:safe on the 6.0.0 version and on the 5.5.2 version you see that by the 5.5.2 version it will show all the images and the amount of pages and by the other one it doens't. Here are some examples with comparisons between the versions: (Left version 6.0.0 right 5.5.2)
[https://i.imgur.com/yBTExpD.png](https://i.imgur.com/yBTExpD.png)
Here you can see that the yande.re source does give different result between versions with the same search.
[https://i.imgur.com/1mA5SQI.png](https://i.imgur.com/1mA5SQI.png)
Here has rule34.xxx no images in version 6.0.0 while it had 1 image in 5.5.2.
[https://i.imgur.com/3tmHeuU.png](https://i.imgur.com/3tmHeuU.png)
And here you can also see that konachan give different results between versions.

### What is the expected behavior? What do you get instead?
Give the same result between the versions. So than you can see how many images there are by konachan and yande.re and that rulexx does have the images it had by the previous version. Instead I now get different results back from the same search.

### How often does this problem occur? On which sources?
It occurs everytime and tested it with yande.re, konachan and rule34.xxx

### What version of the program are you using? On what operating system?
I tested it with 6.0.0 with windows 10 and compared it to 5.5.2

**Comment by Bionus** [comment] 2018-06-09 19:02
Indeed, it would seem that the last page parsing for Moebooru (konachan and yandere) was broken. As for rule34.xxx, it seems that it was a bug caused by the fact that there was only 1 result (quite the critical bug te be honest). 

I pushed a fix, and I'll release v6.0.1 tonight, thanks for the report! 👍

**Closed** 2018-06-09 19:06 UTC
Labels: bug, reproduced, source
