### ISSUE TITLE
batch download stops after 20 images

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#809] opened 2017-02-26 22:24 UTC
![image](https://puu.sh/uleEi/a94c508069.png)

it should download 1000 pics, but always stops after 20. Am I doing something wrong?

**Comment by MasterPetrik** [comment] 2017-02-26 23:46
maybe your delay between downloads are to low and sankaku blocks your downloads due to to many downloads in small time, I know that only sankaku do this. You can try another booru and report about your result.

**Comment by maskkulin** [comment] 2017-02-26 23:56
![image](https://puu.sh/ull7q/ea5f4b7341.png)
this are my settings. It worked fine with the other grabber version

**Comment by MasterPetrik** [comment] 2017-02-27 00:06
Well. Anyway sankaku is blocked in my country and I can't test it. 
Let's wait Bionus ansver then.

P.S.
I did not tested batch downloads in new version yet, but I guess I need to do it.

**Comment by Bionus** [comment] 2017-02-27 04:20
I can indeed reproduce this issue when I try to make batch downloads on Sankaku while logged out. It seems the packing feature that should make packs of 1,000 images (so in this case 50 pages of 20 images) fails to do so and only gets one page.

![image](https://cloud.githubusercontent.com/assets/882719/23348637/5fbad484-fcac-11e6-9afe-5f515d5e3786.png)

**Comment by MasterPetrik** [comment] 2017-02-27 04:24
> It seems the packing feature that should make packs of 1,000 images (so in this case 50 pages of 20 images) fails to do so and only gets one page.

in this case maybe will be a good solution to add  an option to sources settings to set number of pages for batch download separate for each site?

**Comment by Bionus** [comment] 2017-02-27 04:26
> in this case maybe will be a good solution to add an option to sources settings to set number of pages for batch download separate for each site?

It should already be automated. Depending on the "images per page" you set for the download, Grabber will calculate how many pages are required to make packs of approximately 1,000 images (I say "approximately" if you have 300 images per page, it will download 3 pages and have packs of 900 images).

**Comment by Bionus** [comment] 2017-03-10 20:50
After investigation, this problem only happens when the images limit is set to a multiplier of 1,000 (the number of images in a pack). Change the limit to something like 1,001 and it will download the images properly. It will be fixed in 5.2.3.

**Closed** 2017-03-11 18:27 UTC
Labels: bug
