### ISSUE TITLE
e621.net not working

### ISSUE THREAD

**Issue by SendHelp1** [Bionus/imgbrd-grabber#1930] opened 2020-04-09 19:56 UTC
Hello,
I do not receive any results from e621.net, can somebody help me to fix that? I use proxy too but that's not the case since I checked dozens of them and all other resources gave me results. Here's the log

[22:54:49.060][Info] Loading results...
[22:54:49.060][Info] [e621.net][Html] Loading page https://e621.net/posts?limit=20&page=1&tags=male
[22:54:49.061][Info] [e621.net][Json] Loading page https://e621.net/posts.json?limit=20&page=1&tags=male
[22:54:49.364][Info] [e621.net][Json] Receiving page https://e621.net/posts.json?limit=20&page=1&tags=male
[22:54:49.365][Warning] [e621.net][Json] Uncaught exception at line 91: SyntaxError: JSON.parse: Parse error
[22:54:49.365][Warning] [e621.net] Loading using Json failed. Retry using Html.
[22:54:49.966][Info] [e621.net][Html] Receiving page https://e621.net/posts?limit=20&page=1&tags=male
[22:54:49.967][Info] [e621.net][Html] Parsed page https://e621.net/posts?limit=20&page=1&tags=male: 0 images (0), 0 tags (0), -1 total (-1), -1 pages (-1)

**Comment by SendHelp1** [comment] 2020-04-09 19:58
I think it's because they updated their site recently. Everything was OK few months ago. I saw a thread about it somewhere but there was nothing useful in it I still have problems

**Comment by Bionus** [comment] 2020-04-09 20:30
Duplicate of issue #1895.
Please post there if you have questions. FYI, e621 is already fixed in [nightly releases](https://github.com/Bionus/imgbrd-grabber/releases/nightly) 👍

**Closed by Bionus** 2020-04-09 20:30 UTC

**Comment by SendHelp1** [comment] 2020-04-09 20:32
It's not working for me still but ok, sure.

**Comment by SendHelp1** [comment] 2020-04-11 16:27
Does anyone know another e621-downloader that is working with new site update?
