### ISSUE TITLE
chan.sankakucomplex.com disappears from the sources after closing the application

### ISSUE THREAD

**Issue by Rarz** [Bionus/imgbrd-grabber#1988] opened 2020-05-31 20:02 UTC
**Bug description**

After installing Grabber chan.sankakucomplex.com is a source you can select. After downloading stuff and closing the program, restarting leaves you without chan.sankakucomplex.com as source to select.

**Steps to reproduce**

1. Download grabber Grabber_v7.2.1_x64.exe
2. Install Grabber. You don't even need to uninstall the previous version.
2. Click on 'Sources'
3. Check to see that chan.sankakucomplex.com is available
4. Close program.
5. Restart program.
6. Click on 'Sources'
7. See that chan.sankakucomplex.com is no longer available as source.

**Expected behavior**

Whatever source you have selected should remain available the next time the program is started.

**Context**

[settings.zip](https://github.com/Bionus/imgbrd-grabber/files/4708292/settings.zip)

'mail.log':
**[21:52:52.175][Warning] Javascript model not found for Sankaku**
[21:52:52.185][Info] Temp directory purged of 0/0 files (0 failed)
[21:52:52.442][Info] New session started.
[21:52:52.443][Info] Software version: 7.2.1.
[21:52:52.443][Info] Software CPU architecture: x64.
[21:52:52.443][Info] Computer CPU architecture: x86_64.
[21:52:52.443][Info] Qt CPU architecture: x86_64.
[21:52:52.444][Info] Computer platform: Windows 10 (10.0).
[21:52:52.444][Info] Path: `C:/Program Files/Grabber`
[21:52:52.444][Info] Loading preferences from `C:/Users/Meep/AppData/Local/Bionus/Grabber/settings.ini`
[21:52:52.445][Info] Temporary path: `C:/Users/Meep/AppData/Local/Temp\Grabber`
[21:52:52.447][Info] SSL libraries: OpenSSL 1.1.1d  10 Sep 2019
[21:52:52.472][Info] Setting language to ''...
[21:52:52.473][Info] 20 sources found: anime-pictures.net (Anime pictures), api.twitter.com (Twitter), behoimi.org (Danbooru), danbooru.donmai.us (Danbooru (2.0)), derpibooru.org (Booru-on-rails), e-hentai.org (E-Hentai), e621.net (Danbooru), exhentai.org (E-Hentai), gelbooru.com (Gelbooru (0.2)), hijiribe.donmai.us (Danbooru (2.0)), konachan.com (Moebooru), nhentai.net (NHentai), rule34.paheal.net (Shimmie), rule34.xxx (Gelbooru (0.2)), safebooru.org (Gelbooru (0.2)), sonohara.donmai.us (Danbooru (2.0)), tentaclerape.net (Shimmie), www.pixiv.net (Pixiv), www.zerochan.net (Zerochan), yande.re (Moebooru)
[21:52:52.492][Info] Updating checkboxes.
[21:52:52.495][Info] Updating checkboxes.
[21:52:52.498][Info] Monitoring starting
[21:52:52.567][Info] Monitoring tick
[21:52:52.567][Info] Monitoring finished
[21:52:52.599][Warning] [Qt][default] QString::arg: Argument missing: Error posting message: %s, Host www.google-analytics.com not found

**Screenshots**

Immediately after installation:

![Sankaku present immediately after installing](https://user-images.githubusercontent.com/820610/83361539-2e8c9180-a38a-11ea-9072-9fcfbb90d272.png)

Second time Grabber is started:

![Sankaku missing](https://user-images.githubusercontent.com/820610/83361540-33e9dc00-a38a-11ea-87a7-6b6b9a89c8fa.png)

**System information**

- OS: Windows 10
- Grabber version: 7.2.1 x64

**Comment by Rarz** [comment] 2020-06-01 04:58
In addition, I think the first time I installed Grabber, it asks which source you want or add a new one. I think I added the chan server there. Since that worked and let me browse, I thought nothing of it at the time. After that it started behaving like described in the bug.

**Comment by yami-no-tusbas** [comment] 2020-06-01 08:13
It the will of the dev, some desagreament with sankaku devs, so Bionus has removed the option. Maybe the installer still put the file at installation, but grabber will remove it at launch.

Sry, this is not a bug, it's a feature now !

**Comment by Rarz** [comment] 2020-06-01 10:06
Well, that severely limits the usefulness of the program for a subset of the users. Anyway, thank you for the reply.

**Comment by Bionus** [comment] 2020-06-01 14:05
I'll close as a duplicate of #1888, and I think everything was said in that issue, including alternatives on how to install sources manually. But you're free to comment there instead.

> It's the will of the dev, some desagreament with sankaku devs, so Bionus has removed the option. Maybe the installer still put the file at installation, but grabber will remove it at launch.
>
> Sry, this is not a bug, it's a feature now !

That should be the opposite, hence it's a bug, not a feature.

The installer does not include the Sankaku files anymore (reasons explained in the other issue), but Grabber is not supposed to delete anything from your installation folder if you add them yourself. And if it does, that's a bug.

A bug that, AFAIK, I have fixed in the [Nightly version](https://github.com/Bionus/imgbrd-grabber/releases/nightly).

**Closed by Bionus** 2020-06-01 14:05 UTC
Labels: bug
