### ISSUE TITLE
sankaku complex won't download like before

### ISSUE THREAD

**Issue by naruhina2016** [Bionus/imgbrd-grabber#1010] opened 2017-07-27 14:29 UTC
### What steps will reproduce the problem?
it wont download complete sets of pictures that comes from sankaku complex

### What is the expected behavior? What do you get instead?
it downloads less and get access denied on their website 

### How often does this problem occur?
it happens everytime

### What version of the program are you using? On what operating system?
image grabber version 5.4.2 on windows 10

### Please provide any additional information below
it wont download complete sets of pictures

**Comment by urzuse7en** [comment] 2017-07-28 00:23
Duplicate of #997 
Sankaku is not really working now. They're changed something in their site and blocks grabber user's IP because they see it as a potential threat.

**Comment by Bionus** [comment] 2017-07-28 10:41
See the issue mentioned above for more info, Sankaku is blocking downloaders.
I'll close this issue.

**Closed by Bionus** 2017-07-28 10:41 UTC
Labels: duplicate
