### ISSUE TITLE
Images are not loading for certain queries or page ranges even though it works manually.

### ISSUE THREAD

**Issue by Silvernine0S** [Bionus/imgbrd-grabber#1788] opened 2019-09-27 22:43 UTC
The latest version of Grabber, 7.1.1. Default settings for everything. Source used is yande.re.

Query Used: id:552746..573896
Loading the first page works perfectly fine and Grabber states there are 951 total pages and currently on page 1, 20 images are shown out of 19018. Proceed to go to the last page and it will fail with:
yande.re - No result
No valid source of the site returned result.

However, if you were to click on the blue "yande.re" link and opened up the page manually, you will see there are actual results. In addition, if you manually increment the page numbers through the URL, you will still get results past 951. So the total page should be more than 951.

Another example is using the query: id:550746..573896
Loading pg 1043 and 1046 will work fine but pages in between them, pg 1044 and 1045, will result in the same error as before:
"yande.re - No result"
No valid source of the site returned result.

**Comment by pencilbook** [comment] 2019-10-02 22:23
I've had this issue for months, can confirm it is a real issue and it is annoying.

It happens too frequently. It will also refuse to download images.

**Comment by Bionus** [comment] 2019-10-20 10:14
I could indeed reproduce the issue, and the logs give the reason:

```
[12:07:25.330][Warning] [yande.re][Xml] Uncaught exception at line 2: TypeError: Cannot read property 'length' of undefined
[12:07:25.331][Warning] [yande.re] Loading using Xml failed. Retry using Json.
[12:07:25.401][Warning] [yande.re][Json] Uncaught exception at line 2: TypeError: Cannot read property 'length' of undefined
[12:07:25.402][Warning] [yande.re] Loading using Json failed. Retry using Html.
[12:07:25.524][Warning] [yande.re][Html] Uncaught exception at line 2: TypeError: Cannot read property 'length' of undefined
[12:07:25.526][Warning] [yande.re] No valid source of the site returned result.
```

It is caused by a small bug in the code when encountering deleted images, which happen on the specific pages you mention. I just pushed a fix which should solve the issue.

**Closed** 2020-02-28 18:25 UTC
Labels: bug, source
