### ISSUE TITLE
Pixiv login error

### ISSUE THREAD

**Issue by aymanA123** [Bionus/imgbrd-grabber#2300] opened 2021-03-17 12:00 UTC
**Bug description**

every time i try to log into pixiv i get hit with this error :
[12:55:29.461][Info] [www.pixiv.net] Logging in...
[12:55:31.115][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
[12:55:31.116][Info] [www.pixiv.net] Login finished: failure.

it's been like this for a while now

**Expected behavior**
log into pixiv like it used to do normally .

**System information**
windows 10

**Comment by Bionus** [comment] 2021-03-17 13:11
Closing as duplicate of #2263
There doesn't seem to be a proper workaround as of now but I'm investigating

**Closed by Bionus** 2021-03-17 13:11 UTC
