### ISSUE TITLE
Gelbooru Download All Not Working 

### ISSUE THREAD

**Issue by heeltwo** [Bionus/imgbrd-grabber#1411] opened 2018-09-09 08:59 UTC
Issue: https://i.imgur.com/dJdh54g.png

It gives me that and the only workaround is to copy the link and remove "simg4" from the beginning of all the links, kinda frustrating.

**Comment by Bionus** [comment] 2018-09-09 18:49
Looks like a duplicate of #1410, moving to there.

**Closed by Bionus** 2018-09-09 18:49 UTC
